Repository red-hat-storage/cephci, pull requests merged in 2021-08, with the labels that each got.

#681 Increased delay time for resolving sync issue
  utility/utils.py
Labels: RGW, pr-verified

#672 Remove a service using Orch command
  ceph/ceph_admin/orch.py
  suites/pacific/cephadm/tier1_ssl_dashboard_port.yaml
  tests/cephadm/test_orch.py
Labels: cephadm-orchestrator

#682 Fix pool node issue and update "osd_scenario" as part of node attributes
  ceph/ceph.py
  ceph/utils.py
  utility/utils.py
Labels: framework

#685 Fix ntp command execution code issue
  ceph/utils.py
Labels: framework

#689 use id from inventory flle to check distro type
  run.py
Labels: framework, pr-verified

#702 FIX#701: use beta compose as N-1 pre-upgrade build
  suites/pacific/cephadm/tier1_cephadm_upgrade.yaml
Labels: Upgrade, Tier-1

#686 Added Nautilus tier-1 test suites
  conf/nautilus/ansible/tier_1_deploy.yaml
  conf/nautilus/upgrades/tier_1_upgrade.yaml
  pipeline/4/Jenkinsfile-tier-1-deploy.groovy
  suites/nautilus/ansible/tier_1_deploy.yaml
  suites/nautilus/upgrades/tier_1_upgrade_container.yaml
  suites/nautilus/upgrades/tier_1_upgrade_rpm.yaml
Labels: Tier-1, Nautilus

#699 Include CephCI API documentation on readthedocs
  .readthedocs.yaml
  ceph/ceph.py
  ceph/ceph_admin/__init__.py
  ceph/ceph_admin/add.py
  ceph/ceph_admin/alert_manager.py
  ceph/ceph_admin/apply.py
  ceph/ceph_admin/bootstrap.py
  ceph/ceph_admin/common.py
  ceph/ceph_admin/crash.py
  ceph/ceph_admin/daemon.py
  ceph/ceph_admin/device.py
  ceph/ceph_admin/grafana.py
  ceph/ceph_admin/helper.py
  ceph/ceph_admin/host.py
  ceph/ceph_admin/iscsi.py
  ceph/ceph_admin/ls.py
  ceph/ceph_admin/mds.py
  ceph/ceph_admin/mgr.py
  ceph/ceph_admin/mon.py
  ceph/ceph_admin/nfs.py
  ceph/ceph_admin/node_exporter.py
  ceph/ceph_admin/orch.py
  ceph/ceph_admin/osd.py
  ceph/ceph_admin/prometheus.py
  ceph/ceph_admin/ps.py
  ceph/ceph_admin/rbd_mirror.py
  ceph/ceph_admin/reconfig.py
  ceph/ceph_admin/redeploy.py
  ceph/ceph_admin/remove.py
  ceph/ceph_admin/restart.py
  ceph/ceph_admin/rgw.py
  ceph/ceph_admin/rm.py
  ceph/ceph_admin/shell.py
  ceph/ceph_admin/start.py
  ceph/ceph_admin/stop.py
  ceph/ceph_admin/upgrade.py
  ceph/rados/rados_bench.py
  ceph/rados_utils.py
  ceph/utils.py
  docs/conf.py
  docs/index.rst
  docs/requirements.txt
  docs/source/welcome.md
Labels: framework

#708 Deployment of CephFS-Mirror.
  ceph/ceph_admin/cephfs_mirror.py
  conf/pacific/cephfs/tier_1_cephfs_mirror.yaml
  suites/pacific/cephfs/tier_1_cephfs_mirror.yaml
  tests/ceph_installer/test_cephadm.py
Labels: Ceph-FS, Tier-1

#723 Update git ignore file
  .gitignore
Labels: enhancement, Tier-1, Nautilus

#713 Added code support for OSD daemon removal and verify
  ceph/ceph_admin/osd.py
  suites/pacific/cephadm/tier1_ssl_dashboard_port.yaml
  tests/cephadm/test_osd.py
Labels: cephadm-orchestrator

#730 rgw: add external IO config
  suites/nautilus/rgw/tier_1_rgw_multisite_primary_to_secondary.yaml
  suites/nautilus/rgw/tier_1_rgw_multisite_secondary_to_primary.yaml
  tests/rgw/sanity_rgw.py
  tests/rgw/sanity_rgw_multisite.py
Labels: pr-verified, RGW

#732 flake8 and tox to requirements
  requirements.txt
Labels: framework
