Repository red-hat-storage/cephci, pull requests merged in 2021-09, with the labels that each got.

#757 Adding RHCS 4.3 rhel-7 repo
  rhbuild.yaml
Labels: new-build

#760 add datalog omap tests to t1_extn suite
  suites/nautilus/rgw/tier_1_extn_rgw_multisite_primary_to_secondary.yaml
  suites/nautilus/rgw/tier_1_extn_rgw_multisite_secondary_to_primary.yaml
  suites/pacific/rgw/tier_1_extn_rgw_multisite_primary_to_secondary.yaml
  suites/pacific/rgw/tier_1_extn_rgw_multisite_secondary_to_primary.yaml
Labels: pr-verified, RGW

#698 Dashboard enable and validate dashboard login Tests
  ceph/ceph_admin/dashboard.py
  suites/pacific/cephadm/tier1_skip_dashboard.yaml
  tests/cephadm/test_dashboard.py
Labels: Ceph-dashboard, cephadm-orchestrator

#741 Tier-0 generic execution Jenkins Job configuration
  pipeline/executors/Jenkinsfile-tier-0.groovy
  pipeline/scripts/5/0/tier-0/0_deploy.sh
  pipeline/scripts/5/0/tier-0/1_object.sh
  pipeline/vars/lib.groovy
Labels: Jenkins, Tier-0

#764 Adding pipeline script for updating rc container image details
  pipeline/signed-container-image-listener.groovy
Labels: lgtm, approved

#769 Add Pipeline version 2 initial support
  run.py
  utility/utils.py
Labels: enhancement, P0, framework, lgtm, approved

#773 Fix Tier-0 executor
  pipeline/tier-0.groovy
  pipeline/vars/lib.groovy
Labels: lgtm, approved

#775 Fix cleanup issue
  run.py
Labels: lgtm

#777 Moving to shallow clone
  pipeline/signed-compose-listener.groovy
  pipeline/signed-container-image-listener.groovy
Labels: lgtm

#781 Enhance tier-x executor
  pipeline/tier-0.groovy
  pipeline/tier-x.groovy
Labels: approved

#770 Modified the suite to enable dashboard in multisite
  suites/nautilus/rgw/sanity_rgw_multisite.yaml
Labels: lgtm, approved

#782 [Bz 1997080]: fixes docker-to-podman issue in tier1
  tests/ceph_ansible/test_ansible_roll_over.py
Labels: ceph-ansible, lgtm, approved

#783 Tierx executor enhance
  pipeline/tier-x.groovy
  pipeline/vars/lib.groovy
Labels: lgtm, approved

#784 Fix script-path in tier-0 executor
  pipeline/vars/lib.groovy
Labels: lgtm, approved

#785 cvp 5.0 updates
  pipeline/5/Jenkinsfile-tier-0.groovy
  pipeline/vars/common.groovy
Labels: lgtm, approved

#786 Modify testrbd as per cephci version2 changes
  run.py
Labels: lgtm, approved

#788 [4x][CI] Scripts to execute tier-0 test suites
  pipeline/scripts/4/2/tier-0/test-cephfs-core-features.sh
  pipeline/scripts/4/2/tier-0/test-rbd-core-features.sh
  pipeline/scripts/4/2/tier-0/test-rgw-core-features.sh
  pipeline/scripts/4/2/tier-0/test-rhceph-image-on-rhel-7.sh
  pipeline/scripts/4/2/tier-0/test-rhceph-image-on-rhel-8.sh
  pipeline/scripts/4/2/tier-0/test-rhceph-rhel-7-rpm.sh
  pipeline/scripts/4/2/tier-0/test-rhceph-rhel-8-rpm.sh
  pipeline/scripts/4/3/tier-0/test-cephfs-core-features.sh
  pipeline/scripts/4/3/tier-0/test-rbd-core-features.sh
  pipeline/scripts/4/3/tier-0/test-rgw-core-features.sh
  pipeline/scripts/4/3/tier-0/test-rhceph-image-on-rhel-7.sh
  pipeline/scripts/4/3/tier-0/test-rhceph-image-on-rhel-8.sh
  pipeline/scripts/4/3/tier-0/test-rhceph-rhel-7-rpm.sh
  pipeline/scripts/4/3/tier-0/test-rhceph-rhel-8-rpm.sh
  pipeline/vars/lib.groovy
Labels: lgtm, approved

#707 Adding tests to perform orch and host maintenance operations
  ceph/ceph_admin/host.py
  ceph/ceph_admin/maintenance.py
  ceph/ceph_admin/ps.py
  suites/pacific/cephadm/tier1_ssl_dashboard_port.yaml
Labels: lgtm, approved

#789 Adding 5x tier1 scripts
  pipeline/scripts/5/0/tier-1/010_deploy.sh
  pipeline/scripts/5/0/tier-1/020_object.sh
  pipeline/scripts/5/0/tier-1/test-bootstrap-custom-ssl-dashboard-port-and-apply-spec.sh
  pipeline/scripts/5/0/tier-1/test-bootstrap-skip-dashboard-and-custom-ceph-directory-organisation.sh
  pipeline/scripts/5/0/tier-1/test-cephadm-apply-service-spec.sh
  pipeline/scripts/5/0/tier-1/test-cephadm-upgrade-build-to-build-5x.sh
  pipeline/scripts/5/0/tier-1/test-cephfs-extended-mat.sh
  pipeline/scripts/5/0/tier-1/test-rbd-extended-mat.sh
  pipeline/scripts/5/0/tier-1/test-rbd-mirror-functionality.sh
  pipeline/scripts/5/0/tier-1/test-rgw-multi-site-primary-to-secondary.sh
  pipeline/scripts/5/0/tier-1/test-rgw-multi-site-secondary-to-primary.sh
  pipeline/scripts/5/0/tier-1/test-rgw-single-site.sh
  pipeline/scripts/5/0/tier-1/test-upgrade-4x-container-to-5x-container.sh
  pipeline/scripts/5/0/tier-1/test-upgrade-4x-rpm-to-5x-container.sh
Labels: lgtm, approved

#790 /misc-env/exec.py:Fix translate definition issue
  tests/misc_env/exec.py
Labels: lgtm, approved

#791 [4x][CI] Scripts to execute tier-1 test suites
  pipeline/scripts/4/2/tier-1/test-cephfs-extended-mat.sh
  pipeline/scripts/4/2/tier-1/test-rbd-extended-mat.sh
  pipeline/scripts/4/2/tier-1/test-rbd-mirror-functionality.sh
  pipeline/scripts/4/2/tier-1/test-rgw-multi-site-primary-to-secondary.sh
  pipeline/scripts/4/2/tier-1/test-rgw-multi-site-secondary-to-primary.sh
  pipeline/scripts/4/2/tier-1/test-rgw-single-site.sh
  pipeline/scripts/4/2/tier-1/test-rhceph-rhel-7-rpm-deployment.sh
  pipeline/scripts/4/2/tier-1/test-upgrade-of-rpm-based-deployments.sh
  pipeline/scripts/4/2/tier-1/test-upgrade-on-container-based-deployments.sh
  pipeline/scripts/4/3/tier-1/test-cephfs-extended-mat.sh
  pipeline/scripts/4/3/tier-1/test-rbd-extended-mat.sh
  pipeline/scripts/4/3/tier-1/test-rbd-mirror-functionality.sh
  pipeline/scripts/4/3/tier-1/test-rgw-multi-site-primary-to-secondary.sh
  pipeline/scripts/4/3/tier-1/test-rgw-multi-site-secondary-to-primary.sh
  pipeline/scripts/4/3/tier-1/test-rgw-single-site.sh
  pipeline/scripts/4/3/tier-1/test-rhceph-rhel-7-rpm-deployment.sh
  pipeline/scripts/4/3/tier-1/test-upgrade-of-rpm-based-deployments.sh
  pipeline/scripts/4/3/tier-1/test-upgrade-on-container-based-deployments.sh
Labels: lgtm, approved

#787 Add support to upload binaries to IBM COS
  cephci.yaml.template
  pipeline/scripts/ci/upload_compose.py
  pipeline/vars/lib.groovy
  requirements.txt
  setup.py
  storage/__init__.py
  storage/ibm_cos.py
Labels: lgtm, approved

#792 *_directory methods are not supported on Python 3.7
  storage/ibm_cos.py
Labels: lgtm, approved

#793 [CI] Script to execute a tier-2 test suite
  pipeline/scripts/5/0/tier-2/020_object.sh
  pipeline/scripts/5/0/tier-2/test-rgw-regression.sh
  pipeline/scripts/5/0/tier-2/test-rgw-secure-s3.sh
  pipeline/scripts/5/0/tier-2/test-rgw-ssl-multisite-verify-io-from-primary.sh
Labels: lgtm, approved

#795 Removing pipeline v1 artificates that have moved to v2
  pipeline/4/Jenkinsfile-tier-0-rhel-7.groovy
  pipeline/4/Jenkinsfile-tier-0.groovy
  pipeline/4/Jenkinsfile-tier-1-cephfs.groovy
  pipeline/4/Jenkinsfile-tier-1-deploy.groovy
  pipeline/4/Jenkinsfile-tier-1-object.groovy
  pipeline/4/Jenkinsfile-tier-1-rbd.groovy
  pipeline/4/Jenkinsfile-tier-1-wrapper.groovy
  pipeline/5/Jenkinsfile-tier-1-cephfs.groovy
  pipeline/5/Jenkinsfile-tier-1-deploy.groovy
  pipeline/5/Jenkinsfile-tier-1-object.groovy
  pipeline/5/Jenkinsfile-tier-1-rbd.groovy
  pipeline/5/Jenkinsfile-tier-1-wrapper.groovy
  pipeline/5/Jenkinsfile-tier-2-object-regression.groovy
  pipeline/5/Jenkinsfile-tier-2-object-wrapper.groovy
Labels: lgtm, approved

#796 Disabling SSL verification by default
  ceph/ceph.py
  ceph/utils.py
  run.py
  utility/utils.py
Labels: lgtm, approved

#794 Added missing polarian ids for TCs
  suites/nautilus/rgw/tier_1_rgw_multisite_primary_to_secondary.yaml
  suites/nautilus/rgw/tier_1_rgw_multisite_secondary_to_primary.yaml
  suites/pacific/rgw/tier1_rgw_multisite_primary_to_secondary.yaml
  suites/pacific/rgw/tier1_rgw_multisite_secondary_to_primary.yaml
Labels: lgtm, approved

#797 Enable support for uploading objects to IBM COS in the listeners
  pipeline/scripts/ci/upload_compose.py
  pipeline/signed-compose-listener.groovy
  pipeline/unsigned-compose-listener.groovy
  pipeline/vars/lib.groovy
Labels: lgtm, approved

#807 sts: server side copy test case
  suites/nautilus/rgw/tier_1_object.yaml
  suites/pacific/rgw/tier_1_object.yaml
Labels: pr-verified, RGW

#740 Client authorize test
  suites/nautilus/cephfs/tier_1_fs.yaml
  suites/pacific/cephfs/tier_1_fs.yaml
  tests/cephfs/cephfs_utilsV1.py
  tests/cephfs/client_authorize.py
Labels: lgtm

#822 add comment section in email template
  run.py
  templates/result-email-template.html
Labels: framework

#823 Fix email results
  run.py
Labels: framework

#825 Fix email results: None object issue
  run.py
Labels: framework

#826 correct comments placement
  suites/pacific/rgw/tier_1_extn_object.yaml
Labels: RGW

#824 sts: fix filename typo of server side copy test case script name
  suites/nautilus/rgw/tier_1_extn_object.yaml
  suites/nautilus/rgw/tier_1_object.yaml
  suites/pacific/rgw/tier_1_extn_object.yaml
  suites/pacific/rgw/tier_1_object.yaml
  suites/pacific/rgw/tier_2_rgw_regression.yaml
Labels: needs-qa, RGW
