Repository red-hat-storage/cephci, pull requests merged in 2022-11, with the labels that each got.

#1926 change execution to rgw for kafka tests
  suites/pacific/rgw/tier-2_rgw_test-bucket-notifications.yaml
  suites/pacific/rgw/tier-2_rgw_test_5.3_specific_fixes.yaml
Labels: pr-verified, RGW

#1928 [subscription]: switch to SCA(simple content Access)
  tests/misc_env/install_prereq.py
Labels: framework

#1908 [Report Portal] [Launches] [Metadata] Adding additional report portal launches metadata.
  run.py
Labels: Report Portal

#1933 Fix IBM tier-0 suite
  conf/inventory/ibm-vpc-rhel-9.0-minimal-amd64-1.yaml
Labels: P0, framework

#1932 Fix test-basic-object-operations.yaml to be run from rgw nodes
  suites/quincy/rgw/test-basic-object-operations.yaml
Labels: pr-verified, RGW

#1938 rgw-ms: async notification tests to be run from rgw nodes
  suites/pacific/rgw/tier-2_rgw_test-multisite-async-data-notification.yaml
Labels: RGW

#1940 Execute quota_managment suite from rgw node
  suites/pacific/rgw/tier-2_rgw_test-quota-management.yaml
Labels: pr-verified, RGW

#1942 Fix suite name in 6.0 metadata file
  pipeline/metadata/6.0.yaml
Labels: RGW

#1944 Running version 1 scripts from RGW node for 6.x
  suites/quincy/rgw/tier-2_rgw_regression.yaml
Labels: RGW

#1941 [FS]Fixing the mutlifs issue 1924
  tests/cephfs/cephfs_utilsV1.py
  tests/cephfs/multifs/multifs_multiplefs.py
Labels: Ceph-FS

#1953 Removing rgw testcase from tier-0
  suites/pacific/cephadm/tier-0.yaml
  suites/quincy/cephadm/tier-0.yaml
Labels: RGW

#1943 Adding suite tier-1-extn t- quincy with Rate limiting and NFS tests
  pipeline/metadata/6.0.yaml
  suites/quincy/rgw/tier-1-extn_rgw.yaml
Labels: RGW

#1951 Run s3cmd suite from client node
  suites/pacific/rgw/tier-2_rgw_test-using-s3cmd.yaml
Labels: pr-verified, RGW

#1964 [IBM]: Fix root login issue
  conf/inventory/ibm-vpc-rhel-9.0-minimal-amd64-1.yaml
  tests/misc_env/install_prereq.py
Labels: framework

#1954 Add support to run 5.3 rgw suites on rhel-9 platform
  pipeline/metadata/5.3.yaml
Labels: pr-verified, RGW, PipelineV3.0

#1965 Including rgw testcase as a part of tier-0 build validation
  suites/pacific/cephadm/tier-0.yaml
  suites/quincy/cephadm/tier-0.yaml
Labels: pr-verified, RGW

#1958 cephci changes to get exact line and method from which the log was logged
  run.py
  utility/log.py
  utility/utils.py
Labels: pr-verified

#1975 Adding ceph version to pipeline description
  pipeline/tier_executor.groovy
Labels: PipelineV3.0

#1974 Send email only when test stages are available
  pipeline/tier_executor.groovy
Labels: PipelineV3.0

#1968 Fix for IBM status failure when cleanup fails.
  pipeline/tier_executor.groovy
Labels: PipelineV3.0

#1972 tier-2_rgw_test-quota-management suite execute from client-node
  suites/pacific/rgw/tier-2_rgw_test-quota-management.yaml
Labels: pr-verified, RGW

#1824 [Automation] Add tc to validate migration from 4.0 to 5.0, no RGW con…
  conf/pacific/upgrades/upgrades_6_osds.yaml
  suites/pacific/upgrades/tier-1_upgrade_test-4x-to-5x-container_data_pool.yaml
Labels: DMFG

#1982 correcting ceph version in build description
  pipeline/tier_executor.groovy
Labels: PipelineV3.0

#1910 Automation - CEPH-83574741-RBD-mirror:Removal of failed back image sh…
  suites/pacific/rbd/tier-2_rbd_mirror_regression.yaml
  suites/quincy/rbd/tier-2_rbd_mirror_regression.yaml
  tests/rbd_mirror/rbd_mirror_utils.py
  tests/rbd_mirror/test-image-delete-from-secondary.py
Labels: DNM, RBD

#1979 Including grafana service in conf to support 4.x ms
  conf/pacific/rgw/rgw_multisite.yaml
Labels: pr-verified, RGW

#1977 Adding retry for DNS remove operations in IBM
  compute/ibm_vpc.py
Labels: framework

#1984 Include run-on-rgw for pre-upgrdae testcase in nautilus to pacific up…
  suites/pacific/rgw/tier-1_rgw_multisite_test-upgrade-4-to-latest.yaml
  suites/pacific/rgw/tier-1_rgw_ssl_test-upgrade-4-to-latest.yaml
  suites/pacific/rgw/tier-1_rgw_test-upgrade-4-to-latest.yaml
Labels: RGW

#1985 Adding abort on fail for preflight test case
  suites/pacific/upgrades/tier-1_upgrade_test-4x-to-5x-rpm.yaml
Labels: cephadm-ansible

#1970 [Scale FS] Creating max subvolumes with 1 gb each
  suites/quincy/cephfs/tier-2_fs_scale.yaml
  tests/cephfs/cephfs_scale/max_smallfile_snap.py
  tests/cephfs/cephfs_scale/max_subvolumes.py
Labels: Ceph-FS, work-in-progress
