Repository red-hat-storage/cephci, pull requests merged in 2023-12, with the labels that each got.

#3201 Handle IBM nvmeof cli image pull failures
  ceph/nvmeof/nvmeof_gwcli.py
Labels: lgtm

#3204 [Interop] Add rhel interop tests for reef
  conf/reef/integrations/6node-all-roles.yaml
  pipeline/scripts/interop/test-ceph-features.sh
  suites/reef/interop/test-ceph-sanity.yaml
Labels: InterOp, lgtm

#3198 Adding ceph_nodename param to baremetal
  run.py
Labels: lgtm

#3203 fix nvmeof add_listener for multi GW configuration
  ceph/nvmeof/nvmeof_gwcli.py
  tests/nvmeof/test_ceph_nvmeof_data_integrity.py
  tests/nvmeof/test_ceph_nvmeof_gateway.py
  tests/nvmeof/test_ceph_nvmeof_gateway_scale.py
  tests/nvmeof/test_ceph_nvmeof_neg_tests.py
  tests/nvmeof/test_ceph_nvmeof_sub_limit.py
  tests/nvmeof/test_io_perf.py
  tests/nvmeof/test_nvme_cli.py
Labels: lgtm, nvmeof

#3196 Removing "abort-on-fail" for enabling monitoring service tc
  suites/pacific/rgw/tier-1_longevity.yaml
  suites/pacific/rgw/tier-1_rgw_ecpool_ms-bucket-listing-versioning-on-primary.yaml
  suites/pacific/rgw/tier-1_rgw_ms-bilog-crash-on-primary.yaml
  suites/pacific/rgw/tier-1_rgw_ms-bucket-listing-versioning-on-secondary.yaml
  suites/pacific/rgw/tier-1_rgw_ms-omap-datalog-on-primary.yaml
  suites/pacific/rgw/tier-1_rgw_multisite_multirealm_upgrade-5-to-latest.yaml
  suites/pacific/rgw/tier-1_rgw_multisite_upgrade-5-to-latest.yaml
  suites/pacific/rgw/tier-1_rgw_ssl_multisite_test-upgrade-5-to-latest.yaml
  suites/pacific/rgw/tier-2_rgw_ms_test-bucket-notifications.yaml
  suites/pacific/rgw/tier-2_rgw_singlesite_to_multisite.yaml
  suites/pacific/rgw/tier-2_rgw_ssl_ecpool-ms-bucket-listing-versioning-on-secondary.yaml
  suites/pacific/rgw/tier-2_rgw_ssl_ecpool_ms-bucket-objects-gc-policy-on-secondary.yaml
  suites/pacific/rgw/tier-2_rgw_test-multisite-async-data-notification.yaml
  suites/pacific/rgw/tier-2_rgw_test-multisite-metadata-sync.yaml
  suites/quincy/baremetal_pipeline/tier-1_rgw_ms.yaml
  suites/quincy/rgw/tier-1_rgw_ms_upgrade_5-3_latest_to_6x_latest.yaml
  suites/quincy/rgw/tier-1_rgw_ms_upgrade_6-0GA_to_6x_latest.yaml
  suites/quincy/rgw/tier-1_rgw_multisite.yaml
  suites/reef/rgw/tier-1_rgw_ms_datalog_and_crash.yaml
  suites/reef/rgw/tier-1_rgw_ms_upgrade_5_3GA_to_7x_latest.yaml
  suites/reef/rgw/tier-1_rgw_ms_upgrade_6_1GA_to_7x_latest.yaml
  suites/reef/rgw/tier-1_rgw_ms_upgrade_multirealm_61GA_to_7x_latest.yaml
  suites/reef/rgw/tier-1_rgw_multisite.yaml
  suites/reef/rgw/tier-2_rgw_ms_async_data_notification.yaml
  suites/reef/rgw/tier-2_rgw_singlesite_to_multisite.yaml
  suites/reef/rgw/tier-2_ssl_rgw_ms_ecpool_test.yaml
Labels: RGW, lgtm, tfa-issue-fix

#3170 CEPH-10704: Deployment of 3 way multisite with network latency defined.
  conf/reef/rgw/3-way-ms-ec-profile-2+2@4nodes.yaml
  suites/reef/rgw/tier-2_rgw_3_way_multisite.yaml
  tests/rgw/sanity_rgw_multisite.py
Labels: lgtm

#3161 [Tier2] OSD redeployment creates collocated OSD
  suites/quincy/ceph_volume/tier2-ceph-volume-redeploy.yaml
  suites/reef/ceph_volume/tier2-ceph-volume-redeploy.yaml
  tests/ceph_volume/test_ceph_volume_non_collocated.py
Labels: lgtm

#3207 [Automation][Cephadm][Tier2]Cephadm custom config support
  cli/utilities/containers.py
  suites/quincy/cephadm/tier-2-bootstrap-along-with-spec-file.yaml
  tests/cephadm/test_cephadm_custom_config_support.py
Labels: lgtm, CephAdm, DMFG

#3158 CEPH-83575917: Test archive site on/off on an upload of 5K objects
  suites/reef/rgw/tier-2_rgw_ms_archive_with_haproxy.yaml
Labels: RGW, lgtm, Tier-4

#3212 [test-fix] Add fix for cephadm log spam failure
  suites/reef/cephadm/tier1-service-apply-spec.yaml
  tests/cephadm/test_cephadm_log_spam.py
Labels: lgtm, DMFG, tfa-issue-fix

#3205 [Interop] Update rhel interop script to support specific ceph version
  pipeline/scripts/interop/README.md
  pipeline/scripts/interop/test-ceph-features.sh
Labels: InterOp, lgtm

#3214 Adding upgrade suites for reef and quincy
  suites/quincy/cephfs/tier-0_cephfs_mirrror_upgrade_53_to_6x.yaml
  suites/quincy/cephfs/tier-0_cephfs_mirrror_upgrade_ibm_53_to_6x.yaml
  suites/quincy/cephfs/tier-0_cephfs_upgrade_ibm_5x_to_6x.yaml
  suites/reef/cephfs/tier-0_cephfs_mirrror_upgrade_ibm_6x_to_7x.yaml
Labels: lgtm

#3206 Recreating secondary cluster after permanent failure
  suites/pacific/rbd/tier-2_rbd_mirror_recreate_secondary_cluster.yaml
  suites/quincy/rbd/tier-2_rbd_mirror_recreate_secondary_cluster.yaml
  suites/reef/rbd/tier-2_rbd_mirror_recreate_secondary_cluster.yaml
  tests/rbd_mirror/rbd_mirror_reconfigure_secondary_cluster.py
  tests/rbd_mirror/rbd_mirror_utils.py
  tests/rbd_mirror/test_configure_mirror_snapshot.py
Labels: RBD, lgtm, approved

#3210 Enhance nvmeof sanity for vmware clients
  conf/reef/nvmeof/ceph_nvmeof_vmware_sanity.yaml
  suites/reef/nvmeof/tier-0_nvmeof_bdev_vmware_esx.yaml
  suites/reef/nvmeof/tier-0_nvmeof_vmware_esx_sanity.yaml
  tests/nvmeof/test_ceph_nvmeof_vmware_clients.py
Labels: lgtm, nvmeof

#3218 CEPH-83575455: Perform NVMeOF Initiator access failures
  ceph/nvmeof/initiator.py
  suites/reef/nvmeof/tier-1_nvmeof_functional_Regression.yaml
  tests/nvmeof/test_ceph_nvmeof_neg_tests.py
Labels: lgtm, nvmeof

#3151 Changes after analysing baremetal pipeline failures
  ceph/rbd/workflows/krbd_io_handler.py
  ceph/rbd/workflows/rbd.py
  suites/quincy/rbd/tier-2_rbd_cache_scenarios.yaml
  suites/quincy/rbd/tier-3_rbd_persistent_write_back_cache.yaml
  suites/reef/rbd/tier-1_rbd.yaml
  suites/reef/rbd/tier-2_rbd_cache_scenarios.yaml
  suites/reef/rbd/tier-2_rbd_encryption.yaml
  suites/reef/rbd/tier-2_rbd_regression_Image_migration.yaml
  suites/reef/rbd/tier-3_rbd_persistent_write_back_cache.yaml
  suites/reef/rbd/tier-4_rbd_negative_scenario_regression.yaml
  tests/rbd/krbd_io_handler.py
  tests/rbd/rbd_clone_delete_parent_image.py
  tests/rbd/rbd_utils.py
  tests/rbd/test_concurrent_write_pwl_cache.py
  tests/rbd/test_performance_pwl_cache.py
  tests/rbd/test_rbd.py
  tests/rbd/test_rbd_deep_flatten_negative.py
  tests/rbd/test_rbd_dm_cache.py
  tests/rbd/test_rbd_immutable_cache.py
  tests/rbd/test_rbd_migration_image_s3_object.py
  tests/rbd/test_rbd_persistent_write_back_cache.py
  tests/rbd/test_rbd_persistent_writeback_cache_flush.py
  tests/rbd/test_rbd_persistent_writeback_cache_invalidate.py
Labels: lgtm, approved

#3213 Integrating the rgw-restore-index tool test
  suites/reef/rgw/tier-2_rgw_ms_archive_with_haproxy.yaml
Labels: RGW, lgtm, Tier-3, close-loop-automation

#3192 Persistent write back cache test with cluster operations
  ceph/rbd/workflows/cluster_operations.py
  suites/quincy/rbd/tier-3_rbd_persistent_write_back_cache.yaml
  suites/reef/rbd/tier-3_rbd_persistent_write_back_cache.yaml
  tests/rbd/rbd_peristent_writeback_cache.py
  tests/rbd/test_rbd_persistent_writeback_cache_flush.py
  tests/rbd/test_rbd_pwl_cache_cluster_operation.py
  utility/utils.py
Labels: RBD, lgtm, approved

#3215 TFA Fix- Moving the Blue store pinned tests to the baremetal
  suites/pacific/rados/tier-2_rados_test_bluestore.yaml
  suites/quincy/rados/mero_4_node_rados_db_wal_conf.yaml
  suites/quincy/rados/tier-2_rados_test_bluestore.yaml
  suites/reef/rados/mero_4_node_rados_db_wal_conf.yaml
  suites/reef/rados/tier-2_rados_test_bluestore.yaml
Labels: RADOS, lgtm, Ready-for-review, tfa-issue-fix

#3208 Adding FS TC 83574100
  suites/pacific/cephfs/tier-2_cephfs_mirror_ha.yaml
  suites/reef/cephfs/tier-1_cephfs_mirror.yaml
  suites/reef/cephfs/tier-2_cephfs_mirror_ha.yaml
  tests/cephfs/cephfs_mirroring/cephfs_mirroring_utils.py
  tests/cephfs/cephfs_mirroring/test_cephfs_mirror_disconnect.py
  tests/cephfs/cephfs_mirroring/test_cephfs_mirror_ha_conversion.py
  tests/cephfs/cephfs_mirroring/test_cephfs_mirror_ha_disconnect.py
  tests/cephfs/cephfs_mirroring/test_cephfs_mirroring_configure_cephfs_mirroring_ha.py
  tests/cephfs/cephfs_mirroring/test_cephfs_mirroring_configure_cephfs_mirroring_ha_using_spec.py
  tests/cephfs/cephfs_utilsV1.py
Labels: Ceph-FS, lgtm, Tier-2, Polarion testcase

#3227 [tfa-fix] Add fix for replace OSD test case failure
  tests/cephadm/test_replace_osd.py
Labels: lgtm, DMFG, tfa-issue-fix

#3233 [RHCS7][Repo]Updating tool repo
  tests/cephadm/test_client.py
Labels: lgtm

#3230 [SuiteFix] Fix tier-0-cephadm suite
  suites/pacific/cephadm/tier-0_cephadm.yaml
  suites/quincy/cephadm/tier0-cephadm.yaml
  suites/reef/cephadm/tier0-cephadm.yaml
Labels: lgtm

#3226 Object lock with no overwrite , tracks BZ BZ 1890843
  suites/quincy/rgw/tier-2_rgw_regression.yaml
  suites/reef/rgw/tier-2_rgw_regression_extended.yaml
Labels: RGW, lgtm

#3232 [SuiteFix] Fix tier-0-nfs-ganesha suite
  suites/reef/nfs/tier0-nfs-ganesha.yaml
Labels: lgtm

#3209 [Test][Cephadm] Add disconnected install
  cephci/prereq.py
  cephci/utils/configure.py
  cli/ops/cephadm.py
  suites/reef/upgrades/tier2-disconnected-upgrade-rhcs-5x-to-7x.yaml
  tests/ceph_installer/test_disconnected_install.py
  tests/ceph_installer/test_disconnected_upgrade.py
Labels: lgtm, CephAdm

#3228 Adding FS TC 83575338
  suites/pacific/cephfs/tier-2_cephfs_mirror_ha.yaml
  suites/reef/cephfs/tier-2_cephfs_mirror_ha.yaml
  tests/cephfs/cephfs_mirroring/test_cephfs_mirroring_configure_cephfs_mirroring_ha_on_4_nodes.py
Labels: lgtm

#3229 Fixing tier-1 Failures
  tests/cephfs/cephfs_mds_pinning/mds_pinning_split_merge.py
  tests/cephfs/cephfs_utilsV1.py
  tests/cephfs/client_authorize.py
  tests/cephfs/no_recover_session_mount.py
  tests/cephfs/subvolume_authorize.py
Labels: lgtm

#3225 CEPH-83575297: Tier-2 test to deploy cluster and test replica-1 pools
  ceph/rados/crushtool_workflows.py
  conf/quincy/rados/11-node-replica1-cluster.yaml
  conf/reef/rados/11-node-replica1-cluster.yaml
  suites/quincy/rados/tier-2_rados_test-replica1.yaml
  suites/reef/rados/tier-2_rados_test-replica1.yaml
  tests/rados/test_replica1.py
Labels: RADOS, lgtm, Tier-2, Polarion testcase, Ready-for-review

#3219 Test to cover immutable object cache test with cluster operations
  suites/quincy/rbd/tier-2_rbd_cache_scenarios.yaml
  suites/reef/rbd/tier-2_rbd_cache_scenarios.yaml
  tests/rbd/test_rbd_immutable_cache_cluster_operations.py
Labels: lgtm, approved

#3217 Added modules to test CIDR blocklisting of Clients
  ceph/rados/core_workflows.py
  conf/pacific/rados/6-node-cluster-4-clients.yaml
  conf/pacific/rados/test-confs/pool-configurations.yaml
  conf/quincy/rados/6-node-cluster-4-clients.yaml
  conf/quincy/rados/test-confs/pool-configurations.yaml
  conf/reef/rados/6-node-cluster-4-clients.yaml
  conf/reef/rados/test-confs/pool-configurations.yaml
  suites/pacific/rados/tier-3_rados_cidr_blocklisting.yaml
  suites/quincy/rados/tier-3_rados_cidr_blocklisting.yaml
  suites/reef/rados/tier-3_rados_cidr_blocklisting.yaml
  tests/rados/test_cidr_blocklisting.py
Labels: RADOS, lgtm, Tier-3, Polarion testcase

#3221 Adding test for scaled snap mirroring with upgrade
  ceph/rbd/initial_config.py
  ceph/rbd/workflows/execute.py
  ceph/rbd/workflows/krbd_io_handler.py
  ceph/rbd/workflows/pool.py
  ceph/rbd/workflows/rbd.py
  ceph/rbd/workflows/rbd_mirror.py
  ceph/rbd/workflows/snap_scheduling.py
  suites/pacific/rbd/tier-3_rbd_mirror_upgrade_scale.yaml
  suites/quincy/rbd/tier-3_rbd_mirror_upgrade_scale.yaml
  suites/reef/rbd/tier-3_rbd_mirror_upgrade_5xto7x_scale.yaml
  suites/reef/rbd/tier-3_rbd_mirror_upgrade_6xto7x_scale.yaml
  tests/rbd_mirror/test_rbd_snapshot_mirroring_with_upgrade.py
Labels: lgtm

#3231 Add new snapshot schedule and retention workflow for rentention count with n and multifs
  suites/quincy/cephfs/tier-2_cephfs_test-snapshot-clone.yaml
  suites/quincy/cephfs/tier-3_cephfs_scale.yaml
  tests/cephfs/snapshot_clone/snap_schedule_retention_vol_subvol.py
Labels: lgtm

#3236 CEPH-83572916 - Verification of the preempt messages in the OSD logs
  suites/reef/rados/tier-2_rados_test_omap.yaml
  tests/rados/test_rados_preempt_scrub.py
Labels: RADOS, lgtm, Tier-2, Polarion testcase, Ready-for-review

#3238 Adding ceph-common installation
  tests/cephfs/cephfs_mirroring/test_cephfs_mirror_ha_disconnect.py
  tests/cephfs/cephfs_mirroring/test_cephfs_mirroring_configure_cephfs_mirroring_ha_on_4_nodes.py
  tests/cephfs/cephfs_recovery/fs_scrub.py
  tests/cephfs/cephfs_scale/max_snapshots.py
  tests/cephfs/cephfs_utilsV1.py
  tests/cephfs/clients/client_mds_restriction.py
  tests/cephfs/clients/mds_journal_value_conf_verification.py
  tests/cephfs/clients/mds_scrub_after_failover.py
Labels: lgtm

#3235 [CEPH-83575868][close loop][automation]: BZ-2153834, bucket granular sync policy
  suites/quincy/rgw/tier-1_rgw_multisite.yaml
  suites/reef/rgw/tier-2_rgw_multisite_regression_extended.yaml
Labels: pr-verified, RGW, lgtm, Tier-2, close-loop-automation

#3240 Adding test to perform cluster operations with snapshot mirroring
  ceph/rbd/workflows/rbd_mirror.py
  ceph/rbd/workflows/snap_scheduling.py
  suites/pacific/rbd/tier-3_cluster_operations_with_snap_mirroring.yaml
  suites/quincy/rbd/tier-3_cluster_operations_with_snap_mirroring.yaml
  suites/reef/rbd/tier-3_cluster_operations_with_snap_mirroring.yaml
  tests/rbd_mirror/test_rbd_snap_mirroring_with_cluster_op.py
  tests/rbd_mirror/test_rbd_snapshot_mirroring_with_upgrade.py
Labels: lgtm

#3243 [TFA][DMFG][Upgrade]Cephadm upgrade without rgw
  suites/quincy/upgrades/tier1-upgrade-cephadm-without-rgw.yaml
Labels: lgtm, DMFG, tfa-issue-fix

#3239 [TFA][DMFG][Cephadm][Tier2]Multiple Subnet
  conf/quincy/cephadm/tier-2_rhos01_multiple_subnet_openstack_only.yaml
  conf/quincy/cephadm/tier-2_rhosd_multiple_subnet_openstack_only.yaml
  conf/reef/cephadm/rhos01-1admin-5node-multiple-subnet.yaml
  conf/reef/cephadm/rhosd-1admin-5node-multiple-subnet.yaml
  suites/quincy/cephadm/tier-2_rhos01_multiple_subnet_openstack_only.yaml
  suites/quincy/cephadm/tier-2_rhosd_multiple_subnet_openstack_only.yaml
  suites/reef/cephadm/tier-2_rhos01_multiple_subnet_openstack_only.yaml
  suites/reef/cephadm/tier-2_rhosd_multiple_subnet_openstack_only.yaml
Labels: lgtm, DMFG, tfa-issue-fix

#3244 Including s3cmd multipart get as part of regression and upgrade suite
  suites/pacific/rgw/tier-1_rgw.yaml
  suites/pacific/rgw/tier-1_rgw_ms-omap-datalog-on-primary.yaml
  suites/pacific/rgw/tier-1_rgw_test-upgrade-4-to-latest.yaml
  suites/pacific/rgw/tier-1_rgw_test_upgrade-5-to-latest.yaml
  suites/quincy/rgw/tier-1_rgw_multisite.yaml
  suites/quincy/rgw/tier-1_rgw_upgrade_5-3_to_6x_latest.yaml
  suites/quincy/rgw/tier-1_rgw_upgrade_6-0GA_to_6x_latest.yaml
  suites/quincy/rgw/tier-2_rgw_regression_extended.yaml
  suites/reef/rgw/tier-1_rgw_upgrade_5_3GA_to_7x_latest.yaml
  suites/reef/rgw/tier-1_rgw_upgrade_6_1GA_to_7x_latest.yaml
  suites/reef/rgw/tier-2_rgw_3_way_multisite.yaml
  suites/reef/rgw/tier-2_rgw_regression_extended.yaml
Labels: RGW, lgtm, PipelineV3.0, tfa-issue-fix

#3246 [TFA]Fix for sync issue in tier-1_rgw_ms_upgrade_6_1GA_to_7x_latest
  suites/reef/rgw/tier-1_rgw_ms_upgrade_6_1GA_to_7x_latest.yaml
Labels: pr-verified, RGW, lgtm, tfa-issue-fix

#3223 CEPH-83574487- Verification of Async recovery performance with fault
  suites/pacific/rados/tier-3_rados-recovery_tests.yaml
  suites/quincy/rados/tier-3_rados-recovery_tests.yaml
  suites/reef/rados/tier-3_rados-recovery_tests.yaml
  tests/rados/test_osd_async_recovery.py
Labels: RADOS, lgtm, Tier-3

#3248 Add -ve test workflow for snap schedule suite
  suites/reef/cephfs/tier-4_cephfs_recovery.yaml
  tests/cephfs/snapshot_clone/snap_schedule_retention_vol_subvol.py
Labels: lgtm

#3251 [TFA] radosgw-admin bucket stats failure in listng tc
  suites/reef/rgw/tier-2_ssl_rgw_ms_ecpool_test.yaml
Labels: RGW, lgtm, tfa-issue-fix

#3234 Configuring multiple zones without replication
  suites/reef/rgw/tier-2_rgw_multisite_scenarios.yaml
  tests/rgw/sanity_rgw_multisite.py
Labels: pr-verified, RGW, lgtm

#3241 Remove client label from gateway node
  conf/reef/nvmeof/ceph_nvmeof_sanity.yaml
Labels: lgtm, nvmeof

#3245 Adding privatekey argument so that we can utilise the ssh key
  ceph/ceph.py
Labels: lgtm

#3247 Code changes w.r.t new nvmeof CLIS
  ceph/nvmeof/nvmeof_gwcli.py
Labels: lgtm, nvmeof

#3257 Fixing private key argument
  ceph/ceph.py
Labels: lgtm

#3249 Adding test for snap and clone operations with snapshot mirroring
  ceph/rbd/initial_config.py
  ceph/rbd/utils.py
  ceph/rbd/workflows/snap_clone_operations.py
  ceph/rbd/workflows/snap_scheduling.py
  suites/pacific/rbd/tier-3_snap_mirroring_regression.yaml
  suites/quincy/rbd/tier-3_snap_mirroring_regression.yaml
  suites/reef/rbd/tier-3_snap_mirroring_regression.yaml
  tests/rbd_mirror/test_rbd_snap_mirroring_with_cluster_op.py
  tests/rbd_mirror/test_rbd_snap_mirroring_with_snap_clone_op.py
Labels: lgtm

#3260 [TFA fix]: fixing jq installation failure in archive haproxy suite
  suites/reef/rgw/tier-2_rgw_ms_archive_with_haproxy.yaml
Labels: RGW, lgtm, tfa-issue-fix

#3259 [TFA Fix] yes prompt missed while installing rbd-nbd package
  suites/reef/rbd/tier-2_rbd_cache_scenarios.yaml
  suites/reef/rbd/tier-2_rbd_encryption.yaml
  suites/reef/rbd/tier-3_rbd_persistent_write_back_cache.yaml
Labels: lgtm, approved

#3261 [TestFix] Fix tier2-verify-custom-container suite
  cephci/utils/configure.py
Labels: lgtm

#3264 RBD TFA fixes
  suites/quincy/rbd/tier-2_rbd_cache_scenarios.yaml
  suites/reef/rbd/tier-2_rbd_cache_scenarios.yaml
  tests/rbd/test_rbd_immutable_cache_cluster_operations.py
  tests/rbd/test_rbd_python_module.py
Labels: lgtm, approved

#3265 Few corrections to preview PR 3249
  ceph/rbd/utils.py
  tests/rbd_mirror/test_rbd_snap_mirroring_with_snap_clone_op.py
Labels: lgtm, approved

#3269 RBD TFA Fixes
  suites/pacific/rbd/tier-4_rbd_negative_scenario_regression.yaml
  suites/quincy/rbd/tier-4_rbd_negative_scenario_regression.yaml
  tests/rbd/rbd_ecpool_test_image.py
Labels: lgtm, approved

#3250 CEPH-83581346: Test to verify prometheus metric metadata post upgrade
  api/__init__.py
  ceph/rados/core_workflows.py
  conf/pacific/rados/7-node-cluster.yaml
  conf/quincy/rados/7-node-cluster.yaml
  conf/reef/rados/7-node-cluster.yaml
  suites/quincy/rados/tier-2_rados_test-brownfield.yaml
  suites/reef/rados/tier-2_rados_test-brownfield.yaml
  tests/rados/test_brownfield.py
Labels: RADOS, lgtm, Tier-2, Ready-for-review
