Repository red-hat-storage/cephci, pull requests merged in 2024-07, with the labels that each got.

#3795 Adding FS TC_83591419
  suites/quincy/cephfs/tier-2_cephfs_test-clients.yaml
  suites/reef/cephfs/tier-2_cephfs_test-clients.yaml
  suites/squid/cephfs/tier-2_cephfs_test-clients.yaml
  tests/cephfs/cephfs_utilsV1.py
  tests/cephfs/clients/validate_root_squash.py
Labels: lgtm

#3831 Rados TFA fixes - Updated test for pool behaviour at min_size
  ceph/rados/core_workflows.py
  ceph/rados/pool_workflows.py
  suites/squid/rados/tier-3_rados_test-location-stretch-mode.yaml
  tests/rados/pool_tests.py
  tests/rados/test_stretch_netsplit_scenarios.py
  tests/rados/test_upgrade_warn.py
Labels: RADOS, lgtm, tfa-issue-fix

#3825 [Test] Validate multiple ingress service on same host
  suites/reef/cephadm/tier-2-multiple-ingress-service.yaml
Labels: lgtm

#3837 Added pool cleanup for RBD and RBD mirror related tests
  tests/rbd/rbd_faster_exports.py
  tests/rbd_mirror/test_11489.py
  tests/rbd_mirror/test_9470.py
  tests/rbd_mirror/test_9471.py
  tests/rbd_mirror/test_9474.py
  tests/rbd_mirror/test_9475.py
  tests/rbd_mirror/test_expand_or_shrink_img_at_secondary.py
  tests/rbd_mirror/test_rbd_clone_mirror.py
  tests/rbd_mirror/test_rbd_mirror.py
  tests/rbd_mirror/test_rbd_mirror_image.py
  tests/rbd_mirror/test_rbd_mirror_rename_image.py
  tests/rbd_mirror/test_rbd_mirror_snapshot.py
Labels: lgtm, approved

#3822 [T3-automation]: CEPH-83575382 Scale on 2 zone mirror config verify sync
  suites/reef/baremetal/deploy/rh/extensa_clara_multisite_1admin_4node_1client.yaml
  suites/reef/rgw/baremetal/scale_rgw_multi_site.yaml
Labels: pr-verified, RGW, lgtm, Tier-3, tfa-issue-fix, baremetal

#3841 [NFS-Ganesha][Feature Automation] Add the extended attributes additio…
  suites/squid/nfs/tier0-nfs-ganesha-vers-4-2.yaml
  tests/nfs/nfs_operations.py
  tests/nfs/nfs_set_retrieve_xattr_multi_client.py
  tests/nfs/nfs_test_xattr_across_file_operations
  tests/nfs/nfs_verify_xattr_readonly_file.py
Labels: lgtm

#3848 [Cephadm][Tier-4] Add test to validate crash reported
  suites/pacific/cephadm/tier-4-service-operations.yaml
  suites/quincy/cephadm/tier-4-service-operations.yaml
  suites/reef/cephadm/tier4-service-operations.yaml
  tests/cephadm/test_verify_crash_daemon_report_crashes.py
Labels: lgtm

#3850 Automate CEPH-83581754
  ceph/nvmegw_cli/namespace.py
  suites/reef/nvmeof/tier-2_nvmeof_functional_Regression.yaml
  tests/nvmeof/test_ceph_nvmeof_gateway.py
Labels: lgtm

#3853 [TFA] Fix keyring file not present error
  suites/pacific/cephadm/tier-1_cephadm_operations_via_admin_node.yaml
  tests/cephadm/test_cephadm_operations_via_admin.py
Labels: lgtm

#3808 [TFA] Fix the ModuleNotFoundError
  cephci/utils/configure.py
  cli/utilities/containers.py
Labels: lgtm

#3810 Evict all the clients and verify it added to blocklist
  suites/squid/cephfs/tier-3_cephfs_bugs.yaml
  tests/cephfs/cephfs_bugs/evict_all_clients_add_to_blocklist.py
Labels: Ceph-FS, lgtm

#3832 prevent scrub with standby mds
  tests/cephfs/cephfs_bugs/prevent_scrub_with_standby_mds.py
Labels: lgtm

#3847 Fixing client failures in BM config
  tests/cephfs/cephfs_bugs/test_client_blocklist_large_session_metadata.py
  tests/cephfs/clients/client_fstab_auto_mount.py
  tests/cephfs/clients/mds_conf_modifying.py
  tests/cephfs/clients/multiclient_file_dir_ops.py
Labels: lgtm

#3849 [Cephadm] Verify logrotate takes into account tcmu-runner
  suites/pacific/cephadm/tier-4-service-operations.yaml
  suites/quincy/cephadm/tier-4-service-operations.yaml
  suites/reef/cephadm/tier4-service-operations.yaml
  tests/cephadm/test_verify_log_rotate_tcmu_runner.py
Labels: lgtm

#3814 [Test][Ceph-Volume] Add test to validate ceph inventory list format o…
  cli/utilities/containers.py
  suites/pacific/ceph_volume/tier-2-ceph-volume.yaml
  suites/quincy/ceph_volume/tier-2-ceph-volume.yaml
  suites/reef/ceph_volume/tier-2-ceph-volume.yaml
  suites/squid/ceph_volume/tier2-ceph-volume.yaml
  tests/ceph_volume/test_ceph_volume_get_inventory_list.py
Labels: lgtm

#3829 Integrate the list bucket marker test to cephCI
  suites/reef/rgw/tier-2_rgw_regression_extended.yaml
  suites/squid/rgw/tier-2_rgw_regression_extended.yaml
Labels: RGW, lgtm

#3839 Automate CEPH-83581755
  suites/reef/nvmeof/tier-4_nvmeof_neg_tests.yaml
  suites/squid/nvmeof/tier-4_nvmeof_neg_tests.yaml
  tests/nvmeof/test_ceph_nvmeof_neg_tests.py
Labels: lgtm

#3846 TFA fixes for cg quiesce functional suite
  conf/reef/cephfs/tier-1_fs.yaml
  conf/squid/cephfs/tier-1_fs.yaml
  suites/reef/cephfs/tier-1_cephfs_cg_quiesce.yaml
  suites/squid/cephfs/tier-1_cephfs_cg_quiesce.yaml
  tests/cephfs/snapshot_clone/cephfs_cg_io.py
  tests/cephfs/snapshot_clone/cg_snap_test.py
Labels: lgtm

#3854 [Fix] Correct typo extry point module
  suites/quincy/cephadm/tier1_node_exporter_operation.yaml
  suites/reef/cephadm/tier1_node_exporter_operation.yaml
  suites/squid/cephadm/tier1_node_exporter_operation.yaml
Labels: lgtm

#3827 Automation of the Bug#2249003 verification that the crashes on a non omap pool
  suites/pacific/rados/tier-2_rados_test_omap.yaml
  suites/quincy/rados/tier-2_rados_test_omap.yaml
  suites/reef/rados/tier-2_rados_test_omap.yaml
  tests/rados/test_omap_entries.py
Labels: RADOS, lgtm, Polarion testcase

#3858 Adding ceph log collection for failed test suites
  cephci/cluster_info.py
  run.py
Labels: lgtm

#3861 TFA fix for cg_snap_interop_workflow_2
  tests/cephfs/snapshot_clone/cg_snap_test.py
Labels: lgtm

#3863 [Testfix] Correct the IP used as Virtual IP
  suites/reef/cephadm/tier-2-rhos01-multiple-ingress-service.yaml
Labels: lgtm

#3859 Fixing TFA Issues cephfs
  tests/cephfs/cephfs_nfs/nfs_info_cluster_id_and_ls_export_detailed.py
  tests/cephfs/cephfs_utilsV1.py
  tests/cephfs/multifs/multifs_default_values.py
  tests/cephfs/snapshot_clone/clone_threads.py
Labels: lgtm

#3851 adding support for testing sse_kms kmip with GKLM
  suites/reef/rgw/sanity_rgw_multisite.yaml
  suites/squid/rgw/sanity_rgw_multisite.yaml
Labels: pr-verified, RGW, lgtm, Tier-2

#3862 [Automation][cephadm]Verify cephadm call
  cli/utilities/cephadm-call.py
  suites/quincy/cephadm/tier-1_skip_dashboard.yaml
  tests/cephadm/test_cephadm_call.py
Labels: lgtm, CephAdm, DMFG

#3870 [LibFix] Add cluster info and ceph logs to results page
  run.py
  templates/result-email-template.html
  utility/utils.py
Labels: framework, lgtm

#3845 Re-enable d3n testcases in baremetal
  suites/reef/rgw/sanity_rgw.yaml
  suites/squid/rgw/sanity_rgw.yaml
Labels: RGW, lgtm, tfa-issue-fix

#3873 [Conf] Add RHEL 9.5 nightly build inventory
  conf/inventory/rhel-9.5-nightly-x86_64-large.yaml
  conf/inventory/rhel-9.5-nightly-x86_64-xlarge.yaml
  conf/inventory/rhel-9.5-nightly-x86_64.yaml
Labels: framework, lgtm

#3865 [NFS-Ganesha]Fix windows client Test failures
  suites/reef/nfs/tier1-nfs-ganesha-windows-clients.yaml
  tests/nfs/nfs_export_rootsquash_windows.py
  tests/nfs/nfs_multivolume_rootsquash.py
Labels: lgtm

#3871 [TFA-issue-fix] Deployment failure issue with migrate default ss to ms
  conf/reef/rgw/migrate_default_single_to_multisite.yaml
  conf/squid/rgw/migrate_default_single_to_multisite.yaml
  suites/reef/rgw/migrate_default_single_to_multisite.yaml
  suites/squid/rgw/migrate_default_single_to_multisite.yaml
Labels: pr-verified, RGW, lgtm, tfa-issue-fix

#3869 [TFA-issue-Fix] deploy multisite with rgw ssl upgrade suite failure fix
  suites/reef/rgw/tier-1_rgw_ssl_multisite_test_upgrade_71GA_to_71x_latest.yaml
  suites/squid/rgw/tier-1_rgw_ssl_multisite_test_upgrade_71GA_to_8x_latest.yaml
Labels: pr-verified, RGW, Upgrade, lgtm, tfa-issue-fix

#3875 Fix Build issue at Readthedocs
  .readthedocs.yaml
  tests/nvmeof/test_ceph_nvmeof_gateway_sub_scale.py
Labels: bug in framework, lgtm, nvmeof

#3879 os and tools required attributes under build sections.
  .readthedocs.yaml
Labels: bug in framework, framework, lgtm

#3876 NVMeoF b2b upgrade test suite
  ceph/ceph_admin/__init__.py
  ceph/ceph_admin/bootstrap.py
  ceph/ceph_admin/registry_login.py
  ceph/nvmegw_cli/__init__.py
  ceph/nvmegw_cli/execute.py
  suites/reef/nvmeof/tier-2_nvmeof_b2b_upgrade.yaml
  tests/nvmeof/test_ceph_nvmeof_upgrade.py
Labels: Upgrade, lgtm, nvmeof

#3874 7.1 TFA fixes for snap-schedule and quiesce suite
  suites/reef/cephfs/tier-1_cephfs_cg_quiesce.yaml
  suites/reef/cephfs/tier-1_cephfs_cg_quiesce_systemic.yaml
  suites/squid/cephfs/tier-1_cephfs_cg_quiesce.yaml
  tests/cephfs/snapshot_clone/cephfs_cg_io.py
  tests/cephfs/snapshot_clone/cg_snap_system_test.py
  tests/cephfs/snapshot_clone/cg_snap_test.py
  tests/cephfs/snapshot_clone/snap_schedule.py
Labels: lgtm

#3882 Additional OpenStack networks for deployment.
  compute/openstack.py
Labels: pr-verified, framework, lgtm, Ready-for-review

#3857 TFA FIX- Scheduled scrub fix
  tests/rados/scheduled_scrub_scenarios.py
Labels: RADOS, lgtm, do-not-merge/work-in-progress

#3884 Remove unsupported python.version attr
  .readthedocs.yaml
  docs/requirements.txt
Labels: bug in framework, framework, lgtm

#3868 pool_test.py: Added test to verify autoscaler behaviour with pg_num_min
  ceph/rados/core_workflows.py
  suites/pacific/rados/tier-2_rados_test-pool-functionalities.yaml
  suites/quincy/rados/tier-2_rados_test-pool-functionalities.yaml
  suites/reef/rados/tier-2_rados_test-pool-functionalities.yaml
  suites/squid/rados/tier-2_rados_test-pool-functionalities.yaml
  tests/rados/pool_tests.py
Labels: RADOS, lgtm, 7.1-bugs-automate

#3885 TFA fix for nfs and recovery suite
  conf/reef/cephfs/tier-2_cephfs_9-node-cluster.yaml
  tests/cephfs/cephfs_nfs/nfs_info_cluster_id_and_ls_export_detailed.py
Labels: lgtm

#3867 Adding XFS test in kernel verification suite
  suites/pacific/cephfs/tier-1_fs_kernel.yaml
  suites/squid/cephfs/tier-3_cephfs_bugs.yaml
  tests/cephfs/xfs_test.py
Labels: lgtm

#3889 [TFA] Fix the playbook failure due to undefined variable
  tests/cephadm/ansible_wrapper/ceph_config/set-ceph-config.yaml
Labels: lgtm

#3894 [Quincy][Upgrade]Update image and repo
  suites/quincy/upgrades/tier-1-upgrade-ibm-5x-to-6x.yaml
Labels: Upgrade, lgtm, DMFG

#3895 Fix long_running method timeout
  ceph/ceph.py
Labels: lgtm

#3891 Fix for Upgrade from 5.3 to 7.x
  ceph/ceph_admin/bootstrap.py
Labels: lgtm, approved

#3898 TFA: regression issue with long_running method
  ceph/ceph.py
Labels: lgtm

#3840 adding configs for sse_s3 also in install_vault and integrating notif_transition, curl multipart upload test cases
  suites/pacific/rgw/tier-2_rgw_test_5-3_specific_fixes.yaml
  suites/reef/rgw/sanity_rgw.yaml
  suites/reef/rgw/tier-2_rgw_test_bucket_notifications.yaml
  suites/squid/rgw/sanity_rgw.yaml
  suites/squid/rgw/tier-2_rgw_test_bucket_notifications.yaml
  tests/misc_env/install_vault.py
Labels: pr-verified, RGW, lgtm, Tier-2, tfa-issue-fix

#3860 Bucket notifications on archive zone with ObjectSync:Create/Delete events
  suites/reef/rgw/tier-2_rgw_ms-archive.yaml
  suites/squid/rgw/tier-2_rgw_ms-archive.yaml
  tests/rgw/sanity_rgw_multisite.py
Labels: RGW, lgtm, Tier-4, tfa-issue-fix

#3899 Comment curl testcase from ssl suite until support is provided from c…
  suites/reef/rgw/tier-1_rgw_upgrade_ssl_71GA_to_71x_latest.yaml
  suites/squid/rgw/tier-1_rgw_upgrade_ssl_71GA_to_8x_latest.yaml
Labels: RGW, lgtm, tfa-issue-fix

#3866 integrating mod multipart hotfix test into cephci
  suites/pacific/rgw/tier-2_rgw_test-using-s3cmd.yaml
  suites/quincy/rgw/tier-2_rgw_test-using-s3cmd.yaml
  suites/reef/rgw/tier-2_rgw_test_using_s3cmd.yaml
  suites/squid/rgw/tier-2_rgw_test_using_s3cmd.yaml
Labels: pr-verified, RGW, lgtm, Tier-2, hotfix

#3843 Adding CBT support
  cli/io/cbt/__init__.py
  cli/io/cbt/cbt.py
  cli/io/cbt/conf.yaml
  cli/io/cbt/setup_cbt.sh
  tests/cephfs/cephfs_cbt.py
Labels: lgtm, approved

#3901 [TFA]: Fix issue seen with mulipart upload failure with sse-s3
  suites/quincy/rgw/tier-2_rgw_ms_test-bucket-notifications.yaml
Labels: pr-verified, RGW, lgtm, tfa-issue-fix

#3855 [Test] Add test to validate custom config
  suites/quincy/cephadm/tier-2-bootstrap-along-with-spec-file.yaml
  suites/quincy/cephadm/tier-4-service-operations.yaml
  suites/reef/cephadm/tier4-service-operations.yaml
  suites/squid/cephadm/tier4-service-operations.yaml
  tests/cephadm/test_cephadm_custom_config_support.py
Labels: lgtm

#3900 Further Improvements to long_running method
  ceph/ceph.py
Labels: bug in framework, lgtm, Ready-for-review

#3912 [Squid][SMB][Automation]Deploy samba with 500 shares using declarative
  suites/squid/smb/tier-1-smb-500-shares-declarative.yaml
  tests/smb/smb_deployment_multi_shares_declarative_method.py
Labels: lgtm, DMFG, smb

#3902 Fixed TC mismatch b/w reef and quincy suites
  suites/quincy/cephfs/tier-3_cephfs_bugs.yaml
  suites/quincy/cephfs/tier-3_cephfs_bugs_baremetal.yaml
  suites/reef/cephfs/tier-3_cephfs_bugs.yaml
Labels: Ceph-FS, lgtm

#3920 long_running fix unbound variable exception
  ceph/ceph.py
Labels: lgtm

#3924 [Squid][Automation][SMB]Load test
  suites/squid/smb/tier-2-smb-load.yaml
  tests/smb/smb_load.py
  tests/smb/smb_multi_connection.py
  tests/smb/smb_operations.py
Labels: lgtm, DMFG, smb

#3904 Fixing recreating of user in upgrade suite
  suites/reef/cephfs/tier-0_cephfs_upgrade_70_to_71.yaml
  tests/cephfs/cephfs_upgrade/cephfs_io.py
  tests/cephfs/cephfs_upgrade/cephfs_mds_failover.py
  tests/cephfs/cephfs_upgrade/cephfs_post_upgrade_validation.py
  tests/cephfs/cephfs_upgrade/metadata_version_validation.py
  tests/cephfs/cephfs_upgrade/upgrade_pre_req.py
  tests/cephfs/cephfs_utilsV1.py
Labels: lgtm

#3887 Addition of a new generic test suite for RADOS with all the features
  ceph/rados/pool_workflows.py
  suites/pacific/rados/tier-2-rados-basic-regression.yaml
  suites/pacific/rados/tier-2_rados_test-bugfixes.yaml
  suites/quincy/rados/tier-2-rados-basic-regression.yaml
  suites/quincy/rados/tier-2_rados_test-bugfixes.yaml
  suites/reef/rados/test_rados_all_generic_features.yaml
  suites/reef/rados/tier-2-rados-basic-regression.yaml
  suites/reef/rados/tier-2_rados_test-bugfixes.yaml
  suites/squid/rados/tier-2-rados-basic-regression.yaml
  suites/squid/rados/tier-2_rados_test-bugfixes.yaml
  tests/rados/pool_tests.py
  tests/rados/test_omap_entries.py
  tests/rados/test_osd_ecpool_inconsistency_scenario.py
  tests/rados/test_pg_autoscale_flag.py
Labels: RADOS, lgtm

#3915 [NFS-Ganesha]Test allocating space for files of different sizes
  suites/squid/nfs/tier0-nfs-ganesha-vers-4-2.yaml
  tests/nfs/nfs_test_allocation_beyond_size.py
  tests/nfs/nfs_test_space_allocation_diff_sizes.py
  tests/nfs/nfs_test_xattr_across_file_operations.py
Labels: lgtm

#3925 TFA Fix for the-Inconsistent Object not generated on the cluster.
  tests/rados/test_inconsistency_osd_epoch.py
  tests/rados/test_osd_inconsistency_pg.py
Labels: RADOS, lgtm, tfa-issue-fix

#3916 [TFA] Since in primary default realm is india, but in secondary its RealmOne, verify Io failed
  suites/reef/rgw/tier-1_rgw_ms_upgrade_multirealm_61GA_to_7x_latest.yaml
  suites/squid/rgw/tier-1_rgw_ms_upgrade_multirealm_71GA_to_8x_latest.yaml
Labels: pr-verified, RGW, lgtm, tfa-issue-fix

#3907 Re-enable curl testcases for ssl suite
  suites/reef/rgw/tier-1_rgw_upgrade_ssl_71GA_to_71x_latest.yaml
  suites/squid/rgw/tier-1_rgw_upgrade_ssl_71GA_to_8x_latest.yaml
Labels: enhancement, RGW, lgtm, tfa-issue-fix

#3926 cephci integration of CEPH-83574876 - Verify 'bi put` uses right buck…
  suites/quincy/rgw/tier-1-extn_rgw.yaml
  suites/reef/rgw/tier-2_rgw_regression_extended.yaml
  suites/squid/rgw/tier-2_rgw_regression_extended.yaml
Labels: pr-verified, RGW, lgtm, Tier-3

#3922 [Rados] Changing wait_for_device method across the board
  tests/rados/test_cephdf.py
  tests/rados/test_four_node_ecpool.py
  tests/rados/test_osd_rebalance_snap.py
  tests/rados/test_pg_split.py
  tests/rados/test_pool_osd_recovery.py
  tests/rados/test_stretch_osd_serviceability_scenarios.py
Labels: RADOS, lgtm, tfa-issue-fix

#3893 Verification of the scrub&deep-scrub feature with the osd_scrub_auto_repair_num_errors
  suites/pacific/rados/tier-2_rados_test-bugfixes.yaml
  suites/quincy/rados/tier-2_rados_test-bugfixes.yaml
  suites/reef/rados/tier-2_rados_test-bugfixes.yaml
  tests/rados/test_norecovery_flag_functionality.py
  tests/rados/test_osd_ecpool_inconsistency_scenario.py
  tests/rados/test_osd_replicated_inconsistency_scenario.py
Labels: RADOS, lgtm, Polarion testcase

#3934 setuptools 72.0.0 has caused a disruption to gate checks.
  .github/workflows/tests.yml
  tox.ini
Labels: lgtm, approved

#3935 Move mergify to check on 3.9.18
  .github/mergify.yml
Labels: lgtm, approved

#3911 Add 7.1z1 BZ 2290711 workflow
  suites/reef/cephfs/tier-3_cephfs_bugs.yaml
  suites/squid/cephfs/tier-3_cephfs_bugs.yaml
  tests/cephfs/cephfs_bugs/clone_no_wait_if_max_concurrent.py
Labels: Ceph-FS, lgtm, Polarion testcase

#3938 [NFS-Ganesha] Test cmount_path is included in volume export file
  suites/reef/nfs/tier0-nfs-ganesha-v3.yaml
  suites/reef/nfs/tier0-nfs-ganesha.yaml
  suites/squid/nfs/tier0-nfs-ganesha-v3.yaml
  suites/squid/nfs/tier0-nfs-ganesha-vers-4-2.yaml
  suites/squid/nfs/tier0-nfs-ganesha.yaml
  tests/nfs/nfs_validate_cmount_path_export_conf.py
Labels: lgtm

#3927 [Test][NfsGanesha] Add test to validate nfs export access_type as NONE
  suites/reef/nfs/nfs-vers-4_2/tier0-nfs-ganesha-vers-4-2.yaml
  suites/reef/nfs/tier0-nfs-ganesha-v3.yaml
  suites/reef/nfs/tier0-nfs-ganesha.yaml
  tests/nfs/nfs_edit_export_config_with_access_none.py
Labels: lgtm, nfs-ganesha

#3936 TFA fix for squid version
  tests/cephfs/cephfs_utils.py
Labels: lgtm

#3931 client metrics TFA
  suites/reef/cephfs/tier-2_cephfs_test-metrics.yaml
  tests/cephfs/cephfs_metrics/cephfs_metrics_functional.py
  tests/cephfs/cephfs_metrics/cephfs_metrics_scale.py
Labels: Ceph-FS, lgtm, Polarion testcase

#3941 [Cephadm] Add test to validate key rotate
  cli/ceph/orch/daemon.py
  suites/quincy/cephadm/tier-4-service-operations.yaml
  suites/reef/cephadm/tier4-service-operations.yaml
  suites/squid/cephadm/tier4-service-operations.yaml
  tests/cephadm/test_validate_key_rotate.py
Labels: lgtm

#3945 TFA fixes for Regression runs
  conf/quincy/cephfs/tier-2_cephfs_9-node-cluster.yaml
  conf/squid/cephfs/tier-2_cephfs_9-node-cluster.yaml
  tests/cephfs/cephfs_generic/test_data_migrate_bw_buckets.py
  tests/cephfs/cephfs_mirroring/test_cephfs_mirroring_snap_status_using_asok.py
  tests/cephfs/cephfs_nfs/nfs_info_cluster_id_and_ls_export_detailed.py
  tests/cephfs/cephfs_utilsV1.py
  tests/cephfs/multifs/multifs_default_values.py
  tests/cephfs/snapshot_clone/snap_schedule.py
Labels: lgtm
