Repository red-hat-storage/cephci, pull requests merged in 2024-04, with the labels that each got.

#3572 [tfa-fix] Add support for s3.upshift repo for RC builds
  cli/ops/cephadm_ansible.py
Labels: lgtm, DMFG, tfa-issue-fix

#3578 Fixing Version comparison using looseversion
  tests/misc_env/validate_version.py
Labels: lgtm

#3574 [Baremetal] Adding suite for execution
  suites/reef/baremetal/deploy/rh/extensa_clara_multisite_1admin_4node_1client.yaml
  suites/reef/rgw/baremetal/scale_rgw_multi_site.yaml
  suites/reef/rgw/baremetal/scale_rgw_single_site.yaml
Labels: RGW, lgtm, baremetal

#3580 Fixing multisite node ip
  conf/baremetal/extensa_clara_multisite_1admin_4node_1client.yaml
Labels: lgtm

#3560 CephFS Customer Case BZ Automation
  suites/pacific/cephfs/tier-3_cephfs_bugs_baremetal.yaml
  suites/quincy/cephfs/tier-3_cephfs_bugs_baremetal.yaml
  suites/reef/cephfs/tier-3_cephfs_bugs_baremetal.yaml
  tests/cephfs/cephfs_bugs/test_mds_oversized_cache.py
  tests/cephfs/cephfs_utilsV1.py
Labels: Ceph-FS, lgtm, close-loop-automation

#3582 [TFA Fix] Include restart after zone modify in master
  suites/reef/baremetal/deploy/rh/extensa_clara_multisite_1admin_4node_1client.yaml
Labels: pr-verified, RGW, lgtm, tfa-issue-fix, baremetal

#3551 [Nfs Ganesha] Add multi client scenarios
  suites/reef/nfs/tier1-nfs-ganesha-ha-windows.yaml
  suites/reef/nfs/tier1-nfs-ganesha-windows-clients.yaml
  tests/nfs/nfs_verify_multi_client_failover_windows.py
  tests/nfs/nfs_verify_multi_client_reboot_with_io.py
Labels: lgtm

#3585 nvmeof CLI changes as per HA for scale tests
  suites/reef/nvmeof/tier-3_2-nvmeof-gw_1-sub_ns.yaml
  suites/reef/nvmeof/tier-3_2-nvmeof-gw_16-sub_ns.yaml
  suites/reef/nvmeof/tier-3_2-nvmeof-gw_2-sub_ns.yaml
  suites/reef/nvmeof/tier-3_2-nvmeof-gw_4-sub_ns.yaml
  suites/reef/nvmeof/tier-3_2-nvmeof-gw_8-sub_ns.yaml
  suites/reef/nvmeof/tier-3_4-nvmeof-gw_1-sub_ns.yaml
  suites/reef/nvmeof/tier-3_4-nvmeof-gw_16-sub_ns.yaml
  suites/reef/nvmeof/tier-3_4-nvmeof-gw_2-sub_ns.yaml
  suites/reef/nvmeof/tier-3_4-nvmeof-gw_4-sub_ns.yaml
  suites/reef/nvmeof/tier-3_4-nvmeof-gw_8-sub_ns.yaml
  tests/nvmeof/test_ceph_nvmeof_gateway_sub_scale.py
Labels: lgtm, nvmeof

#3586 Comment d3n testacse to avoid execution on baremetal
  suites/reef/rgw/sanity_rgw.yaml
Labels: RGW, lgtm, tfa-issue-fix

#3588 Mirroring stat fixing intermittent issue
  tests/cephfs/cephfs_mirroring/validate_file_dir_stats_modification_on_mirrored_cluster.py
Labels: Ceph-FS, lgtm

#3591 [Upgrade][Reef]Add upgrade suite with monitoring stack
  suites/reef/upgrades/tier1-upgrade-with-monitoring-stack-ibm-7x-to-7x.yaml
  suites/reef/upgrades/tier1-upgrade-with-monitoring-stack-rhcs-7x-to-7x.yaml
Labels: Upgrade, lgtm, DMFG

#3594 [Lib] Add support to get node details
  cli/cloudproviders/baremetal.py
Labels: lgtm

#3595 [Conf] Add IBM inventory file
  conf/inventory/ibm-vpc-rhel-9.2-minimal-bx2-4x16.yaml
Labels: lgtm

#3596 [ConfigFix] Update IBM Cloud inventory
  conf/inventory/ibm-vpc-rhel-9.2-minimal-bx2-4x16.yaml
Labels: lgtm

#3598 Include known issue for BZ-2274680
  suites/pacific/rgw/tier-1_rgw_ms-omap-datalog-on-primary.yaml
  suites/reef/rgw/tier-2_rgw_multisite_regression_extended.yaml
Labels: RGW, lgtm, tfa-issue-fix

#3587 Updating the version check for m granularity
  tests/cephfs/snapshot_clone/cephfs_snap_utils.py
  tests/cephfs/snapshot_clone/snap_schedule.py
  tests/cephfs/snapshot_clone/snap_schedule_retention_vol_subvol.py
Labels: lgtm

#3602 [ConfigFix] Fix IBM Cloud inventory config file
  conf/inventory/ibm-vpc-rhel-9.2-minimal-bx2-4x16.yaml
Labels: framework, lgtm

#3601 test_pg_split.py: Fixed the finally method as part of TFA
  tests/rados/test_pg_split.py
Labels: lgtm

#3604 [LibFix] Fix polarion report update to skip template
  cephci/reports.py
Labels: lgtm

#3605 Fix for upgrade test cases not adding right repo to cluster nodes
  ceph/ceph_admin/__init__.py
Labels: lgtm

#3549 REST API framework complained to ceph-ci with a working testcase
  ceph/rbd/workflows/rbd.py
  requirements.txt
  rest/__init__.py
  rest/common/__init__.py
  rest/common/config/__init__.py
  rest/common/config/config.json
  rest/common/config/config.py
  rest/common/utils/__init__.py
  rest/common/utils/exceptions.py
  rest/common/utils/rest.py
  rest/endpoints/__init__.py
  rest/endpoints/ceph.py
  rest/endpoints/rbd/__init__.py
  rest/endpoints/rbd/rbd.py
  rest/workflows/__init__.py
  rest/workflows/rbd/__init__.py
  rest/workflows/rbd/rbd.py
  run.py
  suites/quincy/rbd/tier-2_rbd_rest.yaml
  suites/reef/rbd/tier-2_rbd_rest.yaml
  tests/rbd/rest/__init__.py
  tests/rbd/rest/test_rbd_rest_pool_image_creation.py
Labels: lgtm

#3606 Nvmeof code changes to adopt few new CLIS
  ceph/nvmegw_cli/__init__.py
  ceph/nvmegw_cli/common.py
  tests/cephadm/test_nvmeof.py
  tests/cephadm/test_orch.py
  tests/nvmeof/test_ceph_nvmeof_data_integrity.py
  tests/nvmeof/test_ceph_nvmeof_gateway.py
  tests/nvmeof/test_ceph_nvmeof_gateway_sub_scale.py
  tests/nvmeof/test_ceph_nvmeof_sub_limit.py
  tests/nvmeof/test_nvme_cli.py
Labels: lgtm, nvmeof

#3581 Adding Fs TC_CEPH-83586730
  suites/pacific/cephfs/tier-3_cephfs_bugs.yaml
  suites/quincy/cephfs/tier-3_cephfs_bugs.yaml
  suites/reef/cephfs/tier-3_cephfs_bugs.yaml
  tests/cephfs/cephfs_bugs/test_mds_inject_health_dummy.py
  tests/cephfs/cephfs_utilsV1.py
Labels: Ceph-FS, lgtm, close-loop-automation

#3597 [TFA] Introducing small delay before monitor_consistency_via_bucket_stats
  tests/rgw/sanity_rgw_multisite.py
Labels: pr-verified, RGW, lgtm, tfa-issue-fix

#3599 [TFA] Removing abort-on-failure from baremetal
  suites/quincy/baremetal_pipeline/tier-1_rgw_ms.yaml
  suites/reef/rgw/baremetal/scale_rgw_multi_site.yaml
  suites/reef/rgw/baremetal/scale_rgw_single_site.yaml
Labels: RGW, lgtm, tfa-issue-fix

#3609 [TFA issue fix] include datalog trim testcase in reef and run from primary
  suites/pacific/rgw/tier-2_rgw_singlesite_to_multisite.yaml
  suites/reef/rgw/tier-2_rgw_singlesite_to_multisite.yaml
Labels: pr-verified, RGW, lgtm, tfa-issue-fix

#3592 Changing order of the 5000 full sync test in the suite
  suites/reef/rgw/tier-2_rgw_ms_archive_with_haproxy.yaml
Labels: RGW, lgtm, tfa-issue-fix

#3593 Execute the tier-2 tests before zone rename(negative tests)
  suites/reef/rgw/tier-2_rgw_singlesite_to_multisite.yaml
Labels: RGW, lgtm, tfa-issue-fix

#3607 Unify all NVMe GW CLI command options
  ceph/nvmegw_cli/__init__.py
  ceph/nvmegw_cli/host.py
  ceph/nvmegw_cli/listener.py
  ceph/nvmegw_cli/namespace.py
  ceph/nvmegw_cli/subsystem.py
  tests/nvmeof/test_ceph_nvmeof_data_integrity.py
  tests/nvmeof/test_ceph_nvmeof_gateway.py
  tests/nvmeof/test_ceph_nvmeof_neg_tests.py
  tests/nvmeof/test_io_perf.py
Labels: lgtm, nvmeof

#3613 [Lib] Fix polarion testrun reporting
  cephci/reports.py
Labels: lgtm

#3611 RBD package support for pydocs
  ceph/rbd/__init__.py
  ceph/rbd/workflows/__init__.py
  cli/rbd/__init__.py
Labels: lgtm, approved

#3612 [NFS-Ganesha][HA] Test export delete with HA windows client
  suites/reef/nfs/tier1-nfs-ganesha-ha-windows.yaml
  tests/nfs/nfs_ha_export_delete_windows.py
Labels: lgtm

#3590 Adding tests for all workloads in Specstorage
  cli/io/spec_storage.py
  suites/reef/cephfs/tier-2_cephfs_io.yaml
  tests/cephfs/cephfs_spec_storage.py
Labels: lgtm

#3559 [Test] Validate CLI tests for "ceph-volume lvm"
  cli/ceph/ceph_volume/__init__.py
  cli/ceph/ceph_volume/ceph_volume.py
  cli/ceph/ceph_volume/lvm.py
  cli/cephadm/cephadm.py
  suites/reef/ceph_volume/tier1-ceph-volume-lvm-cli-validations.yaml
  tests/ceph_volume/test_ceph_volume_lvm_cli_validations.py
Labels: lgtm

#3608 mon_serviceability.py: Added checks to look for crashes post mon operations
  ceph/rados/core_workflows.py
  tests/rados/test_mon_addition_removal.py
  tests/rados/test_mon_system_operations.py
Labels: RADOS, lgtm

#3615 RBD group snap and rollback usecase
  ceph/rbd/workflows/group.py
  cli/rbd/group.py
  suites/quincy/rbd/tier-2_rbd_group.yaml
  suites/reef/rbd/tier-2_rbd_group.yaml
  tests/rbd/test_rbd_group_snapshot_usecase.py
Labels: lgtm, approved

#3616 CEPH-83588304: Tier-3 test to verify no ceph-mgr crashes when monitor weights are out of sync
  ceph/rados/core_workflows.py
  suites/pacific/rados/tier-3_rados-recovery_tests.yaml
  suites/quincy/rados/tier-3_rados-recovery_tests.yaml
  suites/reef/rados/tier-3_rados-recovery_tests.yaml
  tests/rados/test_mon_mgr_weight.py
  tests/rados/test_pg_log_limit.py
Labels: RADOS, lgtm, Tier-3, Polarion testcase, Ready-for-review

#3617 Fix Rados Inconsistent Objects test cases
  ceph/rados/core_workflows.py
  suites/pacific/rados/tier-2_rados_trim_tests.yaml
  suites/quincy/rados/tier-2_rados_trim_tests.yaml
  suites/reef/rados/tier-2_rados_trim_tests.yaml
  tests/rados/test_inconsistency_osd_epoch.py
  tests/rados/test_osd_inconsistency_pg.py
Labels: RADOS, lgtm, tfa-issue-fix

#3619 Updating mero1 config file to change client node magna010 to magna011
  conf/baremetal/mero1_1admin_4node_4client.yaml
Labels: lgtm

#3618 [NFS-Ganesha][HA] Test modify file with node reboot
  suites/reef/nfs/tier1-nfs-ganesha-ha-windows.yaml
  tests/nfs/nfs_ha_reboot_with_file_modify.py
Labels: lgtm

#3603 7.1 cg automation updates
  conf/reef/cephfs/tier-1_cephfs_cg_quiesce.yaml
  suites/reef/cephfs/tier-1_cephfs_cg_quiesce.yaml
  suites/reef/cephfs/tier-1_cephfs_cg_quiesce_systemic.yaml
  tests/cephfs/snapshot_clone/cephfs_cg_io.py
  tests/cephfs/snapshot_clone/cg_snap_system_test.py
  tests/cephfs/snapshot_clone/cg_snap_test.py
Labels: lgtm

#3622 Fixing Baremetal intermittent bootstrap issue
  ceph/ceph.py
Labels: lgtm

#3625 nvmeof: ibm registry login on GW nodes
  ceph/nvmegw_cli/__init__.py
Labels: nvmeof

#3623 Fixing the vault failures for baremetal and VMs
  tests/misc_env/install_vault.py
Labels: RGW, lgtm, tfa-issue-fix, baremetal

#3626 Fixing dmfg baremetal configs
  conf/baremetal/dmfg_clara_1admin_5node_2client.yaml
  suites/reef/cephadm/upi/upi-dmfg-deployment.yaml
Labels: lgtm

#3610 NVMe HA automation support
  ceph/nvmegw_cli/__init__.py
  ceph/nvmegw_cli/connection.py
  ceph/nvmegw_cli/execute.py
  ceph/nvmegw_cli/gateway.py
  ceph/nvmegw_cli/listener.py
  ceph/nvmegw_cli/log_level.py
  ceph/nvmegw_cli/version.py
  ceph/nvmeof/nvme_cli.py
  conf/reef/nvmeof/ceph_nvmeof_ha_cluster.yaml
  suites/reef/nvmeof/tier-1_nvmeof_ha_sanity.yaml
  tests/nvmeof/test_ceph_nvmeof_high_availability.py
  tests/nvmeof/workflows/__init__.py
  tests/nvmeof/workflows/ha.py
  tests/nvmeof/workflows/initiator.py
  tests/nvmeof/workflows/nvme_gateway.py
  utility/systemctl.py
Labels: lgtm, nvmeof, Reef, RHCS-7.1-New-Feature

#3627 Adding MDS role and updating client rpms
  conf/baremetal/mero2_1admin_4node_4client.yaml
  tests/cephfs/cephfs_utilsV1.py
Labels: lgtm

#3629 [Conf] Add IBM Cloud inventory for 2vCPU & 8GB
  conf/inventory/ibm-vpc-rhel-9.2-minimal-bx2-2x8.yaml
  conf/inventory/ibm-vpc-rhel-9.2-minimal_ref.yaml
Labels: lgtm

#3630 Fixing the typo for restart
  suites/reef/rgw/tier-2_rgw_ms_archive_with_haproxy.yaml
Labels: RGW, lgtm, tfa-issue-fix

#3631 Fix issue at enable-fips mode in custom configs.
  run.py
Labels: bug in framework, framework, lgtm

#3632 Added polarion id for 2 NVMeof GW HA test
  suites/reef/nvmeof/tier-1_nvmeof_ha_sanity.yaml
Labels: lgtm, approved, nvmeof

#3589 Migrate default zone configuration single to multisite
  conf/reef/rgw/migrate_default_single_to_multisite.yaml
  suites/reef/rgw/migrate_default_single_to_multisite.yaml
  suites/reef/rgw/tier-2_rgw_singlesite_to_multisite.yaml
Labels: RGW, lgtm, Tier-2, close-loop-automation, tfa-issue-fix

#3633 Rados mute alerts: Added adutomation for bug automation : 2247232
  tests/rados/mute_alerts.py
Labels: RADOS, lgtm, close-loop-automation

#3541 [Hardware Monitoring] [Baremetal] Add support for hardware monitoring
  cephci/stats.py
  cephci/utils/configs.py
  cli/reports/database.py
Labels: enhancement, lgtm

#3638 [Cephadm][Upgrade]Add suite
  suites/pacific/upgrades/tier-1-upgrade-5x-to-5x_latest-check-rgw-pool.yaml
  tests/cephadm/test_verify_pool.py
Labels: lgtm, CephAdm

#3621 Add 2 more functional automations to CG test script
  tests/cephfs/snapshot_clone/cephfs_cg_io.py
  tests/cephfs/snapshot_clone/cg_snap_test.py
Labels: lgtm

#3640 Modifying the OSD deploy
  suites/quincy/rados/tier-3_rados_test-stretch-mode-baremetal.yaml
  suites/reef/rados/tier-3_rados_test-stretch-mode-baremetal.yaml
Labels: lgtm

#3636 Adding FS TC_83583723
  tests/cephfs/cephfs_bugs/test_clone_delete_with_FS_fail.py
Labels: lgtm

#3641 Update no. of clients to use as 10 instead of 9
  tests/cephfs/snapshot_clone/cg_snap_system_test.py
Labels: lgtm

#3634 [TFA] Fixing add network delay testcase for existing delay baremetal
  tests/misc_env/configure-tc.py
Labels: pr-verified, RGW, lgtm, tfa-issue-fix, baremetal

#3624 [TFA]Update testcase config as per the scale config of mero
  suites/reef/baremetal/tier-3_rgw.yaml
Labels: pr-verified, RGW, lgtm, tfa-issue-fix, baremetal

#3646 cphfs-bugs-tfa- timeout with long_running
  tests/cephfs/cephfs_bugs/test_validate_mclientcaps_revoke_ack.py
Labels: Ceph-FS, lgtm, tfa-issue-fix

#3645 removing mon_host check in cephfs peer connection
  tests/cephfs/cephfs_mirroring/cephfs_mirroring_utils.py
Labels: Ceph-FS, lgtm, tfa-issue-fix

#3635 Adding FS TC 83583721
  suites/reef/cephfs/tier-3_cephfs_bugs.yaml
  tests/cephfs/cephfs_bugs/validate_mds_metadata.py
  tests/cephfs/cephfs_utils.py
  tests/cephfs/cephfs_utilsV1.py
Labels: lgtm

#3649 Fix for config assimilation test failure.
  suites/reef/rados/tier-3_rados_test-location-stretch-mode.yaml
  tests/rados/test_config_assimilation.py
  tests/rados/test_pool_osd_recovery.py
Labels: RADOS, lgtm, tfa-issue-fix

#3650 [TFA]: Fix typo on restart post zone modify
  suites/pacific/rgw/tier-2_rgw_multisite_archive_with_haproxy.yaml
Labels: RGW, lgtm, tfa-issue-fix

#3642 Test cases for 4 Gateway HA failover and failback
  ceph/ceph_admin/helper.py
  ceph/ceph_admin/orch.py
  conf/reef/nvmeof/ceph_nvmeof_ha_cluster_4nodes.yaml
  suites/reef/nvmeof/tier-2_nvmeof_4nodes_gateway_ha_tests.yaml
  tests/nvmeof/workflows/ha.py
Labels: lgtm, nvmeof, RHCS-7.1-New-Feature

#3639 Automate CephFS-Geo-Metrics on HA Config
  suites/reef/cephfs/tier-2_cephfs_mirror_ha_metrics.yaml
  tests/cephfs/cephfs_mirroring/test_cephfs_mirroring_configure_cephfs_mirroring_ha.py
  tests/cephfs/cephfs_mirroring/test_cephfs_mirroring_ha_metrics.py
Labels: Ceph-FS, lgtm, RHCS-7.1-New-Feature

#3652 TFA-Add known issue for sse-s3 copy and remove bucket stats test from…
  suites/pacific/rgw/tier-2_rgw_multisite_archive_with_haproxy.yaml
Labels: RGW, lgtm, tfa-issue-fix

#3655 fix_nsid in namespace add in scale tests
  tests/nvmeof/test_ceph_nvmeof_gateway_sub_scale.py
Labels: lgtm, nvmeof

#3656 systemctl and daemon methods for failover/failback
  suites/reef/nvmeof/tier-1_nvmeof_ha_sanity.yaml
  suites/reef/nvmeof/tier-2_nvmeof_4nodes_gateway_ha_tests.yaml
  tests/nvmeof/workflows/ha.py
  tests/nvmeof/workflows/nvme_gateway.py
Labels: lgtm, nvmeof, early-automation-7.1, RHCS-7.1-New-Feature
