Repository red-hat-storage/cephci, pull requests merged in 2024-02, with the labels that each got.

#3363 [TFA] Enable sync between zones before testcase of Granular sync policy
  suites/reef/rgw/tier-2_rgw_multisite_scenarios.yaml
Labels: pr-verified, RGW, lgtm, tfa-issue-fix

#3368 [feat] Automate testcases for qos of namespace
  ceph/nvmegw_cli/namespace.py
  suites/reef/nvmeof/tier-1_nvmeof_qos.yaml
  suites/reef/nvmeof/tier-4_nvmeof_neg_tests.yaml
  tests/nvmeof/test_ceph_nvmeof_neg_tests.py
Labels: DNM, nvmeof

#3372 Adding changes to address pipeline automation issue
  ceph/rbd/workflows/krbd_io_handler.py
Labels: lgtm, approved

#3367 [Cephadm][Tier-2] Add test to validate cluster and public network change
  suites/reef/cephadm/tier2-permissive-mode-scenarios.yaml
  tests/cephadm/test_validate_cluster_and_public_network_change.py
Labels: lgtm

#3364 [Test][Cephadm][UPI] Add test multi osd deploy with dmcrypt true
  suites/reef/cephadm/upi/upi-multi-osd-with-encryption.yaml
Labels: lgtm

#3369 [TFA] Fix the IndexError
  tests/cephadm/test_package_validation.py
Labels: lgtm

#3371 [Tier-2] cephci integration of polarion TC: CEPH-11148
  suites/pacific/rgw/tier-2_rgw_test_5-3_specific_fixes.yaml
  suites/reef/rgw/tier-2_rgw_regression_extended.yaml
Labels: pr-verified, RGW, lgtm, Tier-2

#3327 [close-loop] bug-2180549, test multisite mixed-mode upgrade
  suites/reef/rgw/tier-1_rgw_ms_upgrade_5_3GA_to_7x_latest.yaml
Labels: RGW, lgtm, close-loop-automation

#3362 integrating test sts aswi creds expire while object copy is in progress
  suites/pacific/rgw/tier-2_rgw_sts_aswi.yaml
  suites/reef/rgw/tier-2_rgw_sts_aswi.yaml
Labels: pr-verified, RGW, lgtm, close-loop-automation, Tier-4, hotfix

#3358 TFA, fixing sse test failures and remove redundant tests
  suites/reef/rgw/tier-2_rgw_ms_async_data_notification.yaml
Labels: RGW, lgtm, tfa-issue-fix

#3355 TFA, s3tests: fixing the sts test failures
  tests/rgw/test_s3.py
Labels: RGW, lgtm, tfa-issue-fix

#3370 [tfa-fix] Add fix for keyring not present error
  tests/cephadm/test_cephadm_operations_via_admin.py
Labels: lgtm, DMFG, tfa-issue-fix

#3323 Integration of RGW-LC improvements and LC expiration at archive zone
  suites/reef/rgw/tier-1_rgw_ms_upgrade_5_3GA_to_7x_latest.yaml
  suites/reef/rgw/tier-2_rgw_ms-archive.yaml
Labels: RGW, lgtm, Tier-2, early-automation-7.1, 7.0-bugs-automate

#3357 Added Rados missing polarion tests from test suites
  ceph/rados/core_workflows.py
  conf/pacific/rados/test-confs/pool-configurations.yaml
  conf/quincy/rados/test-confs/pool-configurations.yaml
  conf/reef/rados/test-confs/pool-configurations.yaml
  suites/pacific/rados/tier-2_rados_test-pg-dups-trimming.yaml
  suites/pacific/rados/tier-2_rados_test-pg-split-merge.yaml
  suites/pacific/rados/tier-2_rados_test-pool-functionalities.yaml
  suites/pacific/rados/tier-2_rados_test-stretch-mode-upgrade.yaml
  suites/pacific/rados/tier-2_rados_test-stretch-mode.yaml
  suites/pacific/rados/tier-2_rados_trim_tests.yaml
  suites/pacific/rados/tier-3_rados_test-location-stretch-mode.yaml
  suites/quincy/rados/tier-2_rados_test-pg-dups-trimming.yaml
  suites/quincy/rados/tier-2_rados_test-pg-split-merge.yaml
  suites/quincy/rados/tier-2_rados_test-pool-functionalities.yaml
  suites/quincy/rados/tier-2_rados_test-stretch-mode-upgrade.yaml
  suites/quincy/rados/tier-2_rados_test-stretch-mode.yaml
  suites/quincy/rados/tier-2_rados_trim_tests.yaml
  suites/quincy/rados/tier-3_rados_test-location-stretch-mode.yaml
  suites/quincy/upstream/tier-2_rados_test-stretch-mode.yaml
  suites/reef/rados/tier-2_rados_test-pg-dups-trimming.yaml
  suites/reef/rados/tier-2_rados_test-pg-split-merge.yaml
  suites/reef/rados/tier-2_rados_test-pool-functionalities.yaml
  suites/reef/rados/tier-2_rados_test-stretch-mode-upgrade.yaml
  suites/reef/rados/tier-2_rados_test-stretch-mode.yaml
  suites/reef/rados/tier-2_rados_trim_tests.yaml
  suites/reef/rados/tier-3_rados_test-location-stretch-mode.yaml
  tests/rados/pool_tests.py
  tests/rados/test_osd_inconsistency_pg.py
  tests/rados/test_osd_snap_inconsistency_pg.py
  tests/rados/test_pg_split.py
Labels: RADOS, lgtm

#3379 [tfa-fix] Add fix to wait for container file contents to update
  tests/cephadm/test_cephadm_custom_config_support.py
Labels: lgtm, DMFG, tfa-issue-fix

#3381 [tfa-fix] Rename test_osd_memory_target for cephadm and fix json error
  suites/pacific/cephadm/tier-2-osd-scenarios.yaml
  suites/quincy/cephadm/tier-2-osd-scenarios.yaml
  suites/reef/cephadm/tier2-osd-scenarios.yaml
  tests/cephadm/test_osd_memory_target_cephadm.py
Labels: lgtm, DMFG, tfa-issue-fix

#3378 [Tier-2] cephci Integration of polarion testcase: CEPH-11150
  suites/pacific/rgw/tier-2_rgw_test_5-3_specific_fixes.yaml
  suites/reef/rgw/tier-2_rgw_regression_extended.yaml
Labels: pr-verified, RGW, lgtm, Tier-2

#3385 Rados: Adding missing polation test IDs from test suites
  suites/pacific/rados/tier-2_rados_test-stretch-mode-upgrade.yaml
  suites/pacific/rados/tier-2_rados_test-stretch-mode.yaml
  suites/pacific/rados/tier-3_rados_test-location-stretch-mode.yaml
  suites/quincy/rados/tier-2_rados_test-stretch-mode-upgrade.yaml
  suites/quincy/rados/tier-2_rados_test-stretch-mode.yaml
  suites/quincy/rados/tier-3_rados_test-location-stretch-mode.yaml
  suites/reef/rados/tier-2_rados_test-stretch-mode-upgrade.yaml
  suites/reef/rados/tier-2_rados_test-stretch-mode.yaml
  suites/reef/rados/tier-3_rados_test-location-stretch-mode.yaml
Labels: lgtm

#3384 Add Polarion ID for ratelimit conlict Tier-4 test case
  suites/quincy/rgw/tier-2_rgw_test-using-s3cmd.yaml
  suites/reef/rgw/tier-2_rgw_test_using_s3cmd.yaml
Labels: lgtm

#3383 TFA fixes for snap schedule tests
  tests/cephfs/cephfs_utilsV1.py
  tests/cephfs/snapshot_clone/cephfs_snap_utils.py
  tests/cephfs/snapshot_clone/snap_schedule_retention_vol_subvol.py
Labels: Ceph-FS, lgtm, Polarion testcase, tfa-issue-fix

#3382 Adding Cephfs generic cases
  suites/pacific/cephfs/tier-2_cephfs_generic.yaml
  suites/pacific/cephfs/tier-2_cephfs_test-volume-management.yaml
  suites/quincy/cephfs/tier-2_cephfs_generic.yaml
  suites/quincy/cephfs/tier-2_cephfs_test-volume-management.yaml
  suites/reef/cephfs/tier-2_cephfs_generic.yaml
  suites/reef/cephfs/tier-2_cephfs_test-volume-management.yaml
  tests/cephfs/mds_beacon_grace_param_test.py
  tests/cephfs/mds_fail_with_rank.py
Labels: Ceph-FS, lgtm

#3386 [Utility] Add testplan support to testrun
  cephci/reports.py
Labels: framework, lgtm

#3388 RBD namespace in default pool tests
  ceph/rbd/workflows/namespace.py
  cli/rbd/namespace.py
  cli/rbd/pool.py
  cli/rbd/rbd.py
  suites/quincy/rbd/tier-2_rbd_namespace.yaml
  suites/reef/rbd/tier-2_rbd_namespace.yaml
  tests/rbd/test_rbd_namespace_default_pool.py
Labels: lgtm, approved

#3375 Scale test on 2 nvmeof GWs with 2048 namespaces
  suites/reef/nvmeof/tier-3_2-nvmeof-gw_1-sub_ns.yaml
  suites/reef/nvmeof/tier-3_2-nvmeof-gw_16-sub_ns.yaml
  suites/reef/nvmeof/tier-3_2-nvmeof-gw_2-sub_ns.yaml
  suites/reef/nvmeof/tier-3_2-nvmeof-gw_4-sub_ns.yaml
  suites/reef/nvmeof/tier-3_2-nvmeof-gw_8-sub_ns.yaml
  tests/nvmeof/test_ceph_nvmeof_gateway_sub_scale.py
Labels: lgtm, nvmeof

#3393 Fixing ceph version pick for baremetal
  pipeline/vars/v3.groovy
Labels: lgtm

#3377 [NFA-Ganesha][Reef]Upgrade with NFS-Ganesha HA
  suites/reef/nfs/tier1-nfs-ganesha-ha-upgrade-ibm-7x-to-7x-latest.yaml
  suites/reef/nfs/tier1-nfs-ganesha-ha-upgrade-rhcs-7x-to-7x-latest.yaml
Labels: lgtm, nfs-ganesha

#3391 [TFA] removing network delay from suite which are part of regression
  suites/reef/rgw/tier-1_rgw_ms_ecpool_regression_test.yaml
  suites/reef/rgw/tier-2_rgw_3_way_multisite.yaml
Labels: pr-verified, RGW, lgtm, tfa-issue-fix

#3397 [Upgrade] including Single and Multisite upgrade from 7.0ga to latest
  suites/reef/rgw/tier-1_rgw_ms_upgrade_7_0GA_to_7x_latest.yaml
  suites/reef/rgw/tier-1_rgw_upgrade_7_0GA_to_7x_latest.yaml
Labels: pr-verified, RGW, Upgrade

#3374 [Lib][Nfs] Add support for windows clients
  cli/utilities/windows_utils.py
  suites/reef/nfs/tier1-nfs-ganesha-windows-clients.yaml
  tests/nfs/nfs_verify_windows_client.py
Labels: lgtm, approved, DMFG, nfs-ganesha

#3395 RBD namespace related 4 more tests
  suites/quincy/rbd/tier-2_rbd_namespace.yaml
  suites/reef/rbd/tier-2_rbd_namespace.yaml
  tests/rbd/test_rbd_namespace_custom_pool.py
  tests/rbd/test_rbd_namespace_image_pool.py
  tests/rbd/test_rbd_namespace_same_img_diff_ns.py
  tests/rbd/test_rbd_namespace_same_ns_diff_pool.py
Labels: lgtm, approved

#3403 Adding fix to snapshot and mds_laggy
  tests/cephfs/cephfs_bugs/test_mds_laggy_thrown_out.py
  tests/cephfs/cephfs_scale/max_snapshots.py
Labels: lgtm

#3387 CG snap cephfs 7.1 feature automation - io tool and functional test w…
  tests/cephfs/snapshot_clone/cephfs_cg_io.py
  tests/cephfs/snapshot_clone/cg_snap_test.py
  tests/cephfs/snapshot_clone/cg_snap_utils.py
Labels: Ceph-FS, lgtm, Polarion testcase

#3389 Adding log rotation policy
  utility/log.py
Labels: lgtm

#3401 [Lib-fix] Fix create_yaml_config to have spec
  cli/utilities/utils.py
Labels: lgtm

#3400 [Lib] Add OSD ls library
  cli/ceph/osd/osd.py
Labels: lgtm

#3342 [Test] Re-deploy collocated and non-collcated OSDs
  suites/quincy/ceph_volume/tier2-ceph-volume-redeploy.yaml
  suites/reef/ceph_volume/tier2-ceph-volume-redeploy.yaml
  tests/ceph_volume/test_redeploy_collocated_and_non_collocated_osd.py
Labels: lgtm

#3406 TFA fixes
  tests/cephfs/cephfs_scale/max_smallfile_snap.py
  tests/cephfs/cephfs_scale/max_snapshots.py
  tests/cephfs/cephfs_utilsV1.py
  tests/cephfs/snapshot_clone/cephfs_snap_utils.py
  tests/cephfs/snapshot_clone/snap_schedule_retention_vol_subvol.py
Labels: lgtm

#3380 Scale test on 4 nvmeof GWs with 2048 namespaces
  suites/reef/nvmeof/tier-3_4-nvmeof-gw_1-sub_ns.yaml
  suites/reef/nvmeof/tier-3_4-nvmeof-gw_16-sub_ns.yaml
  suites/reef/nvmeof/tier-3_4-nvmeof-gw_2-sub_ns.yaml
  suites/reef/nvmeof/tier-3_4-nvmeof-gw_4-sub_ns.yaml
  suites/reef/nvmeof/tier-3_4-nvmeof-gw_8-sub_ns.yaml
Labels: lgtm, nvmeof

#3402 CEPH-83573627: Verify Mon election strategies in stretch mode and normal cluster
  conf/quincy/rados/stretch-mode-host-location-attrs.yaml
  conf/reef/rados/stretch-mode-host-location-attrs.yaml
  suites/pacific/rados/tier-2-rados-basic-regression.yaml
  suites/pacific/rados/tier-2_rados_test-brownfield.yaml
  suites/pacific/rados/tier-2_rados_test-stretch-mode.yaml
  suites/quincy/rados/tier-2-rados-basic-regression.yaml
  suites/quincy/rados/tier-2_rados_test-stretch-mode.yaml
  suites/reef/rados/tier-2-rados-basic-regression.yaml
  suites/reef/rados/tier-2_rados_test-stretch-mode.yaml
  tests/rados/monitor_configurations.py
  tests/rados/test_election_strategies.py
Labels: RADOS, lgtm, Tier-3, Polarion testcase, Ready-for-review

#3404 [TFA] To reduce execution time, reduced the network delay induced in suite
  suites/pacific/rgw/tier-1_rgw_ecpool_ms-bucket-listing-versioning-on-primary.yaml
  suites/pacific/rgw/tier-1_rgw_ecpool_ms-bucket-object-gc-policy-on-primary.yaml
  suites/pacific/rgw/tier-1_rgw_ms-bucket-listing-versioning-on-secondary.yaml
  suites/pacific/rgw/tier-1_rgw_ms-bucket-object-gc-policy-on-secondary.yaml
  suites/pacific/rgw/tier-2_rgw_singlesite_to_multisite.yaml
  suites/pacific/rgw/tier-2_rgw_sts_aswi.yaml
  suites/reef/rgw/tier-2_rgw_singlesite_to_multisite.yaml
  suites/reef/rgw/tier-2_rgw_sts_aswi.yaml
Labels: RGW, lgtm, tfa-issue-fix

#3411 Cephci Integration of CEPH-83583080
  suites/pacific/rgw/tier-2_rgw_regression.yaml
  suites/quincy/rgw/tier-2_rgw_regression_extended.yaml
  suites/reef/rgw/tier-2_rgw_regression_extended.yaml
Labels: pr-verified, RGW, lgtm, Tier-2, close-loop-automation

#3412 integrating rgw quota verification and test bucket quota conflict using curl
  suites/quincy/rgw/tier-2_rgw_6_1_fixes.yaml
  suites/reef/rgw/sanity_rgw_multisite.yaml
  suites/reef/rgw/tier-1_rgw_ms_ecpool_regression_test.yaml
  suites/reef/rgw/tier-2_rgw_regression_test.yaml
Labels: pr-verified, RGW, lgtm, Tier-2, close-loop-automation

#3405 v7 scale test module
  tests/nvmeof/test_ceph_nvmeof_gateway_sub_scale.py
Labels: lgtm

#3399 [TFA][Test-fix] Add OSD ls and wait for OSD creation
  suites/quincy/ceph_volume/tier2-ceph-volume-redeploy.yaml
  suites/reef/ceph_volume/tier2-ceph-volume-redeploy.yaml
  tests/ceph_volume/test_ceph_volume_non_collocated.py
  tests/ceph_volume/test_ceph_volume_redeploy.py
  tests/ceph_volume/test_osd_deploy_with_spec_crush_device_class.py
Labels: lgtm

#3410 Baremetal config for DMFG and nfs
  conf/reef/baremetal/cali_conf.yaml
  conf/reef/baremetal/clara_conf.yaml
  suites/reef/baremetal/cali_suite.yaml
  suites/reef/baremetal/clara_suite.yaml
Labels: lgtm, DMFG, nfs-ganesha, baremetal

#3408 Persistant write back cache with encrypted images
  suites/quincy/rbd/tier-3_rbd_persistent_write_back_cache.yaml
  suites/reef/rbd/tier-3_rbd_persistent_write_back_cache.yaml
  tests/rbd/test_rbd_pwl_with_encrypted_images.py
Labels: RBD, lgtm, approved

#3413 Include S3CMD small and multipart object download testcase in rgw-san…
  suites/reef/rgw/tier-1_rgw.yaml
Labels: pr-verified, RGW, lgtm, tfa-issue-fix

#3414 Fix 2 nvmeof GWs scale test suite files as per scale discussion
  ceph/nvmeof/nvmeof_gwcli.py
  suites/reef/nvmeof/tier-3_2-nvmeof-gw_1-sub_ns.yaml
  suites/reef/nvmeof/tier-3_2-nvmeof-gw_16-sub_ns.yaml
  suites/reef/nvmeof/tier-3_2-nvmeof-gw_2-sub_ns.yaml
  suites/reef/nvmeof/tier-3_2-nvmeof-gw_4-sub_ns.yaml
  suites/reef/nvmeof/tier-3_2-nvmeof-gw_8-sub_ns.yaml
Labels: lgtm, nvmeof

#3407 [Lib] Add get_node_disks to cli/ops
  cli/ops/devices.py
Labels: lgtm

#3392 [Test] Create OSDs with existing LVMs
  suites/quincy/ceph_volume/tier2-ceph-volume-lvm.yaml
  suites/reef/ceph_volume/tier2-ceph-volume-lvm.yaml
  tests/ceph_volume/test_ceph_volume_prepare_lvm.py
Labels: lgtm

#3353 [Test] Deploy non-collocated OSDs with wrong db
  suites/quincy/ceph_volume/tier2-ceph-volume-non-collocated.yaml
  suites/reef/ceph_volume/tier2-ceph-volume-non-collocated.yaml
  tests/ceph_volume/test_ceph_volume_wrong_db_size_compute.py
Labels: lgtm

#3418 [tfa-fix] Change bootstrap playbook to use registry details
  suites/reef/cephadm/tier1-cephadm-ansible-wrapper-modules.yaml
Labels: lgtm, DMFG, tfa-issue-fix

#3420 Removing mero007 as we are facing reimage issue
  conf/reef/baremetal/mero_conf.yaml
Labels: lgtm

#3421 Adding os check in reimage and removing mero003
  conf/reef/baremetal/mero_conf.yaml
  pipeline/scripts/ci/reimage-octo-node.sh
Labels: lgtm

#3423 Adding password to client nodes
  conf/reef/baremetal/clara_conf.yaml
Labels: lgtm

#3409 [Lib] Add Memory and CPU usage monitoring support
  cli/performance/__init__.py
  cli/performance/memory_and_cpu_utils.py
  cli/performance/utilities/memory_and_cpu_logger.py
Labels: lgtm

#3419 [NFS-Ganesha][Automation][V3]Verify mount on both window and linux
  cli/utilities/utils.py
  cli/utilities/windows_utils.py
  suites/reef/nfs/tier1-nfs-ganesha-windows-clients.yaml
  tests/nfs/nfs_verify_v3_mount_window_linux.py
Labels: lgtm, approved, nfs-ganesha

#3424 [LibFix] Update cephci utilities to use logs
  cephci/cleanup.py
  cephci/cluster_conf.py
  cephci/cluster_info.py
  cephci/prereq.py
  cephci/provision.py
  cephci/reports.py
Labels: lgtm

#3416 RBD namespace removal 2 tests
  ceph/rbd/workflows/namespace.py
  ceph/rbd/workflows/rbd.py
  cli/rbd/rbd.py
  suites/quincy/rbd/tier-2_rbd_namespace.yaml
  suites/reef/rbd/tier-2_rbd_namespace.yaml
  tests/rbd/test_rbd_namespace_remove_neg.py
  tests/rbd/test_rbd_namespace_remove_pos.py
Labels: lgtm, approved

#3429 Converting M to m as per BZ 2265160
  tests/cephfs/snapshot_clone/cephfs_snap_utils.py
  tests/cephfs/snapshot_clone/snap_schedule.py
  tests/cephfs/snapshot_clone/snap_schedule_retention_vol_subvol.py
Labels: lgtm

#3417 CEPH-83583664: Tier-2 test to verify database reconnection by libcephsqlite
  ceph/rados/core_workflows.py
  suites/pacific/rados/tier-3_rados_cidr_blocklisting.yaml
  suites/quincy/rados/tier-3_rados_cidr_blocklisting.yaml
  suites/reef/rados/tier-3_rados_cidr_blocklisting.yaml
  tests/rados/test_libcephsqlite.py
Labels: RADOS, lgtm, Tier-2, Polarion testcase, Ready-for-review, close-loop-automation

#3428 CephFS - Tier3 - CEPH-83583762
  suites/pacific/cephfs/tier-3_cephfs_bugs.yaml
  suites/quincy/cephfs/tier-3_cephfs_bugs.yaml
  suites/reef/cephfs/tier-3_cephfs_bugs.yaml
  tests/cephfs/cephfs_bugs/test_disallow_fs_creation_with_pool_level_snaps.py
  tests/cephfs/cephfs_utilsV1.py
Labels: Ceph-FS, lgtm, Tier-3, Polarion testcase

#3431 Add BZ-2265890 as known issue to object lock test
  suites/reef/rgw/tier-2_rgw_regression_extended.yaml
Labels: RGW, lgtm, tfa-issue-fix

#3435 Perform snap create operation parallely/scale
  ceph/rbd/workflows/rbd.py
  ceph/rbd/workflows/snap_clone_operations.py
  suites/quincy/rbd/tier-3_rbd_snap_operations.yaml
  suites/reef/rbd/tier-3_rbd_snap_operations.yaml
  tests/rbd/test_rbd_image_snap_operations.py
Labels: lgtm, approved

#3433 [Nfs-Ganesha] Add multi mount version support
  suites/reef/nfs/tier1-nfs-ganesha-phase2.yaml
  tests/nfs/nfs_operations.py
  tests/nfs/nfs_verify_multi_mount_version.py
Labels: pr-verified, lgtm, DMFG, nfs-ganesha

#3430 [Lib] Add `connectible.remote` class
  cli/connectible/__init__.py
  cli/connectible/remote.py
  cli/exceptions.py
Labels: framework, lgtm

#3438 [NFS-Ganesha][Automation]Adding windows client scenario
  cli/utilities/utils.py
  suites/reef/nfs/tier1-nfs-ganesha-windows-clients.yaml
  tests/nfs/nfs_verify_mount_linux_v4_windows_clinet_v3.py
  tests/nfs/nfs_verify_window_clinets_file_rename_lookups.py
Labels: lgtm, nfs-ganesha

#3440 Test rootsquash Post running IO
  suites/reef/nfs/tier1-nfs-ganesha-windows-clients.yaml
  tests/nfs/nfs_rootsquash_post_io_operation_windows.py
Labels: lgtm

#3441 Rados: Updated the methods to wait for Clean PGs on a pool, instead of entire cluster
  pipeline/metadata/5.2.yaml
  pipeline/metadata/5.3.yaml
  pipeline/metadata/6.0.yaml
  pipeline/metadata/6.1.yaml
  pipeline/metadata/archived/5.3.yaml
  pipeline/metadata/archived/6.0.yaml
  pipeline/metadata/archived/6.1.yaml
  suites/pacific/rados/tier-2_rados_test-ecpool-osd-rebalance.yaml
  suites/pacific/rados/tier-2_rados_test-osd-inprogress-rebalance.yaml
  suites/pacific/rados/tier-2_rados_test-osd-rebalance-many-pools.yaml
  suites/pacific/rados/tier-2_rados_test-osd-rebalance-snap.yaml
  suites/pacific/rados/tier-2_rados_test-osd-rebalance.yaml
  suites/quincy/rados/tier-2_rados_test-ecpool-osd-rebalance.yaml
  suites/quincy/rados/tier-2_rados_test-osd-inprogress-rebalance.yaml
  suites/quincy/rados/tier-2_rados_test-osd-rebalance-many-pools.yaml
  suites/quincy/rados/tier-2_rados_test-osd-rebalance-snap.yaml
  suites/quincy/rados/tier-2_rados_test-osd-rebalance.yaml
  suites/reef/rados/tier-2_rados_test-ecpool-osd-rebalance.yaml
  suites/reef/rados/tier-2_rados_test-osd-inprogress-rebalance.yaml
  suites/reef/rados/tier-2_rados_test-osd-rebalance-many-pools.yaml
  suites/reef/rados/tier-2_rados_test-osd-rebalance-snap.yaml
  suites/reef/rados/tier-2_rados_test-osd-rebalance.yaml
  tests/rados/pool_tests.py
  tests/rados/stretch_cluster.py
  tests/rados/test_clay_ecpool.py
  tests/rados/test_four_node_ecpool.py
  tests/rados/test_mon_system_operations.py
  tests/rados/test_omap_entries.py
  tests/rados/test_osd_async_recovery.py
  tests/rados/test_osd_df.py
  tests/rados/test_osd_inprogress_rebalance.py
  tests/rados/test_osd_rebalance.py
  tests/rados/test_osd_rebalance_snap.py
  tests/rados/test_pg_split.py
  tests/rados/test_pool_osd_recovery.py
Labels: RADOS, lgtm

#3445 Fix for upgrade 7-1/2 to 7
  ceph/ceph_admin/bootstrap.py
Labels: lgtm

#3443 [Cephadm] Add test to verify OSD memory usage data
  cli/exceptions.py
  suites/reef/cephadm/tier2-osd-scenarios.yaml
  tests/cephadm/test_verify_incorrect_mem_usage.py
Labels: lgtm, DMFG, close-loop-automation

#3446 Adding a comment for TFA, known issue
  suites/reef/rgw/tier-2_rgw_ms_archive_with_haproxy.yaml
Labels: lgtm

#3436 [Tier-3]: CEPH-83575073 [PUT Workload] Test sync bi-directional with Versioned bucket
  suites/quincy/baremetal_pipeline/tier-1_rgw_ms.yaml
  tests/misc_env/push_cosbench_workload.py
  tests/parallel/test_parallel.py
Labels: pr-verified, RGW, lgtm, Tier-3, baremetal

#3447 Comparing ceph version
  ceph/ceph_admin/bootstrap.py
Labels: lgtm

#3442 Automation of the avoid ballooning client_mount_timeout(BZ#2233800)
  suites/quincy/rados/tier-2_rados_test-bugfixes.yaml
  suites/reef/rados/tier-2_rados_test-bugfixes.yaml
  tests/rados/test_rados_ballooning_client.py
Labels: RADOS, lgtm, Polarion testcase, Ready-for-review

#3396 Adding spec storage tests to FS
  cli/io/spec_storage.py
  suites/reef/cephfs/tier-2_cephfs_io.yaml
  tests/cephfs/cephfs_fio_storage.py
  tests/cephfs/cephfs_spec_storage.py
  tests/cephfs/cephfs_utilsV1.py
Labels: lgtm

#3426 Adding new folio config files
  conf/baremetal/folio1_1admin_4node_4client.yaml
  conf/baremetal/folio2_1admin_4node_4client.yaml
  conf/baremetal/mero2_1admin_4node_4client.yaml
  conf/baremetal/nfs_folio3_1admin_3node_4client.yaml
  suites/reef/baremetal/nfs_folio3_3node_4client.yaml
Labels: lgtm

#3439 [Perf-Mon] Enable Performance Monitoring
  cli/performance/memory_and_cpu_utils.py
  run.py
Labels: enhancement, lgtm, DMFG

#3449 Test rootsquash volume set operation
  suites/reef/nfs/tier1-nfs-ganesha-windows-clients.yaml
  tests/nfs/nfs_export_rootsquash_windows.py
Labels: lgtm

#3434 Added OSD and Host replacement scenarios in stretch mode
  ceph/rados/serviceability_workflows.py
  conf/pacific/rados/stretch-mode-host-location-attrs.yaml
  conf/quincy/rados/stretch-mode-host-location-attrs.yaml
  conf/reef/rados/stretch-mode-host-location-attrs.yaml
  suites/pacific/rados/tier-3_rados_test-location-stretch-mode.yaml
  suites/quincy/rados/tier-3_rados_test-location-stretch-mode.yaml
  suites/reef/rados/tier-3_rados_test-location-stretch-mode.yaml
  tests/rados/test_stretch_netsplit_scenarios.py
  tests/rados/test_stretch_osd_serviceability_scenarios.py
Labels: RADOS, lgtm, Tier-3

#3452 Rados: Updated the object size in the migration tests
  suites/pacific/rados/tier-2_rados_test-pool-functionalities.yaml
  suites/quincy/rados/tier-2_rados_test-pool-functionalities.yaml
  suites/reef/rados/tier-2_rados_test-pool-functionalities.yaml
  tests/rados/pool_tests.py
  tests/rados/test_data_migration_bw_pools.py
Labels: RADOS, lgtm, tfa-issue-fix

#3448 snap clone, remove operations parallely and scale
  ceph/rbd/workflows/snap_clone_operations.py
  suites/quincy/rbd/tier-3_rbd_snap_operations.yaml
  suites/reef/rbd/tier-3_rbd_snap_operations.yaml
  tests/rbd/test_rbd_image_snap_operations.py
Labels: lgtm, approved

#3455 adding known issue for reef s3tests anon_put_write_access and increasing network delay for sts hotfix test
  suites/pacific/rgw/tier-2_rgw_sts_aswi.yaml
  suites/reef/rgw/sanity_rgw.yaml
  suites/reef/rgw/tier-2_rgw_sts_aswi.yaml
  suites/reef/rgw/tier-2_ssl_rgw_ecpool_test.yaml
Labels: pr-verified, RGW, lgtm, tfa-issue-fix
