Repository red-hat-storage/cephci, pull requests merged in 2024-06, with the labels that each got.

#3723 PG Autoscaler tests: Added coverage for bug : 2136766
  ceph/rados/core_workflows.py
  suites/pacific/rados/tier-2-rados-basic-regression.yaml
  suites/quincy/rados/tier-2-rados-basic-regression.yaml
  suites/quincy/upstream/tier-2-rados-basic-regression.yaml
  suites/reef/rados/tier-2-rados-basic-regression.yaml
  tests/rados/pool_tests.py
  tests/rados/test_pg_autoscale_flag.py
  tests/rados/test_stretch_negative_scenarios.py
  tests/rados/test_stretch_osd_serviceability_scenarios.py
Labels: RADOS, lgtm

#3739 [RADOS] Alternate approach to 'wait_for_device' method
  ceph/rados/utils.py
  suites/pacific/rados/tier-2_rados_test-bugfixes.yaml
  suites/quincy/rados/tier-2_rados_bm_add_db_wal_cbt.yaml
  suites/quincy/rados/tier-2_rados_test-bugfixes.yaml
  suites/quincy/rados/tier-3_rados_test-stretch-mode-baremetal.yaml
  suites/reef/rados/tier-2_rados_bm_add_db_wal_cbt.yaml
  suites/reef/rados/tier-2_rados_test-bugfixes.yaml
  suites/reef/rados/tier-3_rados_test-stretch-mode-baremetal.yaml
  suites/squid/rados/tier-2_rados_bm_add_db_wal_cbt.yaml
  suites/squid/rados/tier-2_rados_test-bugfixes.yaml
  suites/squid/rados/tier-3_rados_test-stretch-mode-baremetal.yaml
  tests/rados/rados_test_util.py
  tests/rados/test_bug_fixes.py
  tests/rados/test_osd_inprogress_rebalance.py
Labels: RADOS, lgtm, Ready-for-review, tfa-issue-fix

#3743 fix wipefs issue in server setup script
  pipeline/scripts/ci/server_setup_utils.sh
Labels: script issue, lgtm, baremetal

#3734 Scripts for CephFS Scale Tests
  suites/reef/cephfs/tier-3_cephfs_scale_baremetal.yaml
  tests/cephfs/cephfs_scale/cleanup.py
  tests/cephfs/cephfs_scale/create_large_file.sh
  tests/cephfs/cephfs_scale/large_file_writes.py
Labels: Ceph-FS, lgtm

#3727 [NFS-Ganesha]Added support for export creation using subvolume and su…
  cli/ceph/nfs/export/export.py
  tests/nfs/nfs_client_permission_export.py
  tests/nfs/nfs_edit_export_config_with_1client_access.py
  tests/nfs/nfs_edit_export_config_with_ro.py
  tests/nfs/nfs_export_rootsquash_windows.py
  tests/nfs/nfs_ha_failover_edit_export_config_client_permission.py
  tests/nfs/nfs_ha_failover_edit_export_config_with_ro.py
  tests/nfs/nfs_operations.py
  tests/nfs/nfs_rootsquash_using_conf.py
  tests/nfs/nfs_verify_file_lock_root_squash.py
  tests/nfs/nfs_verify_setuid_bit.py
  tests/nfs/test_export_readonly.py
  tests/nfs/test_export_rootsquash.py
Labels: lgtm

#3753 fix wipefs issue
  pipeline/scripts/ci/server_setup_utils.sh
Labels: lgtm

#3740 kernel IO fs stress
  suites/pacific/cephfs/tier-0_fs_kernel.yaml
  suites/pacific/cephfs/tier-1_fs_kernel.yaml
Labels: lgtm

#3744 Adding Validation for defer_client_eviction_on_laggy_osds
  tests/cephfs/clients/mds_conf_modifying.py
Labels: lgtm

#3741 TFA fix,BZ id in comment,New Automation
  suites/reef/cephfs/tier-1_cephfs_cg_quiesce.yaml
  tests/cephfs/snapshot_clone/cephfs_cg_io.py
  tests/cephfs/snapshot_clone/cg_snap_test.py
Labels: Ceph-FS, lgtm, tfa-issue-fix, RHCS-7.1-New-Feature

#3745 Adding support for ceph logs
  ceph/ceph.py
  cephci/cluster_info.py
Labels: lgtm

#3750 [TFA][TestFix] Fix Conditional is marked as unsafe error
  tests/cephadm/ansible_wrapper/ceph_config/set-ceph-config.yaml
Labels: lgtm

#3752 [SuiteFix] Add polarion scenario to existing test
  suites/reef/ceph_volume/tier2-ceph-volume-lvm.yaml
Labels: lgtm

#3756 [Config] Add latest IBM cloud inventories
  conf/inventory/ibm-vpc-rhel-8-latest.yaml
  conf/inventory/ibm-vpc-rhel-8.10-minimal-bx2-2x8.yaml
  conf/inventory/ibm-vpc-rhel-8.10-minimal-bx2-4x16.yaml
  conf/inventory/ibm-vpc-rhel-8.8-minimal-bx2-2x8.yaml
  conf/inventory/ibm-vpc-rhel-8.8-minimal-bx2-4x16.yaml
  conf/inventory/ibm-vpc-rhel-9-latest.yaml
  conf/inventory/ibm-vpc-rhel-9.4-minimal-bx2-2x8.yaml
  conf/inventory/ibm-vpc-rhel-9.4-minimal-bx2-4x16.yaml
Labels: framework, lgtm

#3718 [TFA] Fix the RHEL8 and RHEL9 images used in the config file
  conf/reef/upgrades/upgrade_8-node-cluster_mix_os.yaml
Labels: lgtm

#3758 fsstress fix for tier-0 and tier-1 suites
  tests/cephfs/cephfs_bugs/test_fsstress_on_kernel_and_fuse.py
Labels: lgtm

#3749 Fix suite tier-3_4-nvmeof-gw_8-sub_ns.yaml format
  suites/reef/nvmeof/tier-3_4-nvmeof-gw_16-sub_ns.yaml
  suites/reef/nvmeof/tier-3_4-nvmeof-gw_2-sub_ns.yaml
  suites/reef/nvmeof/tier-3_4-nvmeof-gw_8-sub_ns.yaml
  suites/squid/nvmeof/tier-3_4-nvmeof-gw_16-sub_ns.yaml
  suites/squid/nvmeof/tier-3_4-nvmeof-gw_2-sub_ns.yaml
  suites/squid/nvmeof/tier-3_4-nvmeof-gw_8-sub_ns.yaml
Labels: lgtm

#3647 [RGW MS] Baremetal multisite config and suite changes due to disk space
  conf/baremetal/extensa_clara_multisite_1admin_4node_1client.yaml
  suites/reef/baremetal/deploy/rh/extensa_clara_multisite_1admin_4node_1client.yaml
  suites/reef/rgw/baremetal/scale_rgw_multi_site.yaml
Labels: RGW, lgtm, stale-warning-on-inactivity, tfa-issue-fix, baremetal

#3765 [Suite] Add polarion id to existing scenario
  suites/reef/ceph_volume/tier2-ceph-volume-lvm.yaml
Labels: lgtm

#3755 [TFA][DMFG][Cephadm][OS-Tuning-Profile]Updated mount value
  tests/cephadm/test_os_tuning_profile.py
Labels: lgtm, DMFG, tfa-issue-fix

#3762 TFA-FIX- Inconsistency objects repair on EC pool
  tests/rados/test_osd_ecpool_inconsistency_scenario.py
Labels: RADOS, lgtm, tfa-issue-fix

#3759 TFA fix to wait for more time for ceph status to be healthy before snap schedule test
  suites/reef/cephfs/tier-2_cephfs_test-snapshot-clone.yaml
  tests/cephfs/snapshot_clone/snap_schedule_retention_vol_subvol.py
Labels: lgtm

#3766 [TFA-Fix] Update baremetal cosbench driver
  suites/reef/baremetal/deploy/rh/extensa_clara_multisite_1admin_4node_1client.yaml
Labels: RGW, lgtm, tfa-issue-fix, baremetal

#3769 Correcting repo delete command
  tests/cephadm/test_cephadm_upgrade.py
Labels: lgtm

#3732 MDS metrcis scale Testing
  suites/reef/cephfs/tier-2_cephfs_test-metrics.yaml
  tests/cephfs/cephfs_metrics/cephfs_metrics_functional.py
  tests/cephfs/cephfs_metrics/cephfs_metrics_scale.py
  tests/cephfs/cephfs_utilsV1.py
Labels: Ceph-FS, lgtm

#3724 [Test] Add support for squid build
  tests/ceph_installer/test_disconnected_install.py
  tests/cephadm/test_custom_container.py
Labels: lgtm

#3747 CephFS Customer Case - CLA
  tests/cephfs/cephfs_utilsV1.py
  tests/cephfs/clients/mds_conf_modifying.py
Labels: Ceph-FS, lgtm, close-loop-automation

#3771 [Fix] Update Squid version smoke test
  suites/squid/smoke/build.yaml
Labels: lgtm

#3757 Adding Cephfs TC 83591136
  suites/reef/cephfs/tier-3_cephfs_bugs.yaml
  suites/squid/cephfs/tier-3_cephfs_bugs.yaml
  tests/cephfs/cephfs_bugs/multithreaded_file_writer.py
  tests/cephfs/cephfs_bugs/validate_mds_health_with_client_evict.py
Labels: lgtm

#3742 fixing s3select TFA issue of too many open files and integrating parquet tests
  suites/reef/rgw/tier-4-rgw.yaml
Labels: pr-verified, RGW, lgtm, Tier-4, tfa-issue-fix

#3751 [Tier-3] Intergration of polarion testcase CEPH-83575143 to cephci
  suites/reef/rgw/tier-1_rgw_ms_datalog_and_crash.yaml
  suites/squid/rgw/tier-1_rgw_ms_datalog_and_crash.yaml
Labels: pr-verified, RGW, lgtm, Tier-3, early-automation-7.1

#3772 [Automation][DMFG][SMB]Deployment smb with 500 shares
  suites/squid/smb/tier-1-smb-500-shares.yaml
  tests/smb/smb_deployment_500_shares.py
  tests/smb/smb_operations.py
Labels: lgtm, DMFG, smb

#3768 Test Gap enhancements for MDS failover workflow
  tests/cephfs/snapshot_clone/cephfs_cg_io.py
  tests/cephfs/snapshot_clone/cg_snap_test.py
Labels: lgtm

#3764 [Tier-3] Cephci integration of polarion testcase id : CEPH-83581958
  suites/reef/rgw/tier-1_rgw_ms_datalog_and_crash.yaml
  suites/reef/rgw/tier-2_rgw_ms_granular_sync_policy.yaml
  suites/squid/rgw/tier-1_rgw_ms_datalog_and_crash.yaml
  suites/squid/rgw/tier-2_rgw_ms_granular_sync_policy.yaml
Labels: pr-verified, RGW, lgtm, Tier-3, early-automation-7.1

#3700 Integrating the tests in PR 594
  suites/reef/rgw/tier-2_rgw_ms_archive_with_haproxy.yaml
Labels: RGW, lgtm, Tier-3

#3746 [Test][Cephadm] Add test to validate support to customize <daemon>-co…
  cli/utilities/utils.py
  suites/reef/cephadm/tier4-service-operations.yaml
  tests/cephadm/test_validate_container_cpu_limit.py
Labels: lgtm

#3778 fix split issue in wipefs section
  pipeline/scripts/ci/server_setup_utils.sh
Labels: lgtm, baremetal

#3777 Remove snap-sched multi-fs test as BZ is not fixed for 5.3
  suites/pacific/cephfs/tier-2_cephfs_test-snapshot-clone.yaml
  tests/cephfs/cephfs_bugs/test_client_blocklist_large_session_metadata.py
Labels: Ceph-FS, lgtm, tfa-issue-fix

#3775 [NFS-Ganesha][TFA] Fix the rootsquash and locking failures
  tests/nfs/nfs_edit_export_config_with_1client_access.py
  tests/nfs/nfs_operations.py
  tests/nfs/nfs_verify_file_lock.py
  tests/nfs/nfs_verify_file_lock_root_squash.py
  tests/nfs/nfs_verify_setuid_bit.py
  tests/nfs/test_export_rootsquash.py
Labels: lgtm

#3754 CEPH-83591092: OSD resiliency when 'bluefs_shared_alloc_size' is below 'bluestore_min_alloc_size'
  suites/pacific/rados/tier-2_rados_test-bugfixes.yaml
  suites/quincy/rados/tier-2_rados_test-bugfixes.yaml
  suites/reef/rados/tier-2_rados_test-bugfixes.yaml
  suites/squid/rados/tier-2_rados_test-bugfixes.yaml
  tests/rados/rados_test_util.py
  tests/rados/test_bug_fixes.py
Labels: RADOS, lgtm, Tier-2, Polarion testcase, Ready-for-review, close-loop-automation

#3781 [Add] Update Polarion ID for existing test
  suites/reef/cephadm/tier2-cluster-elasticity.yaml
  suites/squid/cephadm/tier2-cluster-elasticity.yaml
Labels: lgtm

#3774 Add Negative Scenario for Mirror Metrics
  tests/cephfs/cephfs_mirroring/cephfs_mirroring_utils.py
  tests/cephfs/cephfs_mirroring/test_cephfs_mirroring_metrics.py
Labels: Ceph-FS, lgtm, RHCS-7.1-New-Feature

#3779 [RADOS] TFA fix for utf-8 decode error & wait_for_device method
  suites/pacific/rados/tier-2_rados_test-ecpool-osd-rebalance.yaml
  suites/quincy/rados/tier-2_rados_test-ecpool-osd-rebalance.yaml
  suites/reef/rados/tier-2_rados_test-ecpool-osd-rebalance.yaml
  suites/squid/rados/tier-2_rados_test-ecpool-osd-rebalance.yaml
  tests/rados/rados_test_util.py
  tests/rados/test_objectstoretool_workflows.py
  tests/rados/test_osd_inprogress_rebalance.py
Labels: RADOS, lgtm, Ready-for-review, tfa-issue-fix

#3780 [Test] Add test for node-exporter entra-entrypoint
  suites/quincy/cephadm/tier1_node_exporter_operation.yaml
  suites/reef/cephadm/tier1_node_exporter_operation.yaml
  suites/squid/cephadm/tier1_node_exporter_operation.yaml
  tests/cephadm/test_node_exporter_extra_entrypoint.py
Labels: lgtm

#3738 [Test] Add ceph-volume starting and stopping OSD
  cli/ceph/osd/osd.py
  cli/cephadm/cephadm.py
  suites/quincy/ceph_volume/tier1-ceph-volume-sanity.yaml
  suites/reef/ceph_volume/tier1-ceph-volume-sanity.yaml
  tests/ceph_volume/test_ceph_volume_existing_osd.py
Labels: lgtm

#3687 [Test] Verify monitoring stack image version using ceph orchestrator
  cli/utilities/containers.py
  suites/reef/cephadm/tier1-container-cli-args-ibm.yaml
  suites/reef/cephadm/tier1-container-cli-args-rh.yaml
  tests/cephadm/test_ceph_orch_for_monitoring_image_version.py
Labels: lgtm

#3678 [Test] Add host to maintenance using flags
  cli/ceph/ceph.py
  cli/ceph/orch/host.py
  cli/ceph/osd/pool.py
  cli/ops/host.py
  suites/reef/cephadm/tier0-cephadm.yaml
  tests/cephadm/test_add_host_to_maintenance_using_flags.py
Labels: lgtm

#3783 [Config] Update IBM Cloud RHEL-8 inventory configurations
  conf/inventory/ibm-vpc-rhel-8.10-minimal-bx2-2x8.yaml
  conf/inventory/ibm-vpc-rhel-8.10-minimal-bx2-4x16.yaml
Labels: lgtm

#3784 Alternative way to find root disk
  pipeline/scripts/ci/server_setup_utils.sh
Labels: lgtm, baremetal

#3773 [dmfg] Add test to validate cephadm command timeout
  cli/utilities/cephadm-hold-lock-utility.py
  cli/utilities/utils.py
  suites/quincy/cephadm/tier2-cephadm-mgr-timeout.yaml
  tests/cephadm/test_cephadm_mgr_timeout.py
Labels: test case, lgtm, CephAdm, DMFG

#3787 fix syntax in server utils
  pipeline/scripts/ci/reimage-octo-node.sh
  pipeline/scripts/ci/server_setup_utils.sh
  suites/reef/baremetal/deploy/rh/nvme_cali_1admin_6node_2client.yaml
Labels: bug in framework, lgtm, baremetal

#3792 [TestFix] Add bz info to test
  tests/cephadm/test_verify_incorrect_mem_usage.py
Labels: lgtm

#3794 Adding retry for getting standby_reply mds
  conf/baremetal/mero1_1admin_4node_4client.yaml
  conf/baremetal/mero2_1admin_4node_4client.yaml
  tests/cephfs/cephfs_bugs/test_mds_inject_health_dummy.py
Labels: lgtm

#3763 [Test] Verify Prometheus daemon retention_time is adjustable
  suites/reef/cephadm/tier1-service-apply-spec.yaml
  tests/cephadm/test_adjust_prometheus_retention_time.py
Labels: lgtm

#3788 Adding two new interop and negative scenario in cg quiesce,Ephemeral …
  suites/reef/cephfs/tier-1_cephfs_cg_quiesce.yaml
  suites/squid/cephfs/tier-1_cephfs_cg_quiesce.yaml
  tests/cephfs/snapshot_clone/cephfs_cg_io.py
  tests/cephfs/snapshot_clone/cg_snap_test.py
Labels: lgtm

#3797 [NFS-Ganesha][Feature Automation] Test NFS Ganesha extended attribute…
  suites/squid/nfs/tier0-nfs-ganesha-vers-4-2.yaml
  tests/nfs/nfs_operations.py
  tests/nfs/test_nfs_get_set_attr_operation.py
Labels: lgtm

#3789 [NFS-Ganesha][Baremetal] Fix the baremetal pipeline test failures
  tests/nfs/nfs_file_truncate.py
  tests/nfs/nfs_verify_stress.py
Labels: lgtm

#3699 Automation of - CEPH-83586116- Verify that the Mgr daemon is not marked lost and a connection is established post failures.
  ceph/rados/core_workflows.py
  ceph/rados/mgr_workflows.py
  suites/pacific/rados/tier-2_rados_test-mgr-daemon.yaml
  suites/quincy/rados/tier-2_rados_test-mgr-daemon.yaml
  suites/reef/rados/tier-2_rados_test-mgr-daemon.yaml
  suites/squid/rados/tier-2_rados_test-mgr-daemon.yaml
  tests/rados/test_mgr_daemon.py
Labels: RADOS, lgtm, Polarion testcase, Ready-for-review

#3793 Add ssl-upgrade from 7.1GA to 8.0 latest for single and multisite
  suites/squid/rgw/tier-1_rgw_ssl_multisite_test_upgrade_71GA_to_8x_latest.yaml
  suites/squid/rgw/tier-1_rgw_upgrade_ssl_71GA_to_8x_latest.yaml
Labels: pr-verified, RGW, Upgrade, Tier-1, lgtm

#3790 Add the Ratelimit Debt test to cephCI
  suites/reef/rgw/tier-2_rgw_test_using_s3cmd.yaml
  suites/squid/rgw/tier-2_rgw_test_using_s3cmd.yaml
Labels: RGW, lgtm

#3801 NVMe Baremetal pipeline fix
  pipeline/scripts/ci/server_setup_utils.sh
  suites/reef/baremetal/deploy/rh/nvme_cali_1admin_6node_2client.yaml
  tests/nvmeof/workflows/initiator.py
Labels: lgtm, nvmeof, baremetal

#3805 Updating jenkins agent for cleanup jobs
  pipeline/rhos_scripts/Jenkinsfile-cleanup-env.groovy
  pipeline/rhos_scripts/Jenkinsfile-quota.groovy
Labels: lgtm

#3804 Adding temporary fix for psi_remove_vm
  utility/psi_remove_vms.py
Labels: lgtm

#3813 TFA FIX - Inconsistent object pg check using pool snapshot
  tests/rados/test_osd_snap_inconsistency_pg.py
Labels: lgtm

#3807 [Squid][SMB][Mult-Connection]Add multi-connection support
  requirements.txt
  suites/squid/smb/tier-2-smb-multi-connections.yaml
  tests/smb/smb_client.py
  tests/smb/smb_load.py
  tests/smb/smb_multi_connection.py
Labels: lgtm, smb

#3809 Adding ephemral random pin validation, fragmentation during test,tar …
  suites/reef/cephfs/tier-1_cephfs_cg_quiesce.yaml
  suites/squid/cephfs/tier-1_cephfs_cg_quiesce.yaml
  tests/cephfs/cephfs_utilsV1.py
  tests/cephfs/snapshot_clone/cephfs_cg_io.py
  tests/cephfs/snapshot_clone/cg_snap_system_test.py
  tests/cephfs/snapshot_clone/cg_snap_test.py
  tests/cephfs/snapshot_clone/cg_snap_utils.py
Labels: lgtm

#3818 minor changes for nvme baremetal pipeline
  suites/reef/baremetal/deploy/rh/nvme_cali_1admin_6node_2client.yaml
  suites/reef/nvmeof/tier-3_2-nvmeof-gw_16-sub_ns.yaml
  suites/reef/nvmeof/tier-3_2-nvmeof-gw_2-sub_ns.yaml
  suites/reef/nvmeof/tier-3_2-nvmeof-gw_8-sub_ns.yaml
  suites/reef/nvmeof/tier-3_4-nvmeof-gw_16-sub_ns.yaml
  suites/reef/nvmeof/tier-3_4-nvmeof-gw_2-sub_ns.yaml
  suites/reef/nvmeof/tier-3_4-nvmeof-gw_8-sub_ns.yaml
  tests/nvmeof/test_io_perf.py
Labels: lgtm, nvmeof, baremetal

#3820 Changing the agent node for quota email
  pipeline/rhos_scripts/Jenkinsfile-cleanup-env.groovy
  pipeline/rhos_scripts/Jenkinsfile-quota.groovy
Labels: lgtm

#3770 Bug 2134786: Verify that no recovery occurs when norecover flag is set on the cluster
  suites/reef/rados/tier-2_rados_test-bugfixes.yaml
  tests/rados/test_norecovery_flag_functionality.py
Labels: RADOS, lgtm, Polarion testcase, bugzilla/severity-high, bugzilla/valid-bug

#3803 Rados Bugzilla automations and TFA fixes
  ceph/rados/core_workflows.py
  suites/pacific/rados/tier-2_rados_test-pool-functionalities.yaml
  suites/pacific/rados/tier-3_rados_test-location-stretch-mode.yaml
  suites/quincy/rados/tier-2_rados_test-pool-functionalities.yaml
  suites/quincy/rados/tier-3_rados_test-location-stretch-mode.yaml
  suites/reef/rados/tier-2_rados_test-pool-functionalities.yaml
  suites/reef/rados/tier-3_rados_test-location-stretch-mode.yaml
  suites/squid/rados/tier-2_rados_test-pool-functionalities.yaml
  suites/squid/rados/tier-3_rados_test-location-stretch-mode.yaml
  tests/rados/pool_tests.py
  tests/rados/test_osdmap_trim.py
  tests/rados/test_stretch_mon_replacements.py
  tests/rados/test_stretch_negative_scenarios.py
Labels: RADOS, lgtm

#3819 [TFA] Fix failure due to string comparison issue
  tests/cephadm/test_config.py
Labels: lgtm

#3802 Add the Ldap tests into CephCI
  suites/reef/rgw/tier-2_rgw_ldap_integration.yaml
  suites/reef/rgw/tier-2_rgw_regression_extended.yaml
  suites/squid/rgw/tier-2_rgw_ldap_integration.yaml
  suites/squid/rgw/tier-2_rgw_regression_extended.yaml
Labels: RGW, lgtm

#3786 TFA: Remove verify-io, as MS test cases are checked via a sync-status
  suites/reef/rgw/tier-1_rgw_ms_datalog_and_crash.yaml
  suites/squid/rgw/sanity_rgw_multisite.yaml
  suites/squid/rgw/tier-1_rgw_ms_datalog_and_crash.yaml
  suites/squid/upstream/tier-1-extn_rgw_multisite-secondary-to-primary.yaml
Labels: RGW, lgtm, tfa-issue-fix

#3798 cephci integration: CEPH-83573543: Verify lifecycle removes all the n…
  suites/pacific/rgw/tier-2_rgw_test-using-s3cmd.yaml
  suites/quincy/rgw/tier-2_rgw_regression_extended.yaml
  suites/reef/rgw/tier-2_rgw_regression_extended.yaml
  suites/squid/rgw/tier-2_rgw_regression_extended.yaml
Labels: pr-verified, RGW, lgtm, Tier-3, close-loop-automation

#3800 Adding ssl upgrade suites to reef
  suites/reef/rgw/tier-1_rgw_ssl_multisite_test_upgrade_71GA_to_71x_latest.yaml
  suites/reef/rgw/tier-1_rgw_upgrade_ssl_71GA_to_71x_latest.yaml
Labels: pr-verified, RGW, Upgrade, lgtm, Reef

#3823 Fix for cleaning up existing repos
  tests/cephadm/test_cephadm_upgrade.py
Labels: lgtm

#3806 [RADOS] TFA fix for osd_memory_target, enhancements to CBT-COT workflow
  ceph/rados/core_workflows.py
  tests/rados/monitor_configurations.py
  tests/rados/test_bluestoretool_workflows.py
  tests/rados/test_objectstoretool_workflows.py
  tests/rados/test_osd_memory_target.py
Labels: RADOS, lgtm, Ready-for-review, tfa-issue-fix

#3776 Test to automate Change and Reset peer ID and validate mirror pool status
  ceph/rbd/workflows/rbd_mirror.py
  suites/quincy/rbd/tier-2_rbd_mirror_image_operations.yaml
  suites/reef/rbd/tier-2_rbd_mirror_image_operations.yaml
  suites/squid/rbd/tier-2_rbd_mirror_image_operations.yaml
  tests/rbd_mirror/test_rbd_mirror_peer_id.py
Labels: RBD, lgtm, approved

#3816 [TFA][Fix]test_label_no_schedule
  suites/pacific/cephadm/tier-1-verify-no-schedule.yaml
  suites/pacific/cephadm/tier-1_service_apply_spec.yaml
Labels: lgtm

#3833 Fixing TFA issue
  conf/baremetal/mero1_1admin_4node_4client.yaml
  conf/baremetal/mero2_1admin_4node_4client.yaml
  tests/cephfs/cephfs_system/fill_cluster_full_del.py
  tests/cephfs/clients/mds_conf_modifying.py
Labels: lgtm

#3812 Adding polarion IDs and test case for multi node gateway failure scenarios
  suites/reef/nvmeof/tier-2_nvmeof_4nodes_gateway_ha_tests.yaml
Labels: lgtm

#3811 [NFS-Ganesha][Feature Automation] Test setting and deleting multiple …
  suites/squid/nfs/tier0-nfs-ganesha-vers-4-2.yaml
  tests/nfs/nfs_multiple_xattr_set_and_delete.py
  tests/nfs/nfs_operations.py
Labels: lgtm

#3830 [8.0][NF] CEPH-83590892: Automation coverage for Bluestore Superblock Redundancy
  suites/squid/rados/tier-2_rados_test_bluestore.yaml
  tests/rados/test_bluestore_superblock.py
Labels: RADOS, lgtm, Polarion testcase, Ready-for-review, 8.0

#3828 NVMeOF Add Host Method Included
  rest/common/config/config.json
  rest/endpoints/nvmeof/nvmeof.py
  rest/workflows/nvmeof/nvmeof.py
  tests/nvmeof/rest/test_nvmeof_rest_sanity.py
Labels: lgtm, approved

#3815 Automation of Online Reads Balancer via Balancer module
  ceph/rados/core_workflows.py
  suites/squid/rados/tier-2_rados_test-pool-functionalities.yaml
  tests/rados/test_online_reads_balancer.py
  tests/rados/test_reads_balancer.py
Labels: RADOS, lgtm, 7.1-bugs-automate, 8.0

#3824 New automation for BZ2245261
  suites/reef/cephfs/tier-2_cephfs_test-snapshot-clone.yaml
  suites/squid/cephfs/tier-2_cephfs_test-snapshot-clone.yaml
  tests/cephfs/snapshot_clone/snapshot_nfs_mount.py
Labels: lgtm

#3782 Changes to run stress test of 100 failovers
  suites/reef/nvmeof/tier-2_nvmeof_4nodes_gateway_ha_tests.yaml
  suites/reef/nvmeof/tier-3_nvmeof_stress_testing_bm.yaml
  tests/nvmeof/test_ceph_nvmeof_high_availability.py
  tests/nvmeof/workflows/ha.py
Labels: lgtm

#3838 minor cmd changes in scale test
  tests/nvmeof/test_ceph_nvmeof_gateway_sub_scale.py
Labels: lgtm, approved, baremetal

#3836 Adding test to failover and failback using power off and power on nodes
  suites/reef/nvmeof/tier-2_nvmeof_4nodes_gateway_ha_tests.yaml
  suites/squid/nvmeof/tier-2_nvmeof_4nodes_gateway_ha_tests.yaml
  tests/nvmeof/workflows/ha.py
Labels: lgtm
