Repository red-hat-storage/cephci, pull requests merged in 2024-09, with the labels that each got.

#4028 [Test] Validate RESTful operations
  api/exceptions.py
  suites/squid/cephmgr/tier2-restful-pool-endpoint.yaml
  tests/mgr/test_restful_operations_pool_endpoint.py
Labels: lgtm

#4049 [Config] Fix IBM Cloud inventories
  conf/inventory/ibm-vpc-rhel-8.10-minimal-bx2-2x8.yaml
  conf/inventory/ibm-vpc-rhel-8.10-minimal-bx2-4x16.yaml
  conf/inventory/ibm-vpc-rhel-8.5-minimal-amd64-1.yaml
  conf/inventory/ibm-vpc-rhel-8.6-minimal-amd64-1.yaml
  conf/inventory/ibm-vpc-rhel-8.7-minimal-amd64.yaml
  conf/inventory/ibm-vpc-rhel-8.8-minimal-bx2-2x8.yaml
  conf/inventory/ibm-vpc-rhel-8.8-minimal-bx2-4x16.yaml
  conf/inventory/ibm-vpc-rhel-9.0-minimal-amd64-1.yaml
  conf/inventory/ibm-vpc-rhel-9.1-minimal-amd64.yaml
  conf/inventory/ibm-vpc-rhel-9.2-minimal-bx2-2x8.yaml
  conf/inventory/ibm-vpc-rhel-9.2-minimal-bx2-4x16.yaml
  conf/inventory/ibm-vpc-rhel-9.4-minimal-bx2-2x8.yaml
  conf/inventory/ibm-vpc-rhel-9.4-minimal-bx2-4x16.yaml
Labels: lgtm, ibmc

#4047 [Squid][NFS-Ganesha] Add NFS HA suite for Squid
  suites/reef/nfs/tier1-nfs-ganesha-ha.yaml
  suites/squid/nfs/baremetal/tier1-nfs-ganesha-ha.yaml
Labels: lgtm

#4026 Adding cephfs-journal-tool event mode
  suites/quincy/cephfs/tier-4_cephfs_recovery.yaml
  suites/reef/cephfs/tier-4_cephfs_recovery.yaml
  suites/squid/cephfs/tier-4_cephfs_recovery.yaml
  tests/cephfs/cephfs_journal_tool/cephfs_journal_tool_event_mode.py
Labels: lgtm

#4033 New Automation for cephfs-top feature polarion test 83575020
  suites/quincy/cephfs/tier-3_cephfs_test_cephfs-top.yaml
  suites/reef/cephfs/tier-3_cephfs_test_cephfs-top.yaml
  suites/squid/cephfs/tier-3_cephfs_test_cephfs-top.yaml
  tests/cephfs/cephfs_top/cephfs_top_negative_tests.py
Labels: Ceph-FS, lgtm, Polarion testcase

#4051 Adding EC support generic suite
  tests/cephfs/ceph-83573462.py
  tests/cephfs/ceph_83574291.py
  tests/cephfs/mds_fail_with_rank.py
Labels: lgtm

#4045 [Test] Validate RESTful operations on OSD endpoint
  api/restful/osd.py
  suites/squid/cephmgr/tier2-restful-endpoint-operations.yaml
  tests/mgr/test_restful_operations_osd_endpoint.py
Labels: lgtm, CephMgr

#4053 NVMeoF-8.0 Build to Build test suite.
  suites/squid/nvmeof/tier-2_nvmeof_b2b_upgrade.yaml
  tests/nvmeof/test_ceph_nvmeof_upgrade.py
Labels: Upgrade, lgtm, nvmeof, squid, 8.0

#4058 Adding mds_journal_value_conf_verification file
  tests/cephfs/clients/mds_journal_value_conf_verification.py
Labels: lgtm

#4038 CEPH-83595766: Tier-3 test to verify BlueFS spillover health warning
  ceph/rados/serviceability_workflows.py
  suites/pacific/rados/tier-2_rados_test_cot_cbt.yaml
  suites/quincy/rados/tier-2_rados_test_cot_cbt.yaml
  suites/reef/rados/tier-2_rados_test_cot_cbt.yaml
  suites/squid/rados/tier-2_rados_test_cot_cbt.yaml
  tests/rados/test_bluestoretool_workflows.py
Labels: RADOS, lgtm, Tier-3, Polarion testcase, 7.0-bugs-automate

#4066 Updating rhcs deploy script to use xlarge config files
  pipeline/rhcs_deploy.groovy
Labels: lgtm

#4057 Adding EC Support for tier-3_fs
  tests/cephfs/CEPH-11238.py
  tests/cephfs/clients/client_option_value_verification.py
  tests/cephfs/osd_add_rm_FS_IO.py
Labels: lgtm

#4068 TFA fix for BZ2284364 and BZ2273569
  suites/squid/cephfs/tier-1_cephfs_cg_quiesce.yaml
  tests/cephfs/snapshot_clone/cephfs_cg_io.py
  tests/cephfs/snapshot_clone/cg_snap_test.py
Labels: lgtm

#4069 Updated RBD squid test suites for upgrade tests
  suites/squid/rbd/tier-2_rbd_upgrade_6x_to_8x.yaml
  suites/squid/rbd/tier-2_rbd_upgrade_7x_to_8x.yaml
  suites/squid/rbd/tier-3_rbd_mirror_upgrade_6x_to_8x_scale.yaml
  suites/squid/rbd/tier-3_rbd_mirror_upgrade_7x_to_8x_scale.yaml
Labels: RBD, lgtm

#4072 [Squid][SMB][Automation]Clustering support
  conf/squid/smb/1admin-4node-1client-cluster.yaml
  suites/squid/smb/tier-1-smb-ctdb-clustering.yaml
  tests/smb/smb_deployment_declarative_method.py
  tests/smb/smb_deployment_imperative_method.py
  tests/smb/smb_operations.py
Labels: lgtm, smb

#4063 TFA-issue fix - Preempt scrub fix
  tests/rados/test_rados_preempt_scrub.py
Labels: RADOS, lgtm, tfa-issue-fix

#4080 Enhance crash module to archive existing crashes & max avail added for OSD out
  ceph/rados/core_workflows.py
  tests/rados/test_osd_rebalance.py
Labels: RADOS, lgtm, Ready-for-review, tfa-issue-fix

#4079 [Test][CephMgr] Add test to verify crash post mgr fail
  cli/ceph/orch/host.py
  suites/reef/cephadm/tier1-remove-cluster.yaml
  suites/squid/cephadm/tier1-remove-cluster.yaml
  tests/mgr/test_cephmgr_crash_after_mgr_fail.py
Labels: Tier-1, lgtm, CephAdm, CephMgr

#4081 [Squid][SMB][Clustering]Add support for public address
  suites/squid/smb/baremetal/tier-1-smb-ctdb-clustering-vip.yaml
  tests/smb/smb_clients_operations.py
  tests/smb/smb_deployment_declarative_method.py
  tests/smb/smb_operations.py
Labels: lgtm, smb

#4048 Remove known issue BZ2302940 since BZ is verified
  suites/pacific/rgw/tier-2_rgw_regression.yaml
  suites/pacific/rgw/tier-2_rgw_test-lc-prefix.yaml
  suites/quincy/rgw/tier-2_rgw_ms_test-bucket-notifications.yaml
  suites/reef/rgw/tier-2_rgw_test_lifecycle.yaml
  suites/squid/rgw/sanity_rgw.yaml
  suites/squid/rgw/sanity_rgw_multisite.yaml
  suites/squid/rgw/tier-2_rgw_ms_archive_with_haproxy.yaml
  suites/squid/rgw/tier-2_rgw_regression_extended.yaml
  suites/squid/rgw/tier-2_rgw_regression_test.yaml
  suites/squid/rgw/tier-2_rgw_test_lifecycle.yaml
Labels: RGW, lgtm, tfa-issue-fix

#4065 Adding EC Support for cephfs_perf
  tests/cephfs/cephfs_perf/cephfs_io_read_write_from_diff_clients.py
  tests/cephfs/cephfs_perf/cephfs_io_read_write_from_multiple_clients.py
  tests/cephfs/cephfs_perf/cephfs_stress_io_from_multiple_clients.py
  tests/cephfs/cephfs_perf/fuse_kernel_performance.py
Labels: lgtm

#4067 Adding cephfs-top dump testing
  suites/quincy/cephfs/tier-3_cephfs_test_cephfs-top.yaml
  suites/reef/cephfs/tier-3_cephfs_test_cephfs-top.yaml
  suites/squid/cephfs/tier-3_cephfs_test_cephfs-top.yaml
  tests/cephfs/cephfs_top/cephfs_top_dump.py
  tests/cephfs/cephfs_utilsV1.py
Labels: lgtm

#4056 CephFS Test Gaps Automation - Selinux Functional Tests
  suites/quincy/cephfs/tier-2_cephfs_test-clients.yaml
  suites/reef/cephfs/tier-2_cephfs_test-clients.yaml
  suites/squid/cephfs/tier-2_cephfs_test-clients.yaml
  tests/cephfs/clients/test_selinux_relabel.py
Labels: Ceph-FS, lgtm, Test Gaps

#4064 DMFG baremetal deploy cluster suites updated
  suites/reef/baremetal/deploy/rh/dmfg_clara_1admin_5node_2client.yaml
  suites/squid/baremetal/deploy/rh/dmfg_clara_1admin_5node_2client.yaml
Labels: lgtm

#4074 Adding ec profile test cases to mero1 and mero2 deploy suites
  suites/squid/baremetal/deploy/rh/mero1_1admin_4node_4client.yaml
  suites/squid/baremetal/deploy/rh/mero2_1admin_4node_4client.yaml
Labels: lgtm

#4078 Adding EC support for recovery suite
  suites/quincy/cephfs/tier-4_cephfs_recovery.yaml
  suites/reef/cephfs/tier-4_cephfs_recovery.yaml
  suites/squid/cephfs/tier-4_cephfs_recovery.yaml
  tests/cephfs/cephfs_generic/test_data_migrate_bw_buckets.py
  tests/cephfs/cephfs_journal_tool/cephfs_journal_tool_event_mode.py
  tests/cephfs/cephfs_journal_tool/cephfs_journal_tool_header_mode.py
  tests/cephfs/cephfs_journal_tool/cephfs_journal_tool_journal_mode.py
  tests/cephfs/cephfs_recovery/fs_down_flag.py
  tests/cephfs/cephfs_recovery/fs_scrub.py
Labels: lgtm

#4062 CEPH-83595780: Tier-2 test to verify max_avail value updation upon OSD size change
  ceph/rados/core_workflows.py
  ceph/rados/serviceability_workflows.py
  suites/reef/rados/tier-4_rados_tests.yaml
  suites/squid/rados/tier-4_rados_tests.yaml
  tests/rados/test_cephdf.py
Labels: RADOS, lgtm, Tier-2, Polarion testcase

#4073 Add support for selected client upgrade, multiple client and reuse of existing mount after upgrade
  suites/squid/cephfs/tier-0_cephfs_upgrade_6x_to_8x.yaml
  suites/squid/cephfs/tier-0_cephfs_upgrade_71_to_8x.yaml
  suites/squid/cephfs/tier-0_cephfs_upgrade_7x_to_8x.yaml
  suites/squid/cephfs/tier-0_cephfs_upgrade_ibm_6x_to_8x.yaml
  tests/cephfs/cephfs_upgrade/cephfs_io.py
  tests/cephfs/cephfs_upgrade/cephfs_post_upgrade_validation.py
  tests/cephfs/cephfs_upgrade/upgrade_pre_req.py
Labels: lgtm

#4085 Include change-load-balancing-group test
  suites/reef/nvmeof/tier-2_nvmeof_gateway_operations.yaml
  suites/squid/nvmeof/tier-2_nvmeof_gateway_operations.yaml
Labels: lgtm, nvmeof

#4043 integrating sts aswi with isv tests into cephci
  suites/reef/rgw/tier-2_rgw_sts_aswi.yaml
  suites/squid/rgw/tier-2_rgw_sts_aswi.yaml
Labels: pr-verified, RGW, Tier-1, lgtm, early-automation, 8.0

#4075 [TFA-Fix] fixing tfa issues seen in RGW runs
  suites/reef/rgw/migrate_default_single_to_multisite.yaml
  suites/reef/rgw/tier-2_rgw_regression_extended.yaml
  suites/reef/rgw/tier-2_rgw_singlesite_to_multisite.yaml
  suites/squid/rgw/migrate_default_single_to_multisite.yaml
  suites/squid/rgw/tier-1_rgw_ms_upgrade_61GA_to_8x_latest.yaml
  suites/squid/rgw/tier-2_rgw_3_way_multisite.yaml
  suites/squid/rgw/tier-2_rgw_ms_archive_with_haproxy.yaml
  suites/squid/rgw/tier-2_rgw_regression_extended.yaml
  suites/squid/rgw/tier-2_rgw_singlesite_to_multisite.yaml
  suites/squid/rgw/tier-3_archive_zone_colocate_data_zone.yaml
Labels: pr-verified, RGW, lgtm, tfa-issue-fix

#4092 fs suite syntax error
  suites/reef/cephfs/tier-2_cephfs_test-clients.yaml
  suites/squid/cephfs/tier-2_cephfs_test-clients.yaml
Labels: Ceph-FS, lgtm

#4094 Updating mero2 client nodes to clara nodes
  conf/baremetal/mero2_1admin_4node_4client.yaml
Labels: lgtm

#4059 [Test] Validate the /config endpoint of RESTful module
  api/restful/config.py
  suites/squid/cephmgr/tier2-restful-endpoint-operations.yaml
  tests/mgr/test_restful_operations_config_endpoint.py
Labels: lgtm

#4082 [TFA] Mero node change from mero007 to mero013
  conf/baremetal/mero_multisite_1admin_3node_along_client.yaml
  suites/reef/baremetal/deploy/rh/mero_multisite_1admin_3node_along_client.yaml
  suites/reef/rgw/baremetal/mero_scale_rgw_multi_site.yaml
  suites/squid/baremetal/deploy/rh/mero_multisite_1admin_3node_along_client.yaml
  suites/squid/rgw/baremetal/mero_scale_rgw_multi_site.yaml
Labels: RGW, lgtm, tfa-issue-fix, baremetal

#4083 New Automation for Client Caps Validation, Polarion TC - CEPH-83597462
  suites/quincy/cephfs/tier-2_cephfs_test-clients.yaml
  suites/reef/cephfs/tier-2_cephfs_test-clients.yaml
  suites/squid/cephfs/tier-2_cephfs_test-clients.yaml
  tests/cephfs/clients/client_caps_update_validation.py
Labels: lgtm

#4052 Changes for multi-GW group
  ceph/nvmegw_cli/gateway.py
  conf/squid/nvmeof/ceph_nvmeof_4-nvmeof-gwgroup_2gw_cluster.yaml
  conf/squid/nvmeof/ceph_nvmeof_4-nvmeof-gwgroup_8gw_cluster.yaml
  suites/squid/nvmeof/tier-1_nvmeof_4-nvmeof-gwgroup_2gw_cluster.yaml
  suites/squid/nvmeof/tier-3_nvmeof_4gwgroup_8gw_cluster.yaml
  tests/nvmeof/test_nvmeof_gwgroup.py
  tests/nvmeof/workflows/ha.py
  tests/nvmeof/workflows/nvme_utils.py
Labels: lgtm, nvmeof, 8.0

#4061 Adding FS TC 83573838
  suites/quincy/cephfs/tier-3_cephfs_test_cephfs-top.yaml
  suites/reef/cephfs/tier-3_cephfs_test_cephfs-top.yaml
  suites/squid/cephfs/tier-3_cephfs_test_cephfs-top.yaml
  tests/cephfs/cephfs_top/validate_fs_top_stats.py
Labels: lgtm

#4095 Adding parallel IOs to mirror suite
  suites/reef/cephfs/tier-0_cephfs_mirrror_upgrade_6x_to_7x.yaml
  suites/squid/cephfs/tier-0_cephfs_mirrror_upgrade_6x_to_8x.yaml
  suites/squid/cephfs/tier-0_cephfs_mirrror_upgrade_7x_to_8x.yaml
  suites/squid/cephfs/tier-0_cephfs_mirrror_upgrade_ibm_6x_to_8x.yaml
  suites/squid/cephfs/tier-0_cephfs_mirrror_upgrade_ibm_7x_to_8x.yaml
Labels: lgtm

#4097 [Test] Validate /crush/rule RESTful endpoint
  api/restful/crush.py
  suites/squid/cephmgr/tier2-restful-endpoint-operations.yaml
  tests/mgr/test_restful_operations_crush_endpoint.py
Labels: lgtm

#4088 [Squid][NFS-Ganesha] Test extended attributes with rootsquash user
  suites/squid/nfs/tier0-nfs-ganesha-vers-4-2.yaml
  tests/nfs/nfs_multi_mount_version_4x.py
  tests/nfs/test_nfs_extended_attribute_rootsquash.py
Labels: lgtm

#4096 [Squid][SMB][Automation]Add failover scenarios
  suites/squid/smb/baremetal/tier-1-smb-ctdb-clustering-vip.yaml
  tests/smb/smb_failover_file_ops.py
  tests/smb/smb_operations.py
Labels: lgtm, smb

#4091 Remove default tier-0 build type
  pipeline/rhcs_deploy.groovy
Labels: lgtm

#4087 [Test] Validate /perf endpoint of RESTful module
  api/restful/perf.py
  suites/squid/cephmgr/tier2-restful-endpoint-operations.yaml
  tests/mgr/test_restful_operations_perf_endpoint.py
Labels: lgtm

#4102 Enable debug logs in CG quiesce functional for reef
  suites/reef/cephfs/tier-1_cephfs_cg_quiesce.yaml
Labels: lgtm

#4098 [TFA] updating indentation for testcase of parallel run
  suites/squid/rgw/tier-2_rgw_ms_upgrade_8xsanity_to_8xlatest.yaml
  suites/squid/rgw/tier-2_rgw_upgrade_8xsanity_to_8xlatest.yaml
Labels: RGW, Upgrade, lgtm, tfa-issue-fix

#4107 [TFA] Remove extensa and update mero
  suites/reef/baremetal/deploy/rh/extensa_clara_multisite_1admin_4node_1client.yaml
  suites/reef/baremetal/deploy/rh/mero_multisite_1admin_3node_along_client.yaml
  suites/reef/baremetal/io/rh/extensa_clara_multisite_1admin_4node_1client.yaml
  suites/reef/rgw/baremetal/scale_rgw_multi_site.yaml
  suites/squid/baremetal/deploy/rh/extensa_clara_multisite_1admin_4node_1client.yaml
  suites/squid/baremetal/deploy/rh/mero_multisite_1admin_3node_along_client.yaml
  suites/squid/baremetal/io/rh/extensa_clara_multisite_1admin_4node_1client.yaml
  suites/squid/baremetal/upgrade/rh/extensa_clara_multisite_1admin_4node_1client.yaml
  suites/squid/rgw/baremetal/scale_rgw_multi_site.yaml
Labels: RGW, lgtm, tfa-issue-fix, baremetal

#4108 Adding allow-overwrite flag to suite file
  suites/reef/integrations/ocs_rgw_ssl_vsphere.yaml
Labels: lgtm

#4007 TFA FIX- Scheduled scrub and Inconsistent object in EC pool
  ceph/rados/core_workflows.py
  suites/quincy/rados/tier-2_rados_test-scrubbing.yaml
  suites/reef/rados/tier-2_rados_test-scrubbing.yaml
  suites/squid/rados/tier-2_rados_test-scrubbing.yaml
  tests/rados/scheduled_scrub_scenarios.py
  tests/rados/test_osd_ecpool_inconsistency_scenario.py
Labels: RADOS, lgtm, Ready-for-review, tfa-issue-fix

#4042 Adding EC support for Clients suite
  tests/cephfs/cephfs_utils.py
  tests/cephfs/cephfs_utilsV1.py
  tests/cephfs/clients/MDS_failover_while_client_IO.py
  tests/cephfs/clients/ceph_auth_caps_modifying_permissions.py
  tests/cephfs/clients/client_evict.py
  tests/cephfs/clients/client_fstab_auto_mount.py
  tests/cephfs/clients/create_user_with_permissions.py
  tests/cephfs/clients/cross_delete_ops_bw_fuse_and_kernel_clients.py
  tests/cephfs/clients/file_lock_on_mounts.py
  tests/cephfs/clients/file_unlink_on_clients.py
  tests/cephfs/clients/fs_basic_bash_cmds.py
  tests/cephfs/clients/integrity_check_after_remount.py
  tests/cephfs/clients/mds_conf_modifying.py
  tests/cephfs/clients/mds_journal_value_conf_verification.py
  tests/cephfs/clients/mds_scrub_after_failover.py
  tests/cephfs/clients/multiclient_cephx_restrict_fs.py
  tests/cephfs/clients/multiclient_file_dir_ops.py
  tests/cephfs/clients/multiclients_io_on_same_directory.py
  tests/cephfs/clients/multiple_clients_permission_mounted_directories.py
  tests/cephfs/clients/multiple_clients_posix_calls.py
  tests/cephfs/clients/rsync_bw_fs_and_other_location.py
  tests/cephfs/clients/smallfiles_with_different_operations.py
  tests/cephfs/clients/validate_root_squash.py
  tests/cephfs/clients/verify_root_squash_in_caps.py
  tests/cephfs/clients/verify_user_read_write_permissions.py
Labels: lgtm

#4112 Fixing cephfs bug suite file
  suites/quincy/cephfs/tier-3_cephfs_bugs.yaml
  suites/reef/cephfs/tier-3_cephfs_bugs.yaml
  suites/squid/cephfs/tier-3_cephfs_bugs.yaml
Labels: lgtm

#4103 fix reef gateway operations test suite
  suites/reef/nvmeof/tier-2_nvmeof_functional_Regression.yaml
  suites/reef/nvmeof/tier-2_nvmeof_gateway_operations.yaml
  tests/nvmeof/test_ceph_nvmeof_data_integrity.py
Labels: lgtm, nvmeof, Reef

#4070 Adding EC Support for Scale suite
  tests/cephfs/cephfs_scale/max_clones_from_snap.py
  tests/cephfs/cephfs_scale/max_smallfile_snap.py
  tests/cephfs/cephfs_scale/max_snapshots.py
  tests/cephfs/cephfs_scale/max_snapshots_single_volume.py
  tests/cephfs/cephfs_scale/max_subvolumes.py
  tests/cephfs/cephfs_scale/max_svg_sv.py
Labels: lgtm

#4110 TFA fix for read op exit and snap cmd errors
  tests/cephfs/snapshot_clone/cephfs_cg_io.py
  tests/cephfs/snapshot_clone/cg_snap_test.py
Labels: lgtm, tfa-issue-fix

#4111 fix subsystem NQN for 8.0
  suites/squid/nvmeof/tier-2_nvmeof_gateway_operations.yaml
  tests/nvmeof/test_ceph_nvmeof_data_integrity.py
  tests/nvmeof/test_ceph_nvmeof_gateway.py
  tests/nvmeof/test_ceph_nvmeof_high_availability.py
Labels: lgtm

#4105 Adding EC support for quiesce suite
  tests/cephfs/snapshot_clone/cephfs_cg_io.py
  tests/cephfs/snapshot_clone/cg_snap_test.py
Labels: lgtm

#4114 Changes to fix subsystem NQN
  suites/squid/nvmeof/tier-2_nvmeof_gateway_operations.yaml
Labels: lgtm

#4116 Moving radosbench shell executions to long running
  ceph/rados/core_workflows.py
  ceph/rados/rados_bench.py
  suites/squid/rados/tier-2_rados_test-clay-ecpool.yaml
  suites/squid/rados/tier-2_rados_test-pool-functionalities.yaml
  tests/rados/test_bluestoretool_workflows.py
  tests/rados/test_cephdf.py
Labels: RADOS, Workaround, lgtm

#4100 NVMeOf - test suite for 8GW in a single GWgroup with n-1 failures using daemon and systemctl fail method
  suites/squid/nvmeof/tier-2_nvmeof_1gwgroup_8gwnodes_ha_tests.yaml
Labels: lgtm, nvmeof, 8.0

#4106 NVMeOF 8.0 Greenfield scale 4 GW groups with 2GWs 1024 NS 128 Sub each
  conf/squid/nvmeof/ceph_nvmeof_4-group_2-gws_scale.yaml
  suites/squid/nvmeof/tier-3_4-group_2-gw_128-sub_1024-NS.yaml
  tests/nvmeof/test_ceph_nvmeof_gateway_sub_scale.py
Labels: lgtm, nvmeof, 8.0

#4089 cephci integration of support to add placement and storageclass durin…
  suites/reef/rgw/tier-2_rgw_regression_extended.yaml
  suites/squid/rgw/tier-2_rgw_regression_extended.yaml
Labels: enhancement, pr-verified, RGW, lgtm, Tier-2

#4109 Adding EC support for mds_pinning
  tests/cephfs/cephfs_mds_pinning/map_and_unmap_directory_trees_to_a_mds_rank.py
  tests/cephfs/cephfs_mds_pinning/mds_pinning_equal_dir_on_two_mdss.py
  tests/cephfs/cephfs_mds_pinning/mds_pinning_load_balancing.py
  tests/cephfs/cephfs_mds_pinning/mds_pinning_max_min_dir_on_two_mdss.py
  tests/cephfs/cephfs_mds_pinning/mds_pinning_node_reboots.py
  tests/cephfs/cephfs_mds_pinning/mds_pinning_split_merge.py
  tests/cephfs/cephfs_mds_pinning/mds_pinning_unequal_dir_on_two_mdss.py
  tests/cephfs/cephfs_utils.py
  tests/cephfs/cephfs_utilsV1.py
Labels: lgtm

#4115 Adding EC support for fs_bugs suite
  tests/cephfs/cephfs_bugs/test_cephfs_pool_size_change.py
  tests/cephfs/cephfs_bugs/test_clone_delete_with_FS_fail.py
  tests/cephfs/cephfs_bugs/test_create_unlink_ops_concorrently.py
  tests/cephfs/cephfs_bugs/test_custom_fscid_cephfs.py
  tests/cephfs/cephfs_bugs/test_disallow_fs_creation_with_pool_level_snaps.py
  tests/cephfs/cephfs_bugs/test_fsstress_on_kernel_and_fuse.py
  tests/cephfs/cephfs_bugs/test_large_omap.py
  tests/cephfs/cephfs_bugs/test_mds_inject_health_dummy.py
  tests/cephfs/cephfs_bugs/test_mds_laggy_thrown_out.py
  tests/cephfs/cephfs_bugs/test_rm_on_lost_found_dir.py
  tests/cephfs/cephfs_bugs/test_validate_deadlock_bw_unlink_and_rename.py
  tests/cephfs/cephfs_bugs/test_write_fsync_on_file_kernel_mount.py
  tests/cephfs/cephfs_bugs/validate_ceph_ops_wtih_fs_fail.py
  tests/cephfs/cephfs_bugs/validate_mds_health_with_client_evict.py
  tests/cephfs/cephfs_bugs/validate_mds_metadata.py
  tests/cephfs/cephfs_bugs/verify_race_condition_between_MDS.py
Labels: lgtm

#4113 RHCEPHQE-16103: exec_command hangs when there is no read/write
  ceph/ceph.py
  ceph/ceph_admin/helper.py
  ceph/ceph_admin/shell.py
  tests/ceph_installer/test_cephadm.py
Labels: framework, lgtm

#4120 Fix failures observed due to exec_command changes
  ceph/ceph.py
Labels: lgtm, approved

#4121 Support for mtls in GWgroup
  suites/reef/nvmeof/tier-2_nvmeof_4nodes_gateway_ha_tests.yaml
  suites/squid/nvmeof/tier-1_nvmeof_4-nvmeof-gwgroup_2gw_cluster.yaml
  suites/squid/nvmeof/tier-2_nvmeof_1gwgroup_8gwnodes_ha_tests.yaml
  suites/squid/nvmeof/tier-2_nvmeof_4nodes_gateway_ha_tests.yaml
  tests/nvmeof/test_ceph_nvmeof_data_integrity.py
  tests/nvmeof/test_ceph_nvmeof_gateway.py
  tests/nvmeof/test_ceph_nvmeof_high_availability.py
  tests/nvmeof/test_nvmeof_gwgroup.py
  tests/nvmeof/workflows/ha.py
Labels: lgtm, nvmeof, 8.0

#4123 Changes to support redeploy HA method
  suites/squid/nvmeof/tier-2_nvmeof_1gwgroup_8gwnodes_ha_tests.yaml
  tests/nvmeof/workflows/ha.py
Labels: lgtm

#4118 [TFA] include testcase update for known issues and increase upgrade monitor interval
  ceph/ceph_admin/upgrade.py
  suites/reef/baremetal/deploy/rh/mero_multisite_1admin_3node_along_client.yaml
  suites/reef/rgw/baremetal/mero_scale_rgw_multi_site.yaml
  suites/reef/rgw/tier-1_rgw_ms_upgrade_7_0GA_to_7x_latest.yaml
  suites/reef/rgw/tier-2_rgw_ms_regression_test.yaml
  suites/reef/rgw/tier-4-rgw.yaml
  suites/squid/baremetal/deploy/rh/mero_multisite_1admin_3node_along_client.yaml
  suites/squid/rgw/baremetal/mero_scale_rgw_multi_site.yaml
  suites/squid/rgw/tier-1_rgw_ms_upgrade_71GA_to_8x_latest.yaml
  suites/squid/rgw/tier-2_rgw_ms_regression_test.yaml
  suites/squid/rgw/tier-4-rgw.yaml
Labels: RGW, Upgrade, lgtm, tfa-issue-fix, baremetal

#4084 [Test] Validate the /mon endpoint of RESTful module
  api/restful/mon.py
  suites/squid/cephmgr/tier2-restful-endpoint-operations.yaml
  tests/mgr/test_restful_operations_mon_endpoint.py
Labels: lgtm

#4122 Fixing suite file for FS
  suites/squid/cephfs/tier-3_cephfs_bugs.yaml
Labels: lgtm

#4125 changing the names and creating new files for secure rgw deployment
  suites/reef/integrations/ocs_rgw_with_ssl_vsphere.yaml
  suites/reef/integrations/ocs_rgw_without_ssl_vsphere.yaml
Labels: lgtm

#4127 Fixing mail error for quota and cleanup
  pipeline/vars/node_bootstrap.bash
  utility/psi_quota.py
Labels: bug in framework, lgtm

#4130 [Squid][NFS-Ganesha][NFS v4.2] Add NFS HA suite for Squid NFS v4.2
  suites/squid/nfs/baremetal/tier1-nfs-ganesha-ha-v4_2.yaml
Labels: lgtm

#4134 [Squid][Samba] Update client operation module
  requirements.txt
  tests/smb/smb_client.py
  tests/smb/smb_load.py
Labels: lgtm, smb

#4101 Support for parallel executon of multi GWgroups
  conf/squid/nvmeof/ceph_nvmeof_4-nvmeof-gwgroup_2gw_cluster.yaml
  suites/squid/nvmeof/tier-1_nvmeof_4-nvmeof-gwgroup_2gw_tests.yaml
  tests/nvmeof/test_nvmeof_gwgroup.py
Labels: lgtm, nvmeof, 8.0

#4131 NVMeOF 8.0 Greenfield scale 4 GW groups with 8GWs 1024 NS 128 Sub each
  suites/squid/nvmeof/tier-3_4-group_8-gw_128-sub_1024-NS.yaml
Labels: lgtm, nvmeof, 8.0

#4136 Modifying the script to incorporate dev changes
  tests/cephfs/clients/mds_conf_modifying.py
Labels: lgtm

#4099 Adding cephfs-top initiate testing
  suites/quincy/cephfs/tier-3_cephfs_test_cephfs-top.yaml
  suites/reef/cephfs/tier-3_cephfs_test_cephfs-top.yaml
  suites/squid/cephfs/tier-3_cephfs_test_cephfs-top.yaml
  tests/cephfs/cephfs_top/cephfs_top_initiate.py
Labels: lgtm

#4126 kernel verification enchancement
  suites/pacific/cephfs/kernel_post_verification.yaml
  suites/quincy/cephfs/kernel_post_verification.yaml
  suites/reef/cephfs/kernel_post_verification.yaml
  suites/squid/cephfs/kernel_post_verification.yaml
  tests/cephfs/kernel_update.py
Labels: lgtm

#4129 Add wait time for FS_Degraded state to auto-resolve in 30secs
  tests/cephfs/snapshot_clone/cephfs_cg_io.py
Labels: lgtm

#4132 CephFS-Mirror- CEPH-83598968 - Validate the snapshot synchronisation …
  suites/quincy/cephfs/tier-1_cephfs_mirror.yaml
  suites/reef/cephfs/tier-1_cephfs_mirror.yaml
  suites/squid/cephfs/tier-1_cephfs_mirror.yaml
  tests/cephfs/cephfs_mirroring/test_cephfs_mirroring_with_snap_schedule.py
  tests/cephfs/snapshot_clone/cephfs_snap_utils.py
Labels: Ceph-FS, Tier-1, lgtm

#4137 Changes to support different RBD pools with GWgroup
  ceph/nvmegw_cli/execute.py
  conf/squid/nvmeof/ceph_nvmeof_4-nvmeof-gwgroup_2gw_cluster.yaml
  suites/squid/nvmeof/tier-1_nvmeof_4-nvmeof-gwgroup_2gw_tests.yaml
  tests/nvmeof/test_nvmeof_gwgroup.py
Labels: lgtm, nvmeof, 8.0
