Repository red-hat-storage/cephci, pull requests merged in 2024-11, with the labels that each got.

#4194 Adding TC 83600860
  suites/quincy/cephfs/tier-2_cephfs_test-snapshot-clone.yaml
  suites/reef/cephfs/tier-2_cephfs_test-snapshot-clone.yaml
  suites/squid/cephfs/tier-2_cephfs_test-snapshot-clone.yaml
  tests/cephfs/snapshot_clone/snap_schedule_with_mds_restart.py
Labels: lgtm

#4199 TFA fix for 3 cg quiesce functional failures
  tests/cephfs/snapshot_clone/cephfs_cg_io.py
  tests/cephfs/snapshot_clone/cg_snap_test.py
  tests/cephfs/snapshot_clone/cg_snap_utils.py
Labels: Ceph-FS, lgtm, tfa-issue-fix

#4197 [RADOS] Enable Bluestore Superblock Redundnacy test | Fix test_bluefs_space test case
  ceph/rados/pool_workflows.py
  suites/squid/rados/tier-2_rados_test_bluestore.yaml
  suites/squid/rados/tier-2_rados_test_omap.yaml
  tests/rados/monitor_configurations.py
  tests/rados/test_bluefs_space.py
  tests/rados/test_bluestore_superblock.py
Labels: RADOS, lgtm, tfa-issue-fix, 8.0

#4202 Fixing import issue
  tests/cephfs/cephfs_nfs/nfs_multiple_export_using_single_conf.py
Labels: lgtm

#4191 Damaging file system for cephfs-journal-tool
  tests/cephfs/cephfs_journal_tool/cephfs_journal_tool_header_mode.py
  tests/cephfs/cephfs_journal_tool/cephfs_journal_tool_journal_mode.py
  tests/cephfs/cephfs_utilsV1.py
Labels: lgtm

#4201 Merging suites with common conf
  suites/quincy/cephfs/tier-2_cephfs_test-clients.yaml
  suites/quincy/cephfs/tier-2_fs_mutlifs_quota_snaphost.yaml
  suites/reef/cephfs/tier-2_cephfs_test-clients.yaml
  suites/reef/cephfs/tier-2_fs_mutlifs_quota_snaphost.yaml
  suites/squid/cephfs/tier-2_cephfs_test-clients.yaml
  suites/squid/cephfs/tier-2_fs_mutlifs_quota_snaphost.yaml
  tests/cephfs/snapshot_clone/snap_schedule_with_mds_restart.py
Labels: lgtm

#4208 Updating default timeout of long-running command.
  tests/misc_env/install_prereq.py
Labels: lgtm

#4204 Merging suites with conf tier-2_cephfs_9-node-cluster
  suites/quincy/cephfs/teir-2_file-dir-lay_vol-mgmt_nfs.yaml
  suites/reef/cephfs/teir-2_file-dir-lay_vol-mgmt_nfs.yaml
  suites/squid/cephfs/teir-2_file-dir-lay_vol-mgmt_nfs.yaml
  tests/cephfs/cephfs_nfs/nfs_export_path.py
Labels: lgtm

#4200 [Squid][NFS-Ganesha] Add windows client test suite for Squid
  suites/squid/nfs/baremetal/tier1-nfs-ganesha-ha-windows.yaml
  suites/squid/nfs/baremetal/tier1-nfs-ganesha-windows-clients.yaml
Labels: lgtm

#4203 Adding support for enabling logs
  tests/cephfs/cephfs_utilsV1.py
Labels: lgtm

#4215 adding kernel log when it ends
  tests/cephfs/xfs_test.py
Labels: lgtm

#4205 [Test] Test disconnected upgrade from RHCS 7.x to RHCS 8
  suites/squid/upgrades/tier2-disconnected-upgrade-rhcs-7x-to-8x.yaml
  tests/ceph_installer/test_disconnected_install.py
  tests/ceph_installer/test_disconnected_upgrade.py
Labels: lgtm

#4212 [tfa] Rearranging the testcase version id null
  suites/pacific/rgw/tier-1_rgw_ms-bucket-listing-versioning-on-secondary.yaml
  suites/reef/rgw/tier-2_rgw_ms_regression_test.yaml
  suites/squid/rgw/tier-2_rgw_ms_regression_test.yaml
Labels: pr-verified, RGW, lgtm, tfa-issue-fix

#4213 [TFA] Update known issue and timeout for testcase execution
  suites/reef/rgw/baremetal/scale_rgw_single_site.yaml
  suites/reef/rgw/migrate_default_single_to_multisite.yaml
  suites/reef/rgw/tier-2_rgw_ms_archive_with_haproxy.yaml
  suites/squid/rgw/baremetal/scale_rgw_single_site.yaml
  suites/squid/rgw/migrate_default_single_to_multisite.yaml
  suites/squid/rgw/tier-2_rgw_ms_archive_with_haproxy.yaml
  suites/squid/rgw/tier-2_rgw_test_bucket_notifications.yaml
Labels: pr-verified, RGW, lgtm, tfa-issue-fix

#4207 [Test] Validate disconnected upgrade from RHCS 6.x to RHCS 8
  suites/squid/upgrades/tier2-disconnected-upgrade-rhcs-6x-to-8x.yaml
Labels: lgtm

#4217 RHCEPHQE-16694:[RADOS] TFA fix for crash module, max avail check, PG ID listing
  ceph/rados/core_workflows.py
  ceph/rados/utils.py
  suites/pacific/rados/tier-2_rados_test_omap.yaml
  suites/pacific/rados/tier-2_rados_trim_tests.yaml
  suites/pacific/rados/tier-3_rados_test-location-stretch-mode.yaml
  suites/quincy/rados/tier-2_rados_test_bluestore.yaml
  suites/quincy/rados/tier-2_rados_test_omap.yaml
  suites/quincy/rados/tier-2_rados_trim_tests.yaml
  suites/quincy/rados/tier-3_rados_test-location-stretch-mode.yaml
  suites/reef/rados/tier-2_rados_test_omap.yaml
  suites/reef/rados/tier-2_rados_trim_tests.yaml
  suites/reef/rados/tier-3_rados_test-location-stretch-mode.yaml
  suites/squid/rados/tier-2_rados_test_omap.yaml
  suites/squid/rados/tier-2_rados_trim_tests.yaml
  suites/squid/rados/tier-3_rados_test-location-stretch-mode.yaml
  suites/squid/rados/tier-4_rados_tests.yaml
  tests/rados/test_bluestoretool_workflows.py
  tests/rados/test_cephdf.py
  tests/rados/test_osd_onode_trimming.py
  tests/rados/test_pool_osd_recovery.py
Labels: RADOS, lgtm, Ready-for-review, tfa-issue-fix

#4216 Add support for --subvol and --group options in snap-schedule test sc…
  tests/cephfs/snapshot_clone/cephfs_snap_utils.py
  tests/cephfs/snapshot_clone/snap_schedule_retention_vol_subvol.py
Labels: lgtm

#4219 [TFA] Moving indexless bucket tescase from sanity suite
  suites/reef/rgw/sanity_rgw.yaml
  suites/reef/rgw/tier-1_rgw.yaml
  suites/squid/rgw/sanity_rgw.yaml
  suites/squid/rgw/tier-1_rgw.yaml
Labels: RGW, lgtm, tfa-issue-fix

#4223 TFA: Comment the Ratelimit test at global scope
  suites/reef/rgw/tier-2_rgw_test_using_s3cmd.yaml
  suites/squid/rgw/tier-2_rgw_test_using_s3cmd.yaml
Labels: RGW, lgtm

#4182 Automation of the BZ#2053021-Ceph conmon [DBG] logs flood /var/log/messages causing filesystem to fill up
  suites/pacific/rados/tier-2_rados_test-pool-functionalities.yaml
  suites/quincy/rados/tier-2_rados_test-pool-functionalities.yaml
  suites/quincy/rados/tier-3_rados_test-4-node-ecpools.yaml
  suites/reef/rados/test_rados_all_generic_features.yaml
  suites/reef/rados/tier-2_rados_test-pool-functionalities.yaml
  suites/reef/rados/tier-3_rados_test-4-node-ecpools.yaml
  suites/squid/rados/tier-2_rados_test-pool-functionalities.yaml
  suites/squid/rados/tier-3_rados_test-4-node-8+6-msr-ecpools.yaml
  suites/squid/rados/tier-3_rados_test-4-node-ecpools.yaml
  tests/rados/test_scrub_log.py
Labels: RADOS, lgtm, Polarion testcase, customer

#4225 Adding ceph-perf project to volume cleanup script
  utility/psi_volume_cleanup.py
Labels: lgtm

#4218 Verify Root squash with non root user
  suites/quincy/cephfs/tier-2_cephfs_test-clients.yaml
  suites/reef/cephfs/tier-2_cephfs_test-clients.yaml
  suites/squid/cephfs/tier-2_cephfs_test-clients.yaml
  tests/cephfs/clients/client_root_squash_non_root_user.py
Labels: lgtm

#4226 [Conf] Add RHEL 9.5 inventories
  conf/inventory/rhel-9-latest.yaml
  conf/inventory/rhel-9.5-server-x86_64-large.yaml
  conf/inventory/rhel-9.5-server-x86_64-xlarge.yaml
  conf/inventory/rhel-9.5-server-x86_64.yaml
Labels: lgtm

#4221 CEPH-83602685: Tier-2 test to verify deletion of object and pool snaps
  ceph/rados/core_workflows.py
  ceph/rados/pool_workflows.py
  suites/pacific/rados/tier-2_rados_test-brownfield.yaml
  suites/quincy/rados/tier-2_rados_test-brownfield.yaml
  suites/quincy/rados/tier-2_rados_test_bluestore.yaml
  suites/reef/rados/tier-2_rados_test-brownfield.yaml
  suites/squid/rados/tier-2_rados_test-brownfield.yaml
  tests/rados/test_pool_snap.py
Labels: RADOS, lgtm, Tier-2, Polarion testcase, Ready-for-review, close-loop-automation

#4238 Correcting inventory file - rhel-9.5-server-x86_64-xlarge.yaml
  conf/inventory/rhel-9.5-server-x86_64-xlarge.yaml
Labels: lgtm

#4234 Integrate the Checksum tests and CORS test
  suites/squid/rgw/tier-2_rgw_regression_test.yaml
Labels: RGW, lgtm

#4241 Enhance method to fetch OSD list & Enable faster recovery during PG merge
  ceph/rados/core_workflows.py
  tests/rados/test_add_new_osd.py
  tests/rados/test_bluestore_superblock.py
  tests/rados/test_bluestoretool_workflows.py
  tests/rados/test_bug_fixes.py
  tests/rados/test_cephdf.py
  tests/rados/test_crash_daemon.py
  tests/rados/test_libcephsqlite.py
  tests/rados/test_mon_system_operations.py
  tests/rados/test_node_drain_customer_bug.py
  tests/rados/test_norecovery_flag_functionality.py
  tests/rados/test_objectstoretool_workflows.py
  tests/rados/test_osd_async_recovery.py
  tests/rados/test_osd_inprogress_rebalance.py
  tests/rados/test_osd_memory_target.py
  tests/rados/test_osd_rebalance.py
  tests/rados/test_osd_rebalance_snap.py
  tests/rados/test_osd_replacement.py
  tests/rados/test_osd_superblock.py
  tests/rados/test_pg_split.py
  tests/rados/test_replica1.py
Labels: RADOS, lgtm, tfa-issue-fix

#4242 [Conf] Add RHEL 8.2 & 8.3 inventories
  conf/inventory/rhel-8.2-server-x86_64-large.yaml
  conf/inventory/rhel-8.2-server-x86_64.yaml
  conf/inventory/rhel-8.3-server-x86_64-large.yaml
  conf/inventory/rhel-8.3-server-x86_64.yaml
Labels: framework, lgtm

#4244 Fix the condition evaluating the default timeout
  ceph/ceph.py
Labels: lgtm, approved

#4227 bootstrap.py: Turning off balancer module on the cluster post bootstrap
  ceph/ceph_admin/bootstrap.py
Labels: Workaround, lgtm, approved

#4228 Automation for CEPH-83597243 - Test to verify RBD image with zero size
  suites/quincy/rbd/tier-2_rbd_regression.yaml
  suites/reef/rbd/tier-2_rbd_regression.yaml
  suites/squid/rbd/tier-2_rbd_regression.yaml
  tests/rbd/test_rbd_image_zero_size.py
Labels: RBD, lgtm, approved

#4252 [LibFix] Add RHCEPH 8 released repos
  ceph/ceph_admin/__init__.py
  cli/utilities/configure.py
  tests/cephadm/test_client.py
Labels: lgtm, approved

#4237 This PR adds data and metadata ops after upgrading secondary zone
  suites/squid/rgw/tier-1_rgw_ms_upgrade_61GA_to_8x_latest.yaml
  suites/squid/rgw/tier-1_rgw_ms_upgrade_71GA_to_8x_latest.yaml
Labels: RGW, lgtm, ceph-bug-automate

#4253 [TFA] Fix the issue with HEALTH_WARNING post upgrade
  conf/6-node-cluster-with-1-client.yaml
  suites/reef/upgrades/tier1-upgrade-rhcs-5x-to-7x.yaml
Labels: lgtm

#4233 Check mon connection scores post installation of cluster
  ceph/rados/monitor_workflows.py
  suites/quincy/rados/tier-2_rados_test-bugfixes.yaml
  suites/reef/rados/tier-2_rados_test-bugfixes.yaml
  suites/squid/rados/tier-2_rados_test-bugfixes.yaml
  tests/rados/test_mon_connection_scores.py
Labels: RADOS, lgtm, Tier-2, Polarion testcase

#4254 Fixing the Regression failures
  tests/cephfs/cephfs_nfs/nfs_info_cluster_id_and_ls_export_detailed.py
  tests/cephfs/clients/client_caps_update_validation.py
  tests/cephfs/snapshot_clone/cephfs_snap_utils.py
Labels: lgtm, approved

#4256 client metrics TFA
  tests/cephfs/cephfs_metrics/cephfs_metrics_functional.py
  tests/cephfs/cephfs_metrics/cephfs_metrics_scale.py
Labels: lgtm, approved, tfa-issue-fix

#4247 CI integration of Bucket owner change with reshard CEPH-83574627
  suites/reef/rgw/tier-2_rgw_ms_regression_test.yaml
  suites/squid/rgw/tier-2_rgw_ms_regression_test.yaml
Labels: RGW, lgtm

#4266 TFA fix in cg_snap_neg_1 to include fs_name during cg_quiesce
  suites/squid/cephfs/tier-1_cephfs_cg_quiesce.yaml
  tests/cephfs/snapshot_clone/cg_snap_test.py
Labels: lgtm

#4222 subvolume and group enhancement testing
  suites/pacific/cephfs/tier-2_cephfs_test-volume-management.yaml
  tests/cephfs/cephfs_vol_management/cephfs_vol_mgmt_subvolume_group_enhancement.py
Labels: lgtm

#4240 [TFA][NFS-Ganesha] Fix Pynfs test failure
  suites/squid/nfs/tier0-nfs-ganesha-v3.yaml
  tests/nfs/nfs_file_truncate.py
  tests/nfs/nfs_verify_pynfs.py
  tests/nfs/nfs_verify_read_write_operations.py
Labels: lgtm

#4265 [TFA] Removing known issue comment for testcase where bz is fixed
  suites/pacific/rgw/tier-2_rgw_test-lc-prefix.yaml
  suites/reef/rgw/tier-2_rgw_regression_extended.yaml
  suites/reef/rgw/tier-2_rgw_test_lifecycle.yaml
  suites/reef/rgw/tier-2_ssl_rgw_ecpool_test.yaml
  suites/squid/rgw/sanity_rgw.yaml
  suites/squid/rgw/tier-1_rgw.yaml
  suites/squid/rgw/tier-2_rgw_regression_extended.yaml
  suites/squid/rgw/tier-2_rgw_test_bucket_notifications.yaml
  suites/squid/rgw/tier-2_rgw_test_lifecycle.yaml
  suites/squid/rgw/tier-2_ssl_rgw_ecpool_test.yaml
Labels: RGW, lgtm, tfa-issue-fix

#4260 Enhance system test automation for parallelism and crash configuration
  suites/squid/cephfs/tier-3_cephfs_system_test.yaml
  tests/cephfs/cephfs_crash_util.py
  tests/cephfs/cephfs_system/cephfs_system_utils.py
  tests/cephfs/cephfs_system/cephfs_systest_client_io.py
  tests/cephfs/cephfs_system/cephfs_systest_setup.py
Labels: Ceph-FS, lgtm

#4259 Merging mirror HA suite in weekly
  suites/squid/cephfs/tier-2_cephfs_mirror_ha.yaml
  tests/cephfs/cephfs_mirroring/test_cephfs_mirroring_configure_cephfs_mirroring_ha_on_4_nodes.py
  tests/cephfs/cephfs_mirroring/test_cephfs_mirroring_configure_cephfs_mirroring_ha_using_spec.py
Labels: lgtm

#4268 Upstream suite for tier-1
  suites/squid/upstream/tier-1_rgw_upstream.yaml
Labels: RGW, lgtm, upstream, tfa-issue-fix
