Repository red-hat-storage/cephci, pull requests merged in 2024-10, with the labels that each got.

#4139 Modified the dd if command bs value
  tests/nvmeof/test_ceph_nvmeof_neg_tests.py
Labels: lgtm, nvmeof

#4141 Fix gateway operations suite
  suites/reef/nvmeof/tier-2_nvmeof_gateway_operations.yaml
Labels: lgtm, nvmeof, 8.0

#4142 [Squid][Automation][SMB]Add earmark support
  cli/ceph/smb/share.py
  suites/squid/smb/tier-1-smb.yaml
  tests/smb/smb_deployment_earmark.py
  tests/smb/smb_operations.py
Labels: lgtm

#4148 [reef]Fix gateway operations suite
  suites/squid/nvmeof/tier-2_nvmeof_gateway_operations.yaml
  tests/nvmeof/workflows/ha.py
Labels: lgtm, 8.0

#4149 [NVMe] update build URL for b2b upgrade suites
  suites/squid/nvmeof/tier-2_nvmeof_1gwgroup_8gwnodes_ha_tests.yaml
  suites/squid/nvmeof/tier-2_nvmeof_b2b_upgrade.yaml
  suites/squid/nvmeof/tier-2_nvmeof_b2b_upgrade_with_mtls.yaml
Labels: lgtm, approved, nvmeof, 8.0

#4145 Fixing background commands to redirect the output
  tests/cephfs/clients/file_lock_on_mounts.py
  tests/cephfs/clients/file_unlink_on_clients.py
Labels: lgtm

#4147 Handle last read call to streams in long_running
  ceph/ceph.py
Labels: lgtm

#4117 RHCEPHQE-15796: TFA fix to make osd_memory_target config update relative to cluster
  ceph/rados/core_workflows.py
  ceph/rados/utils.py
  suites/pacific/rados/tier-2_rados_test-osd-rebalance.yaml
  suites/quincy/rados/tier-2_rados_test-osd-rebalance.yaml
  suites/reef/rados/tier-2_rados_test-osd-rebalance.yaml
  suites/squid/rados/tier-2_rados_test-osd-rebalance.yaml
  tests/rados/test_bluestoretool_workflows.py
  tests/rados/test_cephdf.py
  tests/rados/test_osd_compaction.py
  tests/rados/test_osd_df.py
  tests/rados/test_osd_ecpool_inconsistency_scenario.py
  tests/rados/test_osd_memory_target.py
Labels: RADOS, lgtm, tfa-issue-fix

#4140 Adding EC support for cephfs top suite
  suites/squid/cephfs/tier-3_cephfs_test_cephfs-top.yaml
  tests/cephfs/cephfs_top/cephfs_top_dump.py
  tests/cephfs/cephfs_top/cephfs_top_initiate.py
  tests/cephfs/cephfs_top/cephfs_top_negative_tests.py
Labels: lgtm

#4124 Adding EC support for System suite
  tests/cephfs/cephfs_system/mds_admin_daemon_socket_dump.py
  tests/cephfs/cephfs_system/mds_admin_daemon_socket_perf_flush_log.py
  tests/cephfs/cephfs_system/mds_failover_standby_replay_systemic_test.py
  tests/cephfs/cephfs_system/mds_failure_with_client_IO.py
  tests/cephfs/cephfs_system/mds_nfs_node_failure_ops.py
  tests/cephfs/cephfs_system/mds_node_failure_ops.py
  tests/cephfs/cephfs_system/mds_node_remove_with_IO.py
  tests/cephfs/cephfs_system/mds_shutdown_together_io_continue.py
  tests/cephfs/cephfs_system/mon_failure_with_client_IO.py
  tests/cephfs/cephfs_system/mon_node_failure_ops.py
  tests/cephfs/cephfs_system/osd_failure_with_client_IO.py
  tests/cephfs/cephfs_system/osd_node_failure_ops.py
  tests/cephfs/cephfs_system/shutdown_mds_bring_one_by_one.py
  tests/cephfs/cephfs_system/snap_rollback_with_node_reboots.py
Labels: lgtm

#4150 uncomment the fuse-mount code that was commented unknowingly in previ…
  tests/cephfs/cephfs_upgrade/cephfs_post_upgrade_validation.py
Labels: lgtm

#4152 Update setting public network at global level instead of mon
  ceph/ceph_admin/bootstrap.py
Labels: framework, lgtm

#4146 Implement tfa fix suggested in BZ2284364
  tests/cephfs/snapshot_clone/cephfs_cg_io.py
Labels: lgtm

#4154 Fixing minor issue in mirror suite
  tests/cephfs/cephfs_mirroring/test_cephfs_mirroring_with_snap_schedule.py
Labels: lgtm

#4133 inconsistent object repair in test_osd_replicated_inconsistency_scenario.py
  suites/pacific/rados/tier-2_rados_test-bugfixes.yaml
  suites/quincy/rados/tier-2_rados_test-bugfixes.yaml
  suites/reef/rados/tier-2_rados_test-bugfixes.yaml
  suites/squid/rados/tier-2_rados_test-bugfixes.yaml
  tests/rados/test_inconsistency_osd_epoch.py
  tests/rados/test_osd_replicated_inconsistency_scenario.py
Labels: RADOS, lgtm, tfa-issue-fix

#4093 integrating GetObjectAttributes tests into cephci
  suites/squid/rgw/tier-1_rgw.yaml
Labels: pr-verified, RGW, lgtm, early-automation, 8.0

#4153 Revert recent change in ceph osd df test
  tests/rados/stretch_cluster.py
  tests/rados/test_osd_compaction.py
  tests/rados/test_osd_df.py
Labels: lgtm, tfa-issue-fix

#4144 Remove known issue BZ2269490
  suites/pacific/rgw/tier-2_rgw_regression.yaml
  suites/quincy/rgw/tier-2_rgw_regression_extended.yaml
  suites/reef/rgw/tier-2_rgw_regression_extended.yaml
  suites/squid/rgw/tier-2_rgw_regression_extended.yaml
Labels: RGW, lgtm, tfa-issue-fix

#4166 TFA - Remove unwanted selinux labels and increase timeout
  tests/cephfs/clients/test_selinux_relabel.py
Labels: Ceph-FS, lgtm

#4077 Automation of - BZ#2305677-Ceph mgr crashed after a mgr failover with the message mgr operator() Failed to run module in active mode
  ceph/rados/mgr_workflows.py
  suites/reef/rados/tier-2_rados_test-drain-customer-issue.yaml
  suites/squid/rados/tier-2_rados_test-drain-customer-issue.yaml
  tests/rados/test_node_drain_customer_bug.py
Labels: RADOS, lgtm, Polarion testcase

#4160 Switch rados bench long_running to timeouts | Fix CBT bluefs-stats validation for Pacific
  ceph/rados/core_workflows.py
  ceph/rados/rados_bench.py
  tests/rados/test_bluestoretool_workflows.py
Labels: tfa-issue-fix

#4167 [TfaFix]Fix nfs deployment failures
  suites/quincy/cephadm/tier-1_os_tuning_profiles.yaml
  suites/reef/cephadm/tier1-os-tuning-profiles.yaml
  suites/squid/cephadm/tier1-os-tuning-profiles.yaml
Labels: lgtm, tfa-issue-fix

#4171 [Test] Validate the /request endpoint of RESTful module
  api/restful/request.py
  suites/squid/cephmgr/tier2-restful-endpoint-operations.yaml
  tests/mgr/test_restful_operations_request_endpoint.py
Labels: lgtm

#4170 [TFA]: Rearrange version id null testcase
  suites/squid/rgw/tier-2_rgw_ms_regression_test.yaml
Labels: pr-verified, RGW, lgtm, tfa-issue-fix

#4156 Addition of tests for 3AZ Cluster Scenarios - Netsplit b/w DCs
  ceph/rados/core_workflows.py
  conf/squid/rados/3AZ-cluster-rhos-1.yaml
  conf/squid/rados/3AZ-cluster-rhos-d.yaml
  suites/reef/rados/tier-3_rados_test-3-AZ-Cluster.yaml
  suites/squid/rados/tier-3_rados_test-3-AZ-Cluster.yaml
  tests/rados/test_stretch_n-az_netsplit_scenarios.py
  tests/rados/test_stretch_netsplit_scenarios.py
Labels: RADOS, lgtm, 8.0

#4164 Include Cleanup & enable_standby_replay to scale tests
  suites/reef/cephfs/tier-3_cephfs_scale_baremetal.yaml
  suites/squid/cephfs/tier-3_cephfs_scale_baremetal.yaml
  tests/cephfs/cephfs_scale/run_scale_io.py
Labels: Ceph-FS, lgtm

#4173 adding kernel enhancement
  suites/pacific/cephfs/tier-0_fs_kernel.yaml
  suites/quincy/cephfs/tier-0_fs_kernel.yaml
  suites/reef/cephfs/tier-0_fs_kernel.yaml
  tests/cephfs/cephfs_bugs/fsstress_kernel_verification.py
  tests/cephfs/xfs_test.py
Labels: lgtm

#4135 [Rados-RGW] RGW multisite erasure-code-profile pool suite with bilog trim testcase
  suites/squid/rgw/tier-2_rgw_rados_multisite_ecpool.yaml
Labels: RGW, RADOS, lgtm, close-loop-automation

#4175 [Test] Validate the /server endpoint of RESTful module
  api/restful/server.py
  suites/squid/cephmgr/tier2-restful-endpoint-operations.yaml
  tests/mgr/test_restful_operations_server_endpoint.py
Labels: lgtm

#4169 Adding FS TC 83600107
  suites/quincy/cephfs/tier-3_cephfs_bugs.yaml
  suites/reef/cephfs/tier-3_cephfs_bugs.yaml
  suites/squid/cephfs/tier-3_cephfs_bugs.yaml
  tests/cephfs/cephfs_bugs/test_mds_dir_max_commit_size.py
  tests/cephfs/cephfs_top/cephfs_top_dump.py
  tests/cephfs/cephfs_utilsV1.py
Labels: lgtm

#4174 Align fetch_build_artifacts with upstream recipe file structure
  ceph/ceph_admin/__init__.py
  ceph/ceph_admin/bootstrap.py
  utility/utils.py
Labels: framework, lgtm

#4155 Remove the known issue for test_policy_torrent
  suites/reef/rgw/tier-2_rgw_regression_test.yaml
  suites/squid/rgw/tier-2_rgw_regression_test.yaml
Labels: RGW, lgtm, approved

#4178 [Samba]Add samba metrics image support
  ceph/ceph_admin/bootstrap.py
  cli/ops/cephadm.py
Labels: lgtm, smb

#4177 Switch to install EPEL 9 repo
  pipeline/vars/node_bootstrap.bash
Labels: lgtm

#4172 Rados TFA fixes - Online reads balancer fixes with require_min_compat_client param
  ceph/rados/core_workflows.py
  suites/squid/rados/tier-2_rados_test-clay-ecpool.yaml
  suites/squid/rados/tier-2_rados_test-pool-functionalities.yaml
  tests/rados/test_ec_86.py
  tests/rados/test_online_reads_balancer.py
  tests/rados/test_reads_balancer.py
Labels: RADOS, lgtm, tfa-issue-fix, 8.0

#4168 RHCS 8.0 feature automation - snapdiff
  suites/squid/cephfs/tier-0_cephfs_mirrror_upgrade_6x_to_8x.yaml
  suites/squid/cephfs/tier-0_cephfs_mirrror_upgrade_7x_to_8x.yaml
  suites/squid/cephfs/tier-0_cephfs_mirrror_upgrade_ibm_6x_to_8x.yaml
  suites/squid/cephfs/tier-0_cephfs_mirrror_upgrade_ibm_7x_to_8x.yaml
  tests/cephfs/cephfs_mirroring/snapdiff_perf_improvements_across_releases.py
  tests/cephfs/cephfs_mirroring/validate_snapdiff_perf_results.py
Labels: Ceph-FS, lgtm, New-Feature, 8.0

#4180 [Conf] Update inventory configurations
  conf/inventory/ibm-vpc-rhel-7.9-minimal-amd64-3.yaml
  conf/inventory/ibm-vpc-rhel-8.10-minimal-bx2-2x8.yaml
  conf/inventory/ibm-vpc-rhel-8.10-minimal-bx2-4x16.yaml
  conf/inventory/ibm-vpc-rhel-8.5-minimal-amd64-1.yaml
  conf/inventory/ibm-vpc-rhel-8.6-minimal-amd64-1.yaml
  conf/inventory/ibm-vpc-rhel-8.7-minimal-amd64.yaml
  conf/inventory/ibm-vpc-rhel-8.8-minimal-bx2-2x8.yaml
  conf/inventory/ibm-vpc-rhel-8.8-minimal-bx2-4x16.yaml
  conf/inventory/ibm-vpc-rhel-9.0-minimal-amd64-1.yaml
  conf/inventory/ibm-vpc-rhel-9.1-minimal-amd64.yaml
  conf/inventory/ibm-vpc-rhel-9.2-minimal-bx2-2x8.yaml
  conf/inventory/ibm-vpc-rhel-9.2-minimal-bx2-4x16.yaml
  conf/inventory/ibm-vpc-rhel-9.4-minimal-bx2-2x8.yaml
  conf/inventory/ibm-vpc-rhel-9.4-minimal-bx2-4x16.yaml
  conf/inventory/rhel-7.8-server-x86_64.yaml
  conf/inventory/rhel-7.9-server-x86_64.yaml
  conf/inventory/rhel-8.10-server-x86_64-large.yaml
  conf/inventory/rhel-8.10-server-x86_64.yaml
  conf/inventory/rhel-8.4-server-x86_64.yaml
  conf/inventory/rhel-8.5-server-x86_64-large.yaml
  conf/inventory/rhel-8.5-server-x86_64.yaml
  conf/inventory/rhel-8.6-server-x86_64.yaml
  conf/inventory/rhel-8.7-server-x86_64-large.yaml
  conf/inventory/rhel-8.7-server-x86_64.yaml
  conf/inventory/rhel-8.8-server-x86_64-large.yaml
  conf/inventory/rhel-8.8-server-x86_64.yaml
  conf/inventory/rhel-8.9-server-x86_64-large.yaml
  conf/inventory/rhel-8.9-server-x86_64.yaml
  conf/inventory/rhel-9.0-server-x86_64-large.yaml
  conf/inventory/rhel-9.0-server-x86_64.yaml
  conf/inventory/rhel-9.1-server-x86_64.yaml
  conf/inventory/rhel-9.2-server-x86_64-large.yaml
  conf/inventory/rhel-9.2-server-x86_64-xlarge.yaml
  conf/inventory/rhel-9.2-server-x86_64.yaml
  conf/inventory/rhel-9.3-server-x86_64-large.yaml
  conf/inventory/rhel-9.3-server-x86_64-xlarge.yaml
  conf/inventory/rhel-9.3-server-x86_64.yaml
  conf/inventory/rhel-9.4-server-x86_64-large.yaml
  conf/inventory/rhel-9.4-server-x86_64-xlarge.yaml
  conf/inventory/rhel-9.4-server-x86_64.yaml
  conf/inventory/rhel-9.5-nightly-x86_64-large.yaml
  conf/inventory/rhel-9.5-nightly-x86_64-xlarge.yaml
  conf/inventory/rhel-9.5-nightly-x86_64.yaml
Labels: lgtm, approved

#4181 small kernel url strip
  tests/cephfs/kernel_update.py
Labels: lgtm

#4184 [Squid][Monitoring Stack]Update support for new image
  ceph/ceph_admin/bootstrap.py
  cli/ops/cephadm.py
Labels: lgtm, DMFG

#4183 CEPH-83600867: Verify space utilization by bluefs DB in under check
  ceph/rados/core_workflows.py
  ceph/rados/pool_workflows.py
  suites/quincy/rados/tier-2_rados_test_bluestore.yaml
  suites/quincy/rados/tier-2_rados_test_omap.yaml
  suites/reef/rados/tier-2_rados_test_bluestore.yaml
  suites/reef/rados/tier-2_rados_test_omap.yaml
  suites/squid/rados/tier-2_rados_test_bluestore.yaml
  tests/rados/test_bluefs_space.py
Labels: RADOS, lgtm, Tier-2, Polarion testcase, close-loop-automation

#4179 Fixing change in behavior for nfs export user_id
  conf/pacific/cephfs/tier-2_cephfs_9-node-cluster.yaml
  tests/cephfs/cephfs_nfs/nfs_config_reset.py
  tests/cephfs/cephfs_nfs/nfs_export_config.py
  tests/cephfs/cephfs_nfs/nfs_multiple_export_using_single_conf.py
Labels: lgtm

#4185 [TFA][Cephci] Update oathtool package
  suites/pacific/rgw/tier-2_rgw_regression.yaml
  suites/quincy/baremetal_pipeline/tier-2_rgw_regression.yaml
  suites/quincy/rgw/tier-2_rgw_regression.yaml
  suites/reef/rgw/sanity_rgw.yaml
  suites/reef/rgw/tier-2_rgw_regression_test.yaml
  suites/squid/rgw/sanity_rgw.yaml
  suites/squid/rgw/tier-2_rgw_regression_test.yaml
Labels: pr-verified, RGW, lgtm, tfa-issue-fix

#4186 [TFA][Cephci] kafka java package issue
  suites/pacific/rgw/tier-2_rgw_ms_test-bucket-notifications.yaml
  suites/pacific/rgw/tier-2_rgw_singlesite_to_multisite.yaml
  suites/pacific/rgw/tier-2_rgw_test-bucket-notifications-kafka-sasl-sanity.yaml
  suites/pacific/rgw/tier-2_rgw_test-bucket-notifications-kafka-sasl-scheduled.yaml
  suites/pacific/rgw/tier-2_rgw_test-bucket-notifications-kafka-ssl.yaml
  suites/pacific/rgw/tier-2_rgw_test-bucket-notifications.yaml
  suites/pacific/rgw/tier-2_rgw_test_5-3_specific_fixes.yaml
  suites/pacific/rgw/tier-2_sse_s3_encryption.yaml
  suites/quincy/rgw/tier-2_rgw_6_1_fixes.yaml
  suites/quincy/rgw/tier-2_rgw_ms_test-bucket-notifications.yaml
  suites/quincy/rgw/tier-2_rgw_ssl_test_bucket_notifications.yaml
  suites/quincy/rgw/tier-2_rgw_test-bucket-notifications-kafka-sasl-sanity.yaml
  suites/quincy/rgw/tier-2_rgw_test-bucket-notifications-kafka-sasl-scheduled.yaml
  suites/quincy/rgw/tier-2_rgw_test-bucket-notifications-kafka-ssl.yaml
  suites/quincy/rgw/tier-2_rgw_test_bucket_notifications.yaml
  suites/reef/rgw/sanity_rgw.yaml
  suites/reef/rgw/sanity_rgw_multisite.yaml
  suites/reef/rgw/tier-2_rgw_ms-archive.yaml
  suites/reef/rgw/tier-2_rgw_ms_test_bucket_notifications.yaml
  suites/reef/rgw/tier-2_rgw_regression_extended.yaml
  suites/reef/rgw/tier-2_rgw_test_bucket_notifications.yaml
  suites/reef/rgw/tier-2_rgw_test_bucket_notifications_kafka_sasl.yaml
  suites/reef/rgw/tier-2_rgw_test_bucket_notifications_kafka_ssl.yaml
  suites/reef/rgw/tier-2_ssl_rgw_test_bucket_notifications.yaml
  suites/squid/rgw/sanity_rgw.yaml
  suites/squid/rgw/sanity_rgw_multisite.yaml
  suites/squid/rgw/tier-2_rgw_ms-archive.yaml
  suites/squid/rgw/tier-2_rgw_ms_test_bucket_notifications.yaml
  suites/squid/rgw/tier-2_rgw_regression_extended.yaml
  suites/squid/rgw/tier-2_rgw_test_bucket_notifications.yaml
  suites/squid/rgw/tier-2_rgw_test_bucket_notifications_kafka_sasl.yaml
  suites/squid/rgw/tier-2_rgw_test_bucket_notifications_kafka_ssl.yaml
  suites/squid/rgw/tier-2_ssl_rgw_regression_test.yaml
Labels: pr-verified, RGW, lgtm, tfa-issue-fix

#4192 Installing ceph-common on cluster nodes
  run.py
  utility/sosreport.py
Labels: lgtm

#4196 Adding mirror suite with sequential upgrade
  suites/squid/cephfs/tier-0_cephfs_mirrror_upgrade_seq_6x_to_8x.yaml
  tests/cephfs/cephfs_mirror_upgrade/post_upgrade_validate.py
  tests/cephfs/cephfs_utilsV1.py
Labels: lgtm

#4193 Added post validation steps for NS loadbalancing scenarios
  suites/squid/nvmeof/tier-2_nvmeof_1gwgroup_8gwnodes_loadbalancing_tests.yaml
  tests/nvmeof/test_ceph_nvmeof_loadbalancing.py
  tests/nvmeof/workflows/ha.py
Labels: lgtm, nvmeof, 8.0
